//
// Licensed to the Apache Software Foundation (ASF) under one or more
// contributor license agreements.  See the NOTICE file distributed with
// this work for additional information regarding copyright ownership.
// The ASF licenses this file to You under the Apache License, Version 2.0
// (the "License"); you may not use this file except in compliance with
// the License.  You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: spark/connect/catalog.proto

package generated

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Catalog messages are marked as unstable.
type Catalog struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to CatType:
	//
	//	*Catalog_CurrentDatabase
	//	*Catalog_SetCurrentDatabase
	//	*Catalog_ListDatabases
	//	*Catalog_ListTables
	//	*Catalog_ListFunctions
	//	*Catalog_ListColumns
	//	*Catalog_GetDatabase
	//	*Catalog_GetTable
	//	*Catalog_GetFunction
	//	*Catalog_DatabaseExists
	//	*Catalog_TableExists
	//	*Catalog_FunctionExists
	//	*Catalog_CreateExternalTable
	//	*Catalog_CreateTable
	//	*Catalog_DropTempView
	//	*Catalog_DropGlobalTempView
	//	*Catalog_RecoverPartitions
	//	*Catalog_IsCached
	//	*Catalog_CacheTable
	//	*Catalog_UncacheTable
	//	*Catalog_ClearCache
	//	*Catalog_RefreshTable
	//	*Catalog_RefreshByPath
	//	*Catalog_CurrentCatalog
	//	*Catalog_SetCurrentCatalog
	//	*Catalog_ListCatalogs
	//	*Catalog_DropTable
	//	*Catalog_DropView
	//	*Catalog_CreateDatabase
	//	*Catalog_DropDatabase
	//	*Catalog_ListPartitions
	//	*Catalog_ListViews
	//	*Catalog_GetTableProperties
	//	*Catalog_GetCreateTableString
	//	*Catalog_TruncateTable
	//	*Catalog_AnalyzeTable
	CatType       isCatalog_CatType `protobuf_oneof:"cat_type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Catalog) Reset() {
	*x = Catalog{}
	mi := &file_spark_connect_catalog_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Catalog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Catalog) ProtoMessage() {}

func (x *Catalog) ProtoReflect() protoreflect.Message {
	mi := &file_spark_connect_catalog_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Catalog.ProtoReflect.Descriptor instead.
func (*Catalog) Descriptor() ([]byte, []int) {
	return file_spark_connect_catalog_proto_rawDescGZIP(), []int{0}
}

func (x *Catalog) GetCatType() isCatalog_CatType {
	if x != nil {
		return x.CatType
	}
	return nil
}

func (x *Catalog) GetCurrentDatabase() *CurrentDatabase {
	if x != nil {
		if x, ok := x.CatType.(*Catalog_CurrentDatabase); ok {
			return x.CurrentDatabase
		}
	}
	return nil
}

func (x *Catalog) GetSetCurrentDatabase() *SetCurrentDatabase {
	if x != nil {
		if x, ok := x.CatType.(*Catalog_SetCurrentDatabase); ok {
			return x.SetCurrentDatabase
		}
	}
	return nil
}

func (x *Catalog) GetListDatabases() *ListDatabases {
	if x != nil {
		if x, ok := x.CatType.(*Catalog_ListDatabases); ok {
			return x.ListDatabases
		}
	}
	return nil
}

func (x *Catalog) GetListTables() *ListTables {
	if x != nil {
		if x, ok := x.CatType.(*Catalog_ListTables); ok {
			return x.ListTables
		}
	}
	return nil
}

func (x *Catalog) GetListFunctions() *ListFunctions {
	if x != nil {
		if x, ok := x.CatType.(*Catalog_ListFunctions); ok {
			return x.ListFunctions
		}
	}
	return nil
}

func (x *Catalog) GetListColumns() *ListColumns {
	if x != nil {
		if x, ok := x.CatType.(*Catalog_ListColumns); ok {
			return x.ListColumns
		}
	}
	return nil
}

func (x *Catalog) GetGetDatabase() *GetDatabase {
	if x != nil {
		if x, ok := x.CatType.(*Catalog_GetDatabase); ok {
			return x.GetDatabase
		}
	}
	return nil
}

func (x *Catalog) GetGetTable() *GetTable {
	if x != nil {
		if x, ok := x.CatType.(*Catalog_GetTable); ok {
			return x.GetTable
		}
	}
	return nil
}

func (x *Catalog) GetGetFunction() *GetFunction {
	if x != nil {
		if x, ok := x.CatType.(*Catalog_GetFunction); ok {
			return x.GetFunction
		}
	}
	return nil
}

func (x *Catalog) GetDatabaseExists() *DatabaseExists {
	if x != nil {
		if x, ok := x.CatType.(*Catalog_DatabaseExists); ok {
			return x.DatabaseExists
		}
	}
	return nil
}

func (x *Catalog) GetTableExists() *TableExists {
	if x != nil {
		if x, ok := x.CatType.(*Catalog_TableExists); ok {
			return x.TableExists
		}
	}
	return nil
}

func (x *Catalog) GetFunctionExists() *FunctionExists {
	if x != nil {
		if x, ok := x.CatType.(*Catalog_FunctionExists); ok {
			return x.FunctionExists
		}
	}
	return nil
}

func (x *Catalog) GetCreateExternalTable() *CreateExternalTable {
	if x != nil {
		if x, ok := x.CatType.(*Catalog_CreateExternalTable); ok {
			return x.CreateExternalTable
		}
	}
	return nil
}

func (x *Catalog) GetCreateTable() *CreateTable {
	if x != nil {
		if x, ok := x.CatType.(*Catalog_CreateTable); ok {
			return x.CreateTable
		}
	}
	return nil
}

func (x *Catalog) GetDropTempView() *DropTempView {
	if x != nil {
		if x, ok := x.CatType.(*Catalog_DropTempView); ok {
			return x.DropTempView
		}
	}
	return nil
}

func (x *Catalog) GetDropGlobalTempView() *DropGlobalTempView {
	if x != nil {
		if x, ok := x.CatType.(*Catalog_DropGlobalTempView); ok {
			return x.DropGlobalTempView
		}
	}
	return nil
}

func (x *Catalog) GetRecoverPartitions() *RecoverPartitions {
	if x != nil {
		if x, ok := x.CatType.(*Catalog_RecoverPartitions); ok {
			return x.RecoverPartitions
		}
	}
	return nil
}

func (x *Catalog) GetIsCached() *IsCached {
	if x != nil {
		if x, ok := x.CatType.(*Catalog_IsCached); ok {
			return x.IsCached
		}
	}
	return nil
}

func (x *Catalog) GetCacheTable() *CacheTable {
	if x != nil {
		if x, ok := x.CatType.(*Catalog_CacheTable); ok {
			return x.CacheTable
		}
	}
	return nil
}

func (x *Catalog) GetUncacheTable() *UncacheTable {
	if x != nil {
		if x, ok := x.CatType.(*Catalog_UncacheTable); ok {
			return x.UncacheTable
		}
	}
	return nil
}

func (x *Catalog) GetClearCache() *ClearCache {
	if x != nil {
		if x, ok := x.CatType.(*Catalog_ClearCache); ok {
			return x.ClearCache
		}
	}
	return nil
}

func (x *Catalog) GetRefreshTable() *RefreshTable {
	if x != nil {
		if x, ok := x.CatType.(*Catalog_RefreshTable); ok {
			return x.RefreshTable
		}
	}
	return nil
}

func (x *Catalog) GetRefreshByPath() *RefreshByPath {
	if x != nil {
		if x, ok := x.CatType.(*Catalog_RefreshByPath); ok {
			return x.RefreshByPath
		}
	}
	return nil
}

func (x *Catalog) GetCurrentCatalog() *CurrentCatalog {
	if x != nil {
		if x, ok := x.CatType.(*Catalog_CurrentCatalog); ok {
			return x.CurrentCatalog
		}
	}
	return nil
}

func (x *Catalog) GetSetCurrentCatalog() *SetCurrentCatalog {
	if x != nil {
		if x, ok := x.CatType.(*Catalog_SetCurrentCatalog); ok {
			return x.SetCurrentCatalog
		}
	}
	return nil
}

func (x *Catalog) GetListCatalogs() *ListCatalogs {
	if x != nil {
		if x, ok := x.CatType.(*Catalog_ListCatalogs); ok {
			return x.ListCatalogs
		}
	}
	return nil
}

func (x *Catalog) GetDropTable() *DropTable {
	if x != nil {
		if x, ok := x.CatType.(*Catalog_DropTable); ok {
			return x.DropTable
		}
	}
	return nil
}

func (x *Catalog) GetDropView() *DropView {
	if x != nil {
		if x, ok := x.CatType.(*Catalog_DropView); ok {
			return x.DropView
		}
	}
	return nil
}

func (x *Catalog) GetCreateDatabase() *CreateDatabase {
	if x != nil {
		if x, ok := x.CatType.(*Catalog_CreateDatabase); ok {
			return x.CreateDatabase
		}
	}
	return nil
}

func (x *Catalog) GetDropDatabase() *DropDatabase {
	if x != nil {
		if x, ok := x.CatType.(*Catalog_DropDatabase); ok {
			return x.DropDatabase
		}
	}
	return nil
}

func (x *Catalog) GetListPartitions() *ListPartitions {
	if x != nil {
		if x, ok := x.CatType.(*Catalog_ListPartitions); ok {
			return x.ListPartitions
		}
	}
	return nil
}

func (x *Catalog) GetListViews() *ListViews {
	if x != nil {
		if x, ok := x.CatType.(*Catalog_ListViews); ok {
			return x.ListViews
		}
	}
	return nil
}

func (x *Catalog) GetGetTableProperties() *GetTableProperties {
	if x != nil {
		if x, ok := x.CatType.(*Catalog_GetTableProperties); ok {
			return x.GetTableProperties
		}
	}
	return nil
}

func (x *Catalog) GetGetCreateTableString() *GetCreateTableString {
	if x != nil {
		if x, ok := x.CatType.(*Catalog_GetCreateTableString); ok {
			return x.GetCreateTableString
		}
	}
	return nil
}

func (x *Catalog) GetTruncateTable() *TruncateTable {
	if x != nil {
		if x, ok := x.CatType.(*Catalog_TruncateTable); ok {
			return x.TruncateTable
		}
	}
	return nil
}

func (x *Catalog) GetAnalyzeTable() *AnalyzeTable {
	if x != nil {
		if x, ok := x.CatType.(*Catalog_AnalyzeTable); ok {
			return x.AnalyzeTable
		}
	}
	return nil
}

type isCatalog_CatType interface {
	isCatalog_CatType()
}

type Catalog_CurrentDatabase struct {
	CurrentDatabase *CurrentDatabase `protobuf:"bytes,1,opt,name=current_database,json=currentDatabase,proto3,oneof"`
}

type Catalog_SetCurrentDatabase struct {
	SetCurrentDatabase *SetCurrentDatabase `protobuf:"bytes,2,opt,name=set_current_database,json=setCurrentDatabase,proto3,oneof"`
}

type Catalog_ListDatabases struct {
	ListDatabases *ListDatabases `protobuf:"bytes,3,opt,name=list_databases,json=listDatabases,proto3,oneof"`
}

type Catalog_ListTables struct {
	ListTables *ListTables `protobuf:"bytes,4,opt,name=list_tables,json=listTables,proto3,oneof"`
}

type Catalog_ListFunctions struct {
	ListFunctions *ListFunctions `protobuf:"bytes,5,opt,name=list_functions,json=listFunctions,proto3,oneof"`
}

type Catalog_ListColumns struct {
	ListColumns *ListColumns `protobuf:"bytes,6,opt,name=list_columns,json=listColumns,proto3,oneof"`
}

type Catalog_GetDatabase struct {
	GetDatabase *GetDatabase `protobuf:"bytes,7,opt,name=get_database,json=getDatabase,proto3,oneof"`
}

type Catalog_GetTable struct {
	GetTable *GetTable `protobuf:"bytes,8,opt,name=get_table,json=getTable,proto3,oneof"`
}

type Catalog_GetFunction struct {
	GetFunction *GetFunction `protobuf:"bytes,9,opt,name=get_function,json=getFunction,proto3,oneof"`
}

type Catalog_DatabaseExists struct {
	DatabaseExists *DatabaseExists `protobuf:"bytes,10,opt,name=database_exists,json=databaseExists,proto3,oneof"`
}

type Catalog_TableExists struct {
	TableExists *TableExists `protobuf:"bytes,11,opt,name=table_exists,json=tableExists,proto3,oneof"`
}

type Catalog_FunctionExists struct {
	FunctionExists *FunctionExists `protobuf:"bytes,12,opt,name=function_exists,json=functionExists,proto3,oneof"`
}

type Catalog_CreateExternalTable struct {
	CreateExternalTable *CreateExternalTable `protobuf:"bytes,13,opt,name=create_external_table,json=createExternalTable,proto3,oneof"`
}

type Catalog_CreateTable struct {
	CreateTable *CreateTable `protobuf:"bytes,14,opt,name=create_table,json=createTable,proto3,oneof"`
}

type Catalog_DropTempView struct {
	DropTempView *DropTempView `protobuf:"bytes,15,opt,name=drop_temp_view,json=dropTempView,proto3,oneof"`
}

type Catalog_DropGlobalTempView struct {
	DropGlobalTempView *DropGlobalTempView `protobuf:"bytes,16,opt,name=drop_global_temp_view,json=dropGlobalTempView,proto3,oneof"`
}

type Catalog_RecoverPartitions struct {
	RecoverPartitions *RecoverPartitions `protobuf:"bytes,17,opt,name=recover_partitions,json=recoverPartitions,proto3,oneof"`
}

type Catalog_IsCached struct {
	IsCached *IsCached `protobuf:"bytes,18,opt,name=is_cached,json=isCached,proto3,oneof"`
}

type Catalog_CacheTable struct {
	CacheTable *CacheTable `protobuf:"bytes,19,opt,name=cache_table,json=cacheTable,proto3,oneof"`
}

type Catalog_UncacheTable struct {
	UncacheTable *UncacheTable `protobuf:"bytes,20,opt,name=uncache_table,json=uncacheTable,proto3,oneof"`
}

type Catalog_ClearCache struct {
	ClearCache *ClearCache `protobuf:"bytes,21,opt,name=clear_cache,json=clearCache,proto3,oneof"`
}

type Catalog_RefreshTable struct {
	RefreshTable *RefreshTable `protobuf:"bytes,22,opt,name=refresh_table,json=refreshTable,proto3,oneof"`
}

type Catalog_RefreshByPath struct {
	RefreshByPath *RefreshByPath `protobuf:"bytes,23,opt,name=refresh_by_path,json=refreshByPath,proto3,oneof"`
}

type Catalog_CurrentCatalog struct {
	CurrentCatalog *CurrentCatalog `protobuf:"bytes,24,opt,name=current_catalog,json=currentCatalog,proto3,oneof"`
}

type Catalog_SetCurrentCatalog struct {
	SetCurrentCatalog *SetCurrentCatalog `protobuf:"bytes,25,opt,name=set_current_catalog,json=setCurrentCatalog,proto3,oneof"`
}

type Catalog_ListCatalogs struct {
	ListCatalogs *ListCatalogs `protobuf:"bytes,26,opt,name=list_catalogs,json=listCatalogs,proto3,oneof"`
}

type Catalog_DropTable struct {
	DropTable *DropTable `protobuf:"bytes,27,opt,name=drop_table,json=dropTable,proto3,oneof"`
}

type Catalog_DropView struct {
	DropView *DropView `protobuf:"bytes,28,opt,name=drop_view,json=dropView,proto3,oneof"`
}

type Catalog_CreateDatabase struct {
	CreateDatabase *CreateDatabase `protobuf:"bytes,29,opt,name=create_database,json=createDatabase,proto3,oneof"`
}

type Catalog_DropDatabase struct {
	DropDatabase *DropDatabase `protobuf:"bytes,30,opt,name=drop_database,json=dropDatabase,proto3,oneof"`
}

type Catalog_ListPartitions struct {
	ListPartitions *ListPartitions `protobuf:"bytes,31,opt,name=list_partitions,json=listPartitions,proto3,oneof"`
}

type Catalog_ListViews struct {
	ListViews *ListViews `protobuf:"bytes,32,opt,name=list_views,json=listViews,proto3,oneof"`
}

type Catalog_GetTableProperties struct {
	GetTableProperties *GetTableProperties `protobuf:"bytes,33,opt,name=get_table_properties,json=getTableProperties,proto3,oneof"`
}

type Catalog_GetCreateTableString struct {
	GetCreateTableString *GetCreateTableString `protobuf:"bytes,34,opt,name=get_create_table_string,json=getCreateTableString,proto3,oneof"`
}

type Catalog_TruncateTable struct {
	TruncateTable *TruncateTable `protobuf:"bytes,35,opt,name=truncate_table,json=truncateTable,proto3,oneof"`
}

type Catalog_AnalyzeTable struct {
	AnalyzeTable *AnalyzeTable `protobuf:"bytes,36,opt,name=analyze_table,json=analyzeTable,proto3,oneof"`
}

func (*Catalog_CurrentDatabase) isCatalog_CatType() {}

func (*Catalog_SetCurrentDatabase) isCatalog_CatType() {}

func (*Catalog_ListDatabases) isCatalog_CatType() {}

func (*Catalog_ListTables) isCatalog_CatType() {}

func (*Catalog_ListFunctions) isCatalog_CatType() {}

func (*Catalog_ListColumns) isCatalog_CatType() {}

func (*Catalog_GetDatabase) isCatalog_CatType() {}

func (*Catalog_GetTable) isCatalog_CatType() {}

func (*Catalog_GetFunction) isCatalog_CatType() {}

func (*Catalog_DatabaseExists) isCatalog_CatType() {}

func (*Catalog_TableExists) isCatalog_CatType() {}

func (*Catalog_FunctionExists) isCatalog_CatType() {}

func (*Catalog_CreateExternalTable) isCatalog_CatType() {}

func (*Catalog_CreateTable) isCatalog_CatType() {}

func (*Catalog_DropTempView) isCatalog_CatType() {}

func (*Catalog_DropGlobalTempView) isCatalog_CatType() {}

func (*Catalog_RecoverPartitions) isCatalog_CatType() {}

func (*Catalog_IsCached) isCatalog_CatType() {}

func (*Catalog_CacheTable) isCatalog_CatType() {}

func (*Catalog_UncacheTable) isCatalog_CatType() {}

func (*Catalog_ClearCache) isCatalog_CatType() {}

func (*Catalog_RefreshTable) isCatalog_CatType() {}

func (*Catalog_RefreshByPath) isCatalog_CatType() {}

func (*Catalog_CurrentCatalog) isCatalog_CatType() {}

func (*Catalog_SetCurrentCatalog) isCatalog_CatType() {}

func (*Catalog_ListCatalogs) isCatalog_CatType() {}

func (*Catalog_DropTable) isCatalog_CatType() {}

func (*Catalog_DropView) isCatalog_CatType() {}

func (*Catalog_CreateDatabase) isCatalog_CatType() {}

func (*Catalog_DropDatabase) isCatalog_CatType() {}

func (*Catalog_ListPartitions) isCatalog_CatType() {}

func (*Catalog_ListViews) isCatalog_CatType() {}

func (*Catalog_GetTableProperties) isCatalog_CatType() {}

func (*Catalog_GetCreateTableString) isCatalog_CatType() {}

func (*Catalog_TruncateTable) isCatalog_CatType() {}

func (*Catalog_AnalyzeTable) isCatalog_CatType() {}

// See `spark.catalog.currentDatabase`
type CurrentDatabase struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CurrentDatabase) Reset() {
	*x = CurrentDatabase{}
	mi := &file_spark_connect_catalog_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CurrentDatabase) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CurrentDatabase) ProtoMessage() {}

func (x *CurrentDatabase) ProtoReflect() protoreflect.Message {
	mi := &file_spark_connect_catalog_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CurrentDatabase.ProtoReflect.Descriptor instead.
func (*CurrentDatabase) Descriptor() ([]byte, []int) {
	return file_spark_connect_catalog_proto_rawDescGZIP(), []int{1}
}

// See `spark.catalog.setCurrentDatabase`
type SetCurrentDatabase struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// (Required)
	DbName        string `protobuf:"bytes,1,opt,name=db_name,json=dbName,proto3" json:"db_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetCurrentDatabase) Reset() {
	*x = SetCurrentDatabase{}
	mi := &file_spark_connect_catalog_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetCurrentDatabase) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetCurrentDatabase) ProtoMessage() {}

func (x *SetCurrentDatabase) ProtoReflect() protoreflect.Message {
	mi := &file_spark_connect_catalog_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetCurrentDatabase.ProtoReflect.Descriptor instead.
func (*SetCurrentDatabase) Descriptor() ([]byte, []int) {
	return file_spark_connect_catalog_proto_rawDescGZIP(), []int{2}
}

func (x *SetCurrentDatabase) GetDbName() string {
	if x != nil {
		return x.DbName
	}
	return ""
}

// See `spark.catalog.listDatabases`
type ListDatabases struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// (Optional) The pattern that the database name needs to match
	Pattern       *string `protobuf:"bytes,1,opt,name=pattern,proto3,oneof" json:"pattern,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDatabases) Reset() {
	*x = ListDatabases{}
	mi := &file_spark_connect_catalog_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDatabases) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDatabases) ProtoMessage() {}

func (x *ListDatabases) ProtoReflect() protoreflect.Message {
	mi := &file_spark_connect_catalog_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDatabases.ProtoReflect.Descriptor instead.
func (*ListDatabases) Descriptor() ([]byte, []int) {
	return file_spark_connect_catalog_proto_rawDescGZIP(), []int{3}
}

func (x *ListDatabases) GetPattern() string {
	if x != nil && x.Pattern != nil {
		return *x.Pattern
	}
	return ""
}

// See `spark.catalog.listTables`
type ListTables struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// (Optional)
	DbName *string `protobuf:"bytes,1,opt,name=db_name,json=dbName,proto3,oneof" json:"db_name,omitempty"`
	// (Optional) The pattern that the table name needs to match
	Pattern       *string `protobuf:"bytes,2,opt,name=pattern,proto3,oneof" json:"pattern,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTables) Reset() {
	*x = ListTables{}
	mi := &file_spark_connect_catalog_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTables) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTables) ProtoMessage() {}

func (x *ListTables) ProtoReflect() protoreflect.Message {
	mi := &file_spark_connect_catalog_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTables.ProtoReflect.Descriptor instead.
func (*ListTables) Descriptor() ([]byte, []int) {
	return file_spark_connect_catalog_proto_rawDescGZIP(), []int{4}
}

func (x *ListTables) GetDbName() string {
	if x != nil && x.DbName != nil {
		return *x.DbName
	}
	return ""
}

func (x *ListTables) GetPattern() string {
	if x != nil && x.Pattern != nil {
		return *x.Pattern
	}
	return ""
}

// See `spark.catalog.listFunctions`
type ListFunctions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// (Optional)
	DbName *string `protobuf:"bytes,1,opt,name=db_name,json=dbName,proto3,oneof" json:"db_name,omitempty"`
	// (Optional) The pattern that the function name needs to match
	Pattern       *string `protobuf:"bytes,2,opt,name=pattern,proto3,oneof" json:"pattern,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFunctions) Reset() {
	*x = ListFunctions{}
	mi := &file_spark_connect_catalog_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFunctions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFunctions) ProtoMessage() {}

func (x *ListFunctions) ProtoReflect() protoreflect.Message {
	mi := &file_spark_connect_catalog_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFunctions.ProtoReflect.Descriptor instead.
func (*ListFunctions) Descriptor() ([]byte, []int) {
	return file_spark_connect_catalog_proto_rawDescGZIP(), []int{5}
}

func (x *ListFunctions) GetDbName() string {
	if x != nil && x.DbName != nil {
		return *x.DbName
	}
	return ""
}

func (x *ListFunctions) GetPattern() string {
	if x != nil && x.Pattern != nil {
		return *x.Pattern
	}
	return ""
}

// See `spark.catalog.listColumns`
type ListColumns struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// (Required)
	TableName string `protobuf:"bytes,1,opt,name=table_name,json=tableName,proto3" json:"table_name,omitempty"`
	// (Optional)
	DbName        *string `protobuf:"bytes,2,opt,name=db_name,json=dbName,proto3,oneof" json:"db_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListColumns) Reset() {
	*x = ListColumns{}
	mi := &file_spark_connect_catalog_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListColumns) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListColumns) ProtoMessage() {}

func (x *ListColumns) ProtoReflect() protoreflect.Message {
	mi := &file_spark_connect_catalog_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListColumns.ProtoReflect.Descriptor instead.
func (*ListColumns) Descriptor() ([]byte, []int) {
	return file_spark_connect_catalog_proto_rawDescGZIP(), []int{6}
}

func (x *ListColumns) GetTableName() string {
	if x != nil {
		return x.TableName
	}
	return ""
}

func (x *ListColumns) GetDbName() string {
	if x != nil && x.DbName != nil {
		return *x.DbName
	}
	return ""
}

// See `spark.catalog.getDatabase`
type GetDatabase struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// (Required)
	DbName        string `protobuf:"bytes,1,opt,name=db_name,json=dbName,proto3" json:"db_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDatabase) Reset() {
	*x = GetDatabase{}
	mi := &file_spark_connect_catalog_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDatabase) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDatabase) ProtoMessage() {}

func (x *GetDatabase) ProtoReflect() protoreflect.Message {
	mi := &file_spark_connect_catalog_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDatabase.ProtoReflect.Descriptor instead.
func (*GetDatabase) Descriptor() ([]byte, []int) {
	return file_spark_connect_catalog_proto_rawDescGZIP(), []int{7}
}

func (x *GetDatabase) GetDbName() string {
	if x != nil {
		return x.DbName
	}
	return ""
}

// See `spark.catalog.getTable`
type GetTable struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// (Required)
	TableName string `protobuf:"bytes,1,opt,name=table_name,json=tableName,proto3" json:"table_name,omitempty"`
	// (Optional)
	DbName        *string `protobuf:"bytes,2,opt,name=db_name,json=dbName,proto3,oneof" json:"db_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTable) Reset() {
	*x = GetTable{}
	mi := &file_spark_connect_catalog_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTable) ProtoMessage() {}

func (x *GetTable) ProtoReflect() protoreflect.Message {
	mi := &file_spark_connect_catalog_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTable.ProtoReflect.Descriptor instead.
func (*GetTable) Descriptor() ([]byte, []int) {
	return file_spark_connect_catalog_proto_rawDescGZIP(), []int{8}
}

func (x *GetTable) GetTableName() string {
	if x != nil {
		return x.TableName
	}
	return ""
}

func (x *GetTable) GetDbName() string {
	if x != nil && x.DbName != nil {
		return *x.DbName
	}
	return ""
}

// See `spark.catalog.getFunction`
type GetFunction struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// (Required)
	FunctionName string `protobuf:"bytes,1,opt,name=function_name,json=functionName,proto3" json:"function_name,omitempty"`
	// (Optional)
	DbName        *string `protobuf:"bytes,2,opt,name=db_name,json=dbName,proto3,oneof" json:"db_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFunction) Reset() {
	*x = GetFunction{}
	mi := &file_spark_connect_catalog_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFunction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFunction) ProtoMessage() {}

func (x *GetFunction) ProtoReflect() protoreflect.Message {
	mi := &file_spark_connect_catalog_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFunction.ProtoReflect.Descriptor instead.
func (*GetFunction) Descriptor() ([]byte, []int) {
	return file_spark_connect_catalog_proto_rawDescGZIP(), []int{9}
}

func (x *GetFunction) GetFunctionName() string {
	if x != nil {
		return x.FunctionName
	}
	return ""
}

func (x *GetFunction) GetDbName() string {
	if x != nil && x.DbName != nil {
		return *x.DbName
	}
	return ""
}

// See `spark.catalog.databaseExists`
type DatabaseExists struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// (Required)
	DbName        string `protobuf:"bytes,1,opt,name=db_name,json=dbName,proto3" json:"db_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DatabaseExists) Reset() {
	*x = DatabaseExists{}
	mi := &file_spark_connect_catalog_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DatabaseExists) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DatabaseExists) ProtoMessage() {}

func (x *DatabaseExists) ProtoReflect() protoreflect.Message {
	mi := &file_spark_connect_catalog_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DatabaseExists.ProtoReflect.Descriptor instead.
func (*DatabaseExists) Descriptor() ([]byte, []int) {
	return file_spark_connect_catalog_proto_rawDescGZIP(), []int{10}
}

func (x *DatabaseExists) GetDbName() string {
	if x != nil {
		return x.DbName
	}
	return ""
}

// See `spark.catalog.tableExists`
type TableExists struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// (Required)
	TableName string `protobuf:"bytes,1,opt,name=table_name,json=tableName,proto3" json:"table_name,omitempty"`
	// (Optional)
	DbName        *string `protobuf:"bytes,2,opt,name=db_name,json=dbName,proto3,oneof" json:"db_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TableExists) Reset() {
	*x = TableExists{}
	mi := &file_spark_connect_catalog_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TableExists) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TableExists) ProtoMessage() {}

func (x *TableExists) ProtoReflect() protoreflect.Message {
	mi := &file_spark_connect_catalog_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TableExists.ProtoReflect.Descriptor instead.
func (*TableExists) Descriptor() ([]byte, []int) {
	return file_spark_connect_catalog_proto_rawDescGZIP(), []int{11}
}

func (x *TableExists) GetTableName() string {
	if x != nil {
		return x.TableName
	}
	return ""
}

func (x *TableExists) GetDbName() string {
	if x != nil && x.DbName != nil {
		return *x.DbName
	}
	return ""
}

// See `spark.catalog.functionExists`
type FunctionExists struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// (Required)
	FunctionName string `protobuf:"bytes,1,opt,name=function_name,json=functionName,proto3" json:"function_name,omitempty"`
	// (Optional)
	DbName        *string `protobuf:"bytes,2,opt,name=db_name,json=dbName,proto3,oneof" json:"db_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FunctionExists) Reset() {
	*x = FunctionExists{}
	mi := &file_spark_connect_catalog_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FunctionExists) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FunctionExists) ProtoMessage() {}

func (x *FunctionExists) ProtoReflect() protoreflect.Message {
	mi := &file_spark_connect_catalog_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FunctionExists.ProtoReflect.Descriptor instead.
func (*FunctionExists) Descriptor() ([]byte, []int) {
	return file_spark_connect_catalog_proto_rawDescGZIP(), []int{12}
}

func (x *FunctionExists) GetFunctionName() string {
	if x != nil {
		return x.FunctionName
	}
	return ""
}

func (x *FunctionExists) GetDbName() string {
	if x != nil && x.DbName != nil {
		return *x.DbName
	}
	return ""
}

// See `spark.catalog.createExternalTable`
type CreateExternalTable struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// (Required)
	TableName string `protobuf:"bytes,1,opt,name=table_name,json=tableName,proto3" json:"table_name,omitempty"`
	// (Optional)
	Path *string `protobuf:"bytes,2,opt,name=path,proto3,oneof" json:"path,omitempty"`
	// (Optional)
	Source *string `protobuf:"bytes,3,opt,name=source,proto3,oneof" json:"source,omitempty"`
	// (Optional)
	Schema *DataType `protobuf:"bytes,4,opt,name=schema,proto3,oneof" json:"schema,omitempty"`
	// Options could be empty for valid data source format.
	// The map key is case insensitive.
	Options       map[string]string `protobuf:"bytes,5,rep,name=options,proto3" json:"options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateExternalTable) Reset() {
	*x = CreateExternalTable{}
	mi := &file_spark_connect_catalog_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateExternalTable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateExternalTable) ProtoMessage() {}

func (x *CreateExternalTable) ProtoReflect() protoreflect.Message {
	mi := &file_spark_connect_catalog_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateExternalTable.ProtoReflect.Descriptor instead.
func (*CreateExternalTable) Descriptor() ([]byte, []int) {
	return file_spark_connect_catalog_proto_rawDescGZIP(), []int{13}
}

func (x *CreateExternalTable) GetTableName() string {
	if x != nil {
		return x.TableName
	}
	return ""
}

func (x *CreateExternalTable) GetPath() string {
	if x != nil && x.Path != nil {
		return *x.Path
	}
	return ""
}

func (x *CreateExternalTable) GetSource() string {
	if x != nil && x.Source != nil {
		return *x.Source
	}
	return ""
}

func (x *CreateExternalTable) GetSchema() *DataType {
	if x != nil {
		return x.Schema
	}
	return nil
}

func (x *CreateExternalTable) GetOptions() map[string]string {
	if x != nil {
		return x.Options
	}
	return nil
}

// See `spark.catalog.createTable`
type CreateTable struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// (Required)
	TableName string `protobuf:"bytes,1,opt,name=table_name,json=tableName,proto3" json:"table_name,omitempty"`
	// (Optional)
	Path *string `protobuf:"bytes,2,opt,name=path,proto3,oneof" json:"path,omitempty"`
	// (Optional)
	Source *string `protobuf:"bytes,3,opt,name=source,proto3,oneof" json:"source,omitempty"`
	// (Optional)
	Description *string `protobuf:"bytes,4,opt,name=description,proto3,oneof" json:"description,omitempty"`
	// (Optional)
	Schema *DataType `protobuf:"bytes,5,opt,name=schema,proto3,oneof" json:"schema,omitempty"`
	// Options could be empty for valid data source format.
	// The map key is case insensitive.
	Options       map[string]string `protobuf:"bytes,6,rep,name=options,proto3" json:"options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTable) Reset() {
	*x = CreateTable{}
	mi := &file_spark_connect_catalog_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTable) ProtoMessage() {}

func (x *CreateTable) ProtoReflect() protoreflect.Message {
	mi := &file_spark_connect_catalog_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTable.ProtoReflect.Descriptor instead.
func (*CreateTable) Descriptor() ([]byte, []int) {
	return file_spark_connect_catalog_proto_rawDescGZIP(), []int{14}
}

func (x *CreateTable) GetTableName() string {
	if x != nil {
		return x.TableName
	}
	return ""
}

func (x *CreateTable) GetPath() string {
	if x != nil && x.Path != nil {
		return *x.Path
	}
	return ""
}

func (x *CreateTable) GetSource() string {
	if x != nil && x.Source != nil {
		return *x.Source
	}
	return ""
}

func (x *CreateTable) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *CreateTable) GetSchema() *DataType {
	if x != nil {
		return x.Schema
	}
	return nil
}

func (x *CreateTable) GetOptions() map[string]string {
	if x != nil {
		return x.Options
	}
	return nil
}

// See `spark.catalog.dropTempView`
type DropTempView struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// (Required)
	ViewName      string `protobuf:"bytes,1,opt,name=view_name,json=viewName,proto3" json:"view_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DropTempView) Reset() {
	*x = DropTempView{}
	mi := &file_spark_connect_catalog_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DropTempView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DropTempView) ProtoMessage() {}

func (x *DropTempView) ProtoReflect() protoreflect.Message {
	mi := &file_spark_connect_catalog_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DropTempView.ProtoReflect.Descriptor instead.
func (*DropTempView) Descriptor() ([]byte, []int) {
	return file_spark_connect_catalog_proto_rawDescGZIP(), []int{15}
}

func (x *DropTempView) GetViewName() string {
	if x != nil {
		return x.ViewName
	}
	return ""
}

// See `spark.catalog.dropGlobalTempView`
type DropGlobalTempView struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// (Required)
	ViewName      string `protobuf:"bytes,1,opt,name=view_name,json=viewName,proto3" json:"view_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DropGlobalTempView) Reset() {
	*x = DropGlobalTempView{}
	mi := &file_spark_connect_catalog_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DropGlobalTempView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DropGlobalTempView) ProtoMessage() {}

func (x *DropGlobalTempView) ProtoReflect() protoreflect.Message {
	mi := &file_spark_connect_catalog_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DropGlobalTempView.ProtoReflect.Descriptor instead.
func (*DropGlobalTempView) Descriptor() ([]byte, []int) {
	return file_spark_connect_catalog_proto_rawDescGZIP(), []int{16}
}

func (x *DropGlobalTempView) GetViewName() string {
	if x != nil {
		return x.ViewName
	}
	return ""
}

// See `spark.catalog.recoverPartitions`
type RecoverPartitions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// (Required)
	TableName     string `protobuf:"bytes,1,opt,name=table_name,json=tableName,proto3" json:"table_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecoverPartitions) Reset() {
	*x = RecoverPartitions{}
	mi := &file_spark_connect_catalog_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecoverPartitions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecoverPartitions) ProtoMessage() {}

func (x *RecoverPartitions) ProtoReflect() protoreflect.Message {
	mi := &file_spark_connect_catalog_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecoverPartitions.ProtoReflect.Descriptor instead.
func (*RecoverPartitions) Descriptor() ([]byte, []int) {
	return file_spark_connect_catalog_proto_rawDescGZIP(), []int{17}
}

func (x *RecoverPartitions) GetTableName() string {
	if x != nil {
		return x.TableName
	}
	return ""
}

// See `spark.catalog.isCached`
type IsCached struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// (Required)
	TableName     string `protobuf:"bytes,1,opt,name=table_name,json=tableName,proto3" json:"table_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsCached) Reset() {
	*x = IsCached{}
	mi := &file_spark_connect_catalog_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsCached) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsCached) ProtoMessage() {}

func (x *IsCached) ProtoReflect() protoreflect.Message {
	mi := &file_spark_connect_catalog_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsCached.ProtoReflect.Descriptor instead.
func (*IsCached) Descriptor() ([]byte, []int) {
	return file_spark_connect_catalog_proto_rawDescGZIP(), []int{18}
}

func (x *IsCached) GetTableName() string {
	if x != nil {
		return x.TableName
	}
	return ""
}

// See `spark.catalog.cacheTable`
type CacheTable struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// (Required)
	TableName string `protobuf:"bytes,1,opt,name=table_name,json=tableName,proto3" json:"table_name,omitempty"`
	// (Optional)
	StorageLevel  *StorageLevel `protobuf:"bytes,2,opt,name=storage_level,json=storageLevel,proto3,oneof" json:"storage_level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CacheTable) Reset() {
	*x = CacheTable{}
	mi := &file_spark_connect_catalog_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CacheTable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheTable) ProtoMessage() {}

func (x *CacheTable) ProtoReflect() protoreflect.Message {
	mi := &file_spark_connect_catalog_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheTable.ProtoReflect.Descriptor instead.
func (*CacheTable) Descriptor() ([]byte, []int) {
	return file_spark_connect_catalog_proto_rawDescGZIP(), []int{19}
}

func (x *CacheTable) GetTableName() string {
	if x != nil {
		return x.TableName
	}
	return ""
}

func (x *CacheTable) GetStorageLevel() *StorageLevel {
	if x != nil {
		return x.StorageLevel
	}
	return nil
}

// See `spark.catalog.uncacheTable`
type UncacheTable struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// (Required)
	TableName     string `protobuf:"bytes,1,opt,name=table_name,json=tableName,proto3" json:"table_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UncacheTable) Reset() {
	*x = UncacheTable{}
	mi := &file_spark_connect_catalog_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UncacheTable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UncacheTable) ProtoMessage() {}

func (x *UncacheTable) ProtoReflect() protoreflect.Message {
	mi := &file_spark_connect_catalog_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UncacheTable.ProtoReflect.Descriptor instead.
func (*UncacheTable) Descriptor() ([]byte, []int) {
	return file_spark_connect_catalog_proto_rawDescGZIP(), []int{20}
}

func (x *UncacheTable) GetTableName() string {
	if x != nil {
		return x.TableName
	}
	return ""
}

// See `spark.catalog.clearCache`
type ClearCache struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearCache) Reset() {
	*x = ClearCache{}
	mi := &file_spark_connect_catalog_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearCache) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearCache) ProtoMessage() {}

func (x *ClearCache) ProtoReflect() protoreflect.Message {
	mi := &file_spark_connect_catalog_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearCache.ProtoReflect.Descriptor instead.
func (*ClearCache) Descriptor() ([]byte, []int) {
	return file_spark_connect_catalog_proto_rawDescGZIP(), []int{21}
}

// See `spark.catalog.refreshTable`
type RefreshTable struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// (Required)
	TableName     string `protobuf:"bytes,1,opt,name=table_name,json=tableName,proto3" json:"table_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTable) Reset() {
	*x = RefreshTable{}
	mi := &file_spark_connect_catalog_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTable) ProtoMessage() {}

func (x *RefreshTable) ProtoReflect() protoreflect.Message {
	mi := &file_spark_connect_catalog_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTable.ProtoReflect.Descriptor instead.
func (*RefreshTable) Descriptor() ([]byte, []int) {
	return file_spark_connect_catalog_proto_rawDescGZIP(), []int{22}
}

func (x *RefreshTable) GetTableName() string {
	if x != nil {
		return x.TableName
	}
	return ""
}

// See `spark.catalog.refreshByPath`
type RefreshByPath struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// (Required)
	Path          string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshByPath) Reset() {
	*x = RefreshByPath{}
	mi := &file_spark_connect_catalog_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshByPath) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshByPath) ProtoMessage() {}

func (x *RefreshByPath) ProtoReflect() protoreflect.Message {
	mi := &file_spark_connect_catalog_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshByPath.ProtoReflect.Descriptor instead.
func (*RefreshByPath) Descriptor() ([]byte, []int) {
	return file_spark_connect_catalog_proto_rawDescGZIP(), []int{23}
}

func (x *RefreshByPath) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

// See `spark.catalog.currentCatalog`
type CurrentCatalog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CurrentCatalog) Reset() {
	*x = CurrentCatalog{}
	mi := &file_spark_connect_catalog_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CurrentCatalog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CurrentCatalog) ProtoMessage() {}

func (x *CurrentCatalog) ProtoReflect() protoreflect.Message {
	mi := &file_spark_connect_catalog_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CurrentCatalog.ProtoReflect.Descriptor instead.
func (*CurrentCatalog) Descriptor() ([]byte, []int) {
	return file_spark_connect_catalog_proto_rawDescGZIP(), []int{24}
}

// See `spark.catalog.setCurrentCatalog`
type SetCurrentCatalog struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// (Required)
	CatalogName   string `protobuf:"bytes,1,opt,name=catalog_name,json=catalogName,proto3" json:"catalog_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetCurrentCatalog) Reset() {
	*x = SetCurrentCatalog{}
	mi := &file_spark_connect_catalog_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetCurrentCatalog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetCurrentCatalog) ProtoMessage() {}

func (x *SetCurrentCatalog) ProtoReflect() protoreflect.Message {
	mi := &file_spark_connect_catalog_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetCurrentCatalog.ProtoReflect.Descriptor instead.
func (*SetCurrentCatalog) Descriptor() ([]byte, []int) {
	return file_spark_connect_catalog_proto_rawDescGZIP(), []int{25}
}

func (x *SetCurrentCatalog) GetCatalogName() string {
	if x != nil {
		return x.CatalogName
	}
	return ""
}

// See `spark.catalog.listCatalogs`
type ListCatalogs struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// (Optional) The pattern that the catalog name needs to match
	Pattern       *string `protobuf:"bytes,1,opt,name=pattern,proto3,oneof" json:"pattern,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCatalogs) Reset() {
	*x = ListCatalogs{}
	mi := &file_spark_connect_catalog_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCatalogs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCatalogs) ProtoMessage() {}

func (x *ListCatalogs) ProtoReflect() protoreflect.Message {
	mi := &file_spark_connect_catalog_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCatalogs.ProtoReflect.Descriptor instead.
func (*ListCatalogs) Descriptor() ([]byte, []int) {
	return file_spark_connect_catalog_proto_rawDescGZIP(), []int{26}
}

func (x *ListCatalogs) GetPattern() string {
	if x != nil && x.Pattern != nil {
		return *x.Pattern
	}
	return ""
}

// See `spark.catalog.dropTable`
type DropTable struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// (Required)
	TableName     string `protobuf:"bytes,1,opt,name=table_name,json=tableName,proto3" json:"table_name,omitempty"`
	IfExists      bool   `protobuf:"varint,2,opt,name=if_exists,json=ifExists,proto3" json:"if_exists,omitempty"`
	Purge         bool   `protobuf:"varint,3,opt,name=purge,proto3" json:"purge,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DropTable) Reset() {
	*x = DropTable{}
	mi := &file_spark_connect_catalog_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DropTable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DropTable) ProtoMessage() {}

func (x *DropTable) ProtoReflect() protoreflect.Message {
	mi := &file_spark_connect_catalog_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DropTable.ProtoReflect.Descriptor instead.
func (*DropTable) Descriptor() ([]byte, []int) {
	return file_spark_connect_catalog_proto_rawDescGZIP(), []int{27}
}

func (x *DropTable) GetTableName() string {
	if x != nil {
		return x.TableName
	}
	return ""
}

func (x *DropTable) GetIfExists() bool {
	if x != nil {
		return x.IfExists
	}
	return false
}

func (x *DropTable) GetPurge() bool {
	if x != nil {
		return x.Purge
	}
	return false
}

// See `spark.catalog.dropView`
type DropView struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// (Required)
	ViewName      string `protobuf:"bytes,1,opt,name=view_name,json=viewName,proto3" json:"view_name,omitempty"`
	IfExists      bool   `protobuf:"varint,2,opt,name=if_exists,json=ifExists,proto3" json:"if_exists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DropView) Reset() {
	*x = DropView{}
	mi := &file_spark_connect_catalog_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DropView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DropView) ProtoMessage() {}

func (x *DropView) ProtoReflect() protoreflect.Message {
	mi := &file_spark_connect_catalog_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DropView.ProtoReflect.Descriptor instead.
func (*DropView) Descriptor() ([]byte, []int) {
	return file_spark_connect_catalog_proto_rawDescGZIP(), []int{28}
}

func (x *DropView) GetViewName() string {
	if x != nil {
		return x.ViewName
	}
	return ""
}

func (x *DropView) GetIfExists() bool {
	if x != nil {
		return x.IfExists
	}
	return false
}

// See `spark.catalog.createDatabase`
type CreateDatabase struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// (Required)
	DbName        string            `protobuf:"bytes,1,opt,name=db_name,json=dbName,proto3" json:"db_name,omitempty"`
	IfNotExists   bool              `protobuf:"varint,2,opt,name=if_not_exists,json=ifNotExists,proto3" json:"if_not_exists,omitempty"`
	Properties    map[string]string `protobuf:"bytes,3,rep,name=properties,proto3" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDatabase) Reset() {
	*x = CreateDatabase{}
	mi := &file_spark_connect_catalog_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDatabase) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDatabase) ProtoMessage() {}

func (x *CreateDatabase) ProtoReflect() protoreflect.Message {
	mi := &file_spark_connect_catalog_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDatabase.ProtoReflect.Descriptor instead.
func (*CreateDatabase) Descriptor() ([]byte, []int) {
	return file_spark_connect_catalog_proto_rawDescGZIP(), []int{29}
}

func (x *CreateDatabase) GetDbName() string {
	if x != nil {
		return x.DbName
	}
	return ""
}

func (x *CreateDatabase) GetIfNotExists() bool {
	if x != nil {
		return x.IfNotExists
	}
	return false
}

func (x *CreateDatabase) GetProperties() map[string]string {
	if x != nil {
		return x.Properties
	}
	return nil
}

// See `spark.catalog.dropDatabase`
type DropDatabase struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// (Required)
	DbName        string `protobuf:"bytes,1,opt,name=db_name,json=dbName,proto3" json:"db_name,omitempty"`
	IfExists      bool   `protobuf:"varint,2,opt,name=if_exists,json=ifExists,proto3" json:"if_exists,omitempty"`
	Cascade       bool   `protobuf:"varint,3,opt,name=cascade,proto3" json:"cascade,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DropDatabase) Reset() {
	*x = DropDatabase{}
	mi := &file_spark_connect_catalog_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DropDatabase) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DropDatabase) ProtoMessage() {}

func (x *DropDatabase) ProtoReflect() protoreflect.Message {
	mi := &file_spark_connect_catalog_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DropDatabase.ProtoReflect.Descriptor instead.
func (*DropDatabase) Descriptor() ([]byte, []int) {
	return file_spark_connect_catalog_proto_rawDescGZIP(), []int{30}
}

func (x *DropDatabase) GetDbName() string {
	if x != nil {
		return x.DbName
	}
	return ""
}

func (x *DropDatabase) GetIfExists() bool {
	if x != nil {
		return x.IfExists
	}
	return false
}

func (x *DropDatabase) GetCascade() bool {
	if x != nil {
		return x.Cascade
	}
	return false
}

// See `spark.catalog.listPartitions`
type ListPartitions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// (Required)
	TableName     string `protobuf:"bytes,1,opt,name=table_name,json=tableName,proto3" json:"table_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPartitions) Reset() {
	*x = ListPartitions{}
	mi := &file_spark_connect_catalog_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPartitions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPartitions) ProtoMessage() {}

func (x *ListPartitions) ProtoReflect() protoreflect.Message {
	mi := &file_spark_connect_catalog_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPartitions.ProtoReflect.Descriptor instead.
func (*ListPartitions) Descriptor() ([]byte, []int) {
	return file_spark_connect_catalog_proto_rawDescGZIP(), []int{31}
}

func (x *ListPartitions) GetTableName() string {
	if x != nil {
		return x.TableName
	}
	return ""
}

// See `spark.catalog.listViews`
type ListViews struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// (Optional)
	DbName *string `protobuf:"bytes,1,opt,name=db_name,json=dbName,proto3,oneof" json:"db_name,omitempty"`
	// (Optional) The pattern that the view name needs to match
	Pattern       *string `protobuf:"bytes,2,opt,name=pattern,proto3,oneof" json:"pattern,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListViews) Reset() {
	*x = ListViews{}
	mi := &file_spark_connect_catalog_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListViews) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListViews) ProtoMessage() {}

func (x *ListViews) ProtoReflect() protoreflect.Message {
	mi := &file_spark_connect_catalog_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListViews.ProtoReflect.Descriptor instead.
func (*ListViews) Descriptor() ([]byte, []int) {
	return file_spark_connect_catalog_proto_rawDescGZIP(), []int{32}
}

func (x *ListViews) GetDbName() string {
	if x != nil && x.DbName != nil {
		return *x.DbName
	}
	return ""
}

func (x *ListViews) GetPattern() string {
	if x != nil && x.Pattern != nil {
		return *x.Pattern
	}
	return ""
}

// See `spark.catalog.getTableProperties`
type GetTableProperties struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// (Required)
	TableName     string `protobuf:"bytes,1,opt,name=table_name,json=tableName,proto3" json:"table_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTableProperties) Reset() {
	*x = GetTableProperties{}
	mi := &file_spark_connect_catalog_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTableProperties) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTableProperties) ProtoMessage() {}

func (x *GetTableProperties) ProtoReflect() protoreflect.Message {
	mi := &file_spark_connect_catalog_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTableProperties.ProtoReflect.Descriptor instead.
func (*GetTableProperties) Descriptor() ([]byte, []int) {
	return file_spark_connect_catalog_proto_rawDescGZIP(), []int{33}
}

func (x *GetTableProperties) GetTableName() string {
	if x != nil {
		return x.TableName
	}
	return ""
}

// See `spark.catalog.getCreateTableString`
type GetCreateTableString struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// (Required)
	TableName     string `protobuf:"bytes,1,opt,name=table_name,json=tableName,proto3" json:"table_name,omitempty"`
	AsSerde       bool   `protobuf:"varint,2,opt,name=as_serde,json=asSerde,proto3" json:"as_serde,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCreateTableString) Reset() {
	*x = GetCreateTableString{}
	mi := &file_spark_connect_catalog_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCreateTableString) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCreateTableString) ProtoMessage() {}

func (x *GetCreateTableString) ProtoReflect() protoreflect.Message {
	mi := &file_spark_connect_catalog_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCreateTableString.ProtoReflect.Descriptor instead.
func (*GetCreateTableString) Descriptor() ([]byte, []int) {
	return file_spark_connect_catalog_proto_rawDescGZIP(), []int{34}
}

func (x *GetCreateTableString) GetTableName() string {
	if x != nil {
		return x.TableName
	}
	return ""
}

func (x *GetCreateTableString) GetAsSerde() bool {
	if x != nil {
		return x.AsSerde
	}
	return false
}

// See `spark.catalog.truncateTable`
type TruncateTable struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// (Required)
	TableName     string `protobuf:"bytes,1,opt,name=table_name,json=tableName,proto3" json:"table_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TruncateTable) Reset() {
	*x = TruncateTable{}
	mi := &file_spark_connect_catalog_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TruncateTable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TruncateTable) ProtoMessage() {}

func (x *TruncateTable) ProtoReflect() protoreflect.Message {
	mi := &file_spark_connect_catalog_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TruncateTable.ProtoReflect.Descriptor instead.
func (*TruncateTable) Descriptor() ([]byte, []int) {
	return file_spark_connect_catalog_proto_rawDescGZIP(), []int{35}
}

func (x *TruncateTable) GetTableName() string {
	if x != nil {
		return x.TableName
	}
	return ""
}

// See `spark.catalog.analyzeTable`
type AnalyzeTable struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// (Required)
	TableName     string `protobuf:"bytes,1,opt,name=table_name,json=tableName,proto3" json:"table_name,omitempty"`
	NoScan        bool   `protobuf:"varint,2,opt,name=no_scan,json=noScan,proto3" json:"no_scan,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzeTable) Reset() {
	*x = AnalyzeTable{}
	mi := &file_spark_connect_catalog_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeTable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeTable) ProtoMessage() {}

func (x *AnalyzeTable) ProtoReflect() protoreflect.Message {
	mi := &file_spark_connect_catalog_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeTable.ProtoReflect.Descriptor instead.
func (*AnalyzeTable) Descriptor() ([]byte, []int) {
	return file_spark_connect_catalog_proto_rawDescGZIP(), []int{36}
}

func (x *AnalyzeTable) GetTableName() string {
	if x != nil {
		return x.TableName
	}
	return ""
}

func (x *AnalyzeTable) GetNoScan() bool {
	if x != nil {
		return x.NoScan
	}
	return false
}

var File_spark_connect_catalog_proto protoreflect.FileDescriptor

const file_spark_connect_catalog_proto_rawDesc = "" +
	"\n" +
	"\x1bspark/connect/catalog.proto\x12\rspark.connect\x1a\x1aspark/connect/common.proto\x1a\x19spark/connect/types.proto\"\x8c\x14\n" +
	"\aCatalog\x12K\n" +
	"\x10current_database\x18\x01 \x01(\v2\x1e.spark.connect.CurrentDatabaseH\x00R\x0fcurrentDatabase\x12U\n" +
	"\x14set_current_database\x18\x02 \x01(\v2!.spark.connect.SetCurrentDatabaseH\x00R\x12setCurrentDatabase\x12E\n" +
	"\x0elist_databases\x18\x03 \x01(\v2\x1c.spark.connect.ListDatabasesH\x00R\rlistDatabases\x12<\n" +
	"\vlist_tables\x18\x04 \x01(\v2\x19.spark.connect.ListTablesH\x00R\n" +
	"listTables\x12E\n" +
	"\x0elist_functions\x18\x05 \x01(\v2\x1c.spark.connect.ListFunctionsH\x00R\rlistFunctions\x12?\n" +
	"\flist_columns\x18\x06 \x01(\v2\x1a.spark.connect.ListColumnsH\x00R\vlistColumns\x12?\n" +
	"\fget_database\x18\a \x01(\v2\x1a.spark.connect.GetDatabaseH\x00R\vgetDatabase\x126\n" +
	"\tget_table\x18\b \x01(\v2\x17.spark.connect.GetTableH\x00R\bgetTable\x12?\n" +
	"\fget_function\x18\t \x01(\v2\x1a.spark.connect.GetFunctionH\x00R\vgetFunction\x12H\n" +
	"\x0fdatabase_exists\x18\n" +
	" \x01(\v2\x1d.spark.connect.DatabaseExistsH\x00R\x0edatabaseExists\x12?\n" +
	"\ftable_exists\x18\v \x01(\v2\x1a.spark.connect.TableExistsH\x00R\vtableExists\x12H\n" +
	"\x0ffunction_exists\x18\f \x01(\v2\x1d.spark.connect.FunctionExistsH\x00R\x0efunctionExists\x12X\n" +
	"\x15create_external_table\x18\r \x01(\v2\".spark.connect.CreateExternalTableH\x00R\x13createExternalTable\x12?\n" +
	"\fcreate_table\x18\x0e \x01(\v2\x1a.spark.connect.CreateTableH\x00R\vcreateTable\x12C\n" +
	"\x0edrop_temp_view\x18\x0f \x01(\v2\x1b.spark.connect.DropTempViewH\x00R\fdropTempView\x12V\n" +
	"\x15drop_global_temp_view\x18\x10 \x01(\v2!.spark.connect.DropGlobalTempViewH\x00R\x12dropGlobalTempView\x12Q\n" +
	"\x12recover_partitions\x18\x11 \x01(\v2 .spark.connect.RecoverPartitionsH\x00R\x11recoverPartitions\x126\n" +
	"\tis_cached\x18\x12 \x01(\v2\x17.spark.connect.IsCachedH\x00R\bisCached\x12<\n" +
	"\vcache_table\x18\x13 \x01(\v2\x19.spark.connect.CacheTableH\x00R\n" +
	"cacheTable\x12B\n" +
	"\runcache_table\x18\x14 \x01(\v2\x1b.spark.connect.UncacheTableH\x00R\funcacheTable\x12<\n" +
	"\vclear_cache\x18\x15 \x01(\v2\x19.spark.connect.ClearCacheH\x00R\n" +
	"clearCache\x12B\n" +
	"\rrefresh_table\x18\x16 \x01(\v2\x1b.spark.connect.RefreshTableH\x00R\frefreshTable\x12F\n" +
	"\x0frefresh_by_path\x18\x17 \x01(\v2\x1c.spark.connect.RefreshByPathH\x00R\rrefreshByPath\x12H\n" +
	"\x0fcurrent_catalog\x18\x18 \x01(\v2\x1d.spark.connect.CurrentCatalogH\x00R\x0ecurrentCatalog\x12R\n" +
	"\x13set_current_catalog\x18\x19 \x01(\v2 .spark.connect.SetCurrentCatalogH\x00R\x11setCurrentCatalog\x12B\n" +
	"\rlist_catalogs\x18\x1a \x01(\v2\x1b.spark.connect.ListCatalogsH\x00R\flistCatalogs\x129\n" +
	"\n" +
	"drop_table\x18\x1b \x01(\v2\x18.spark.connect.DropTableH\x00R\tdropTable\x126\n" +
	"\tdrop_view\x18\x1c \x01(\v2\x17.spark.connect.DropViewH\x00R\bdropView\x12H\n" +
	"\x0fcreate_database\x18\x1d \x01(\v2\x1d.spark.connect.CreateDatabaseH\x00R\x0ecreateDatabase\x12B\n" +
	"\rdrop_database\x18\x1e \x01(\v2\x1b.spark.connect.DropDatabaseH\x00R\fdropDatabase\x12H\n" +
	"\x0flist_partitions\x18\x1f \x01(\v2\x1d.spark.connect.ListPartitionsH\x00R\x0elistPartitions\x129\n" +
	"\n" +
	"list_views\x18  \x01(\v2\x18.spark.connect.ListViewsH\x00R\tlistViews\x12U\n" +
	"\x14get_table_properties\x18! \x01(\v2!.spark.connect.GetTablePropertiesH\x00R\x12getTableProperties\x12\\\n" +
	"\x17get_create_table_string\x18\" \x01(\v2#.spark.connect.GetCreateTableStringH\x00R\x14getCreateTableString\x12E\n" +
	"\x0etruncate_table\x18# \x01(\v2\x1c.spark.connect.TruncateTableH\x00R\rtruncateTable\x12B\n" +
	"\ranalyze_table\x18$ \x01(\v2\x1b.spark.connect.AnalyzeTableH\x00R\fanalyzeTableB\n" +
	"\n" +
	"\bcat_type\"\x11\n" +
	"\x0fCurrentDatabase\"-\n" +
	"\x12SetCurrentDatabase\x12\x17\n" +
	"\adb_name\x18\x01 \x01(\tR\x06dbName\":\n" +
	"\rListDatabases\x12\x1d\n" +
	"\apattern\x18\x01 \x01(\tH\x00R\apattern\x88\x01\x01B\n" +
	"\n" +
	"\b_pattern\"a\n" +
	"\n" +
	"ListTables\x12\x1c\n" +
	"\adb_name\x18\x01 \x01(\tH\x00R\x06dbName\x88\x01\x01\x12\x1d\n" +
	"\apattern\x18\x02 \x01(\tH\x01R\apattern\x88\x01\x01B\n" +
	"\n" +
	"\b_db_nameB\n" +
	"\n" +
	"\b_pattern\"d\n" +
	"\rListFunctions\x12\x1c\n" +
	"\adb_name\x18\x01 \x01(\tH\x00R\x06dbName\x88\x01\x01\x12\x1d\n" +
	"\apattern\x18\x02 \x01(\tH\x01R\apattern\x88\x01\x01B\n" +
	"\n" +
	"\b_db_nameB\n" +
	"\n" +
	"\b_pattern\"V\n" +
	"\vListColumns\x12\x1d\n" +
	"\n" +
	"table_name\x18\x01 \x01(\tR\ttableName\x12\x1c\n" +
	"\adb_name\x18\x02 \x01(\tH\x00R\x06dbName\x88\x01\x01B\n" +
	"\n" +
	"\b_db_name\"&\n" +
	"\vGetDatabase\x12\x17\n" +
	"\adb_name\x18\x01 \x01(\tR\x06dbName\"S\n" +
	"\bGetTable\x12\x1d\n" +
	"\n" +
	"table_name\x18\x01 \x01(\tR\ttableName\x12\x1c\n" +
	"\adb_name\x18\x02 \x01(\tH\x00R\x06dbName\x88\x01\x01B\n" +
	"\n" +
	"\b_db_name\"\\\n" +
	"\vGetFunction\x12#\n" +
	"\rfunction_name\x18\x01 \x01(\tR\ffunctionName\x12\x1c\n" +
	"\adb_name\x18\x02 \x01(\tH\x00R\x06dbName\x88\x01\x01B\n" +
	"\n" +
	"\b_db_name\")\n" +
	"\x0eDatabaseExists\x12\x17\n" +
	"\adb_name\x18\x01 \x01(\tR\x06dbName\"V\n" +
	"\vTableExists\x12\x1d\n" +
	"\n" +
	"table_name\x18\x01 \x01(\tR\ttableName\x12\x1c\n" +
	"\adb_name\x18\x02 \x01(\tH\x00R\x06dbName\x88\x01\x01B\n" +
	"\n" +
	"\b_db_name\"_\n" +
	"\x0eFunctionExists\x12#\n" +
	"\rfunction_name\x18\x01 \x01(\tR\ffunctionName\x12\x1c\n" +
	"\adb_name\x18\x02 \x01(\tH\x00R\x06dbName\x88\x01\x01B\n" +
	"\n" +
	"\b_db_name\"\xc6\x02\n" +
	"\x13CreateExternalTable\x12\x1d\n" +
	"\n" +
	"table_name\x18\x01 \x01(\tR\ttableName\x12\x17\n" +
	"\x04path\x18\x02 \x01(\tH\x00R\x04path\x88\x01\x01\x12\x1b\n" +
	"\x06source\x18\x03 \x01(\tH\x01R\x06source\x88\x01\x01\x124\n" +
	"\x06schema\x18\x04 \x01(\v2\x17.spark.connect.DataTypeH\x02R\x06schema\x88\x01\x01\x12I\n" +
	"\aoptions\x18\x05 \x03(\v2/.spark.connect.CreateExternalTable.OptionsEntryR\aoptions\x1a:\n" +
	"\fOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\a\n" +
	"\x05_pathB\t\n" +
	"\a_sourceB\t\n" +
	"\a_schema\"\xed\x02\n" +
	"\vCreateTable\x12\x1d\n" +
	"\n" +
	"table_name\x18\x01 \x01(\tR\ttableName\x12\x17\n" +
	"\x04path\x18\x02 \x01(\tH\x00R\x04path\x88\x01\x01\x12\x1b\n" +
	"\x06source\x18\x03 \x01(\tH\x01R\x06source\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x04 \x01(\tH\x02R\vdescription\x88\x01\x01\x124\n" +
	"\x06schema\x18\x05 \x01(\v2\x17.spark.connect.DataTypeH\x03R\x06schema\x88\x01\x01\x12A\n" +
	"\aoptions\x18\x06 \x03(\v2'.spark.connect.CreateTable.OptionsEntryR\aoptions\x1a:\n" +
	"\fOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\a\n" +
	"\x05_pathB\t\n" +
	"\a_sourceB\x0e\n" +
	"\f_descriptionB\t\n" +
	"\a_schema\"+\n" +
	"\fDropTempView\x12\x1b\n" +
	"\tview_name\x18\x01 \x01(\tR\bviewName\"1\n" +
	"\x12DropGlobalTempView\x12\x1b\n" +
	"\tview_name\x18\x01 \x01(\tR\bviewName\"2\n" +
	"\x11RecoverPartitions\x12\x1d\n" +
	"\n" +
	"table_name\x18\x01 \x01(\tR\ttableName\")\n" +
	"\bIsCached\x12\x1d\n" +
	"\n" +
	"table_name\x18\x01 \x01(\tR\ttableName\"\x84\x01\n" +
	"\n" +
	"CacheTable\x12\x1d\n" +
	"\n" +
	"table_name\x18\x01 \x01(\tR\ttableName\x12E\n" +
	"\rstorage_level\x18\x02 \x01(\v2\x1b.spark.connect.StorageLevelH\x00R\fstorageLevel\x88\x01\x01B\x10\n" +
	"\x0e_storage_level\"-\n" +
	"\fUncacheTable\x12\x1d\n" +
	"\n" +
	"table_name\x18\x01 \x01(\tR\ttableName\"\f\n" +
	"\n" +
	"ClearCache\"-\n" +
	"\fRefreshTable\x12\x1d\n" +
	"\n" +
	"table_name\x18\x01 \x01(\tR\ttableName\"#\n" +
	"\rRefreshByPath\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"\x10\n" +
	"\x0eCurrentCatalog\"6\n" +
	"\x11SetCurrentCatalog\x12!\n" +
	"\fcatalog_name\x18\x01 \x01(\tR\vcatalogName\"9\n" +
	"\fListCatalogs\x12\x1d\n" +
	"\apattern\x18\x01 \x01(\tH\x00R\apattern\x88\x01\x01B\n" +
	"\n" +
	"\b_pattern\"]\n" +
	"\tDropTable\x12\x1d\n" +
	"\n" +
	"table_name\x18\x01 \x01(\tR\ttableName\x12\x1b\n" +
	"\tif_exists\x18\x02 \x01(\bR\bifExists\x12\x14\n" +
	"\x05purge\x18\x03 \x01(\bR\x05purge\"D\n" +
	"\bDropView\x12\x1b\n" +
	"\tview_name\x18\x01 \x01(\tR\bviewName\x12\x1b\n" +
	"\tif_exists\x18\x02 \x01(\bR\bifExists\"\xdb\x01\n" +
	"\x0eCreateDatabase\x12\x17\n" +
	"\adb_name\x18\x01 \x01(\tR\x06dbName\x12\"\n" +
	"\rif_not_exists\x18\x02 \x01(\bR\vifNotExists\x12M\n" +
	"\n" +
	"properties\x18\x03 \x03(\v2-.spark.connect.CreateDatabase.PropertiesEntryR\n" +
	"properties\x1a=\n" +
	"\x0fPropertiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"^\n" +
	"\fDropDatabase\x12\x17\n" +
	"\adb_name\x18\x01 \x01(\tR\x06dbName\x12\x1b\n" +
	"\tif_exists\x18\x02 \x01(\bR\bifExists\x12\x18\n" +
	"\acascade\x18\x03 \x01(\bR\acascade\"/\n" +
	"\x0eListPartitions\x12\x1d\n" +
	"\n" +
	"table_name\x18\x01 \x01(\tR\ttableName\"`\n" +
	"\tListViews\x12\x1c\n" +
	"\adb_name\x18\x01 \x01(\tH\x00R\x06dbName\x88\x01\x01\x12\x1d\n" +
	"\apattern\x18\x02 \x01(\tH\x01R\apattern\x88\x01\x01B\n" +
	"\n" +
	"\b_db_nameB\n" +
	"\n" +
	"\b_pattern\"3\n" +
	"\x12GetTableProperties\x12\x1d\n" +
	"\n" +
	"table_name\x18\x01 \x01(\tR\ttableName\"P\n" +
	"\x14GetCreateTableString\x12\x1d\n" +
	"\n" +
	"table_name\x18\x01 \x01(\tR\ttableName\x12\x19\n" +
	"\bas_serde\x18\x02 \x01(\bR\aasSerde\".\n" +
	"\rTruncateTable\x12\x1d\n" +
	"\n" +
	"table_name\x18\x01 \x01(\tR\ttableName\"F\n" +
	"\fAnalyzeTable\x12\x1d\n" +
	"\n" +
	"table_name\x18\x01 \x01(\tR\ttableName\x12\x17\n" +
	"\ano_scan\x18\x02 \x01(\bR\x06noScanB6\n" +
	"\x1eorg.apache.spark.connect.protoP\x01Z\x12internal/generatedb\x06proto3"

var (
	file_spark_connect_catalog_proto_rawDescOnce sync.Once
	file_spark_connect_catalog_proto_rawDescData []byte
)

func file_spark_connect_catalog_proto_rawDescGZIP() []byte {
	file_spark_connect_catalog_proto_rawDescOnce.Do(func() {
		file_spark_connect_catalog_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_spark_connect_catalog_proto_rawDesc), len(file_spark_connect_catalog_proto_rawDesc)))
	})
	return file_spark_connect_catalog_proto_rawDescData
}

var file_spark_connect_catalog_proto_msgTypes = make([]protoimpl.MessageInfo, 40)
var file_spark_connect_catalog_proto_goTypes = []any{
	(*Catalog)(nil),              // 0: spark.connect.Catalog
	(*CurrentDatabase)(nil),      // 1: spark.connect.CurrentDatabase
	(*SetCurrentDatabase)(nil),   // 2: spark.connect.SetCurrentDatabase
	(*ListDatabases)(nil),        // 3: spark.connect.ListDatabases
	(*ListTables)(nil),           // 4: spark.connect.ListTables
	(*ListFunctions)(nil),        // 5: spark.connect.ListFunctions
	(*ListColumns)(nil),          // 6: spark.connect.ListColumns
	(*GetDatabase)(nil),          // 7: spark.connect.GetDatabase
	(*GetTable)(nil),             // 8: spark.connect.GetTable
	(*GetFunction)(nil),          // 9: spark.connect.GetFunction
	(*DatabaseExists)(nil),       // 10: spark.connect.DatabaseExists
	(*TableExists)(nil),          // 11: spark.connect.TableExists
	(*FunctionExists)(nil),       // 12: spark.connect.FunctionExists
	(*CreateExternalTable)(nil),  // 13: spark.connect.CreateExternalTable
	(*CreateTable)(nil),          // 14: spark.connect.CreateTable
	(*DropTempView)(nil),         // 15: spark.connect.DropTempView
	(*DropGlobalTempView)(nil),   // 16: spark.connect.DropGlobalTempView
	(*RecoverPartitions)(nil),    // 17: spark.connect.RecoverPartitions
	(*IsCached)(nil),             // 18: spark.connect.IsCached
	(*CacheTable)(nil),           // 19: spark.connect.CacheTable
	(*UncacheTable)(nil),         // 20: spark.connect.UncacheTable
	(*ClearCache)(nil),           // 21: spark.connect.ClearCache
	(*RefreshTable)(nil),         // 22: spark.connect.RefreshTable
	(*RefreshByPath)(nil),        // 23: spark.connect.RefreshByPath
	(*CurrentCatalog)(nil),       // 24: spark.connect.CurrentCatalog
	(*SetCurrentCatalog)(nil),    // 25: spark.connect.SetCurrentCatalog
	(*ListCatalogs)(nil),         // 26: spark.connect.ListCatalogs
	(*DropTable)(nil),            // 27: spark.connect.DropTable
	(*DropView)(nil),             // 28: spark.connect.DropView
	(*CreateDatabase)(nil),       // 29: spark.connect.CreateDatabase
	(*DropDatabase)(nil),         // 30: spark.connect.DropDatabase
	(*ListPartitions)(nil),       // 31: spark.connect.ListPartitions
	(*ListViews)(nil),            // 32: spark.connect.ListViews
	(*GetTableProperties)(nil),   // 33: spark.connect.GetTableProperties
	(*GetCreateTableString)(nil), // 34: spark.connect.GetCreateTableString
	(*TruncateTable)(nil),        // 35: spark.connect.TruncateTable
	(*AnalyzeTable)(nil),         // 36: spark.connect.AnalyzeTable
	nil,                          // 37: spark.connect.CreateExternalTable.OptionsEntry
	nil,                          // 38: spark.connect.CreateTable.OptionsEntry
	nil,                          // 39: spark.connect.CreateDatabase.PropertiesEntry
	(*DataType)(nil),             // 40: spark.connect.DataType
	(*StorageLevel)(nil),         // 41: spark.connect.StorageLevel
}
var file_spark_connect_catalog_proto_depIdxs = []int32{
	1,  // 0: spark.connect.Catalog.current_database:type_name -> spark.connect.CurrentDatabase
	2,  // 1: spark.connect.Catalog.set_current_database:type_name -> spark.connect.SetCurrentDatabase
	3,  // 2: spark.connect.Catalog.list_databases:type_name -> spark.connect.ListDatabases
	4,  // 3: spark.connect.Catalog.list_tables:type_name -> spark.connect.ListTables
	5,  // 4: spark.connect.Catalog.list_functions:type_name -> spark.connect.ListFunctions
	6,  // 5: spark.connect.Catalog.list_columns:type_name -> spark.connect.ListColumns
	7,  // 6: spark.connect.Catalog.get_database:type_name -> spark.connect.GetDatabase
	8,  // 7: spark.connect.Catalog.get_table:type_name -> spark.connect.GetTable
	9,  // 8: spark.connect.Catalog.get_function:type_name -> spark.connect.GetFunction
	10, // 9: spark.connect.Catalog.database_exists:type_name -> spark.connect.DatabaseExists
	11, // 10: spark.connect.Catalog.table_exists:type_name -> spark.connect.TableExists
	12, // 11: spark.connect.Catalog.function_exists:type_name -> spark.connect.FunctionExists
	13, // 12: spark.connect.Catalog.create_external_table:type_name -> spark.connect.CreateExternalTable
	14, // 13: spark.connect.Catalog.create_table:type_name -> spark.connect.CreateTable
	15, // 14: spark.connect.Catalog.drop_temp_view:type_name -> spark.connect.DropTempView
	16, // 15: spark.connect.Catalog.drop_global_temp_view:type_name -> spark.connect.DropGlobalTempView
	17, // 16: spark.connect.Catalog.recover_partitions:type_name -> spark.connect.RecoverPartitions
	18, // 17: spark.connect.Catalog.is_cached:type_name -> spark.connect.IsCached
	19, // 18: spark.connect.Catalog.cache_table:type_name -> spark.connect.CacheTable
	20, // 19: spark.connect.Catalog.uncache_table:type_name -> spark.connect.UncacheTable
	21, // 20: spark.connect.Catalog.clear_cache:type_name -> spark.connect.ClearCache
	22, // 21: spark.connect.Catalog.refresh_table:type_name -> spark.connect.RefreshTable
	23, // 22: spark.connect.Catalog.refresh_by_path:type_name -> spark.connect.RefreshByPath
	24, // 23: spark.connect.Catalog.current_catalog:type_name -> spark.connect.CurrentCatalog
	25, // 24: spark.connect.Catalog.set_current_catalog:type_name -> spark.connect.SetCurrentCatalog
	26, // 25: spark.connect.Catalog.list_catalogs:type_name -> spark.connect.ListCatalogs
	27, // 26: spark.connect.Catalog.drop_table:type_name -> spark.connect.DropTable
	28, // 27: spark.connect.Catalog.drop_view:type_name -> spark.connect.DropView
	29, // 28: spark.connect.Catalog.create_database:type_name -> spark.connect.CreateDatabase
	30, // 29: spark.connect.Catalog.drop_database:type_name -> spark.connect.DropDatabase
	31, // 30: spark.connect.Catalog.list_partitions:type_name -> spark.connect.ListPartitions
	32, // 31: spark.connect.Catalog.list_views:type_name -> spark.connect.ListViews
	33, // 32: spark.connect.Catalog.get_table_properties:type_name -> spark.connect.GetTableProperties
	34, // 33: spark.connect.Catalog.get_create_table_string:type_name -> spark.connect.GetCreateTableString
	35, // 34: spark.connect.Catalog.truncate_table:type_name -> spark.connect.TruncateTable
	36, // 35: spark.connect.Catalog.analyze_table:type_name -> spark.connect.AnalyzeTable
	40, // 36: spark.connect.CreateExternalTable.schema:type_name -> spark.connect.DataType
	37, // 37: spark.connect.CreateExternalTable.options:type_name -> spark.connect.CreateExternalTable.OptionsEntry
	40, // 38: spark.connect.CreateTable.schema:type_name -> spark.connect.DataType
	38, // 39: spark.connect.CreateTable.options:type_name -> spark.connect.CreateTable.OptionsEntry
	41, // 40: spark.connect.CacheTable.storage_level:type_name -> spark.connect.StorageLevel
	39, // 41: spark.connect.CreateDatabase.properties:type_name -> spark.connect.CreateDatabase.PropertiesEntry
	42, // [42:42] is the sub-list for method output_type
	42, // [42:42] is the sub-list for method input_type
	42, // [42:42] is the sub-list for extension type_name
	42, // [42:42] is the sub-list for extension extendee
	0,  // [0:42] is the sub-list for field type_name
}

func init() { file_spark_connect_catalog_proto_init() }
func file_spark_connect_catalog_proto_init() {
	if File_spark_connect_catalog_proto != nil {
		return
	}
	file_spark_connect_common_proto_init()
	file_spark_connect_types_proto_init()
	file_spark_connect_catalog_proto_msgTypes[0].OneofWrappers = []any{
		(*Catalog_CurrentDatabase)(nil),
		(*Catalog_SetCurrentDatabase)(nil),
		(*Catalog_ListDatabases)(nil),
		(*Catalog_ListTables)(nil),
		(*Catalog_ListFunctions)(nil),
		(*Catalog_ListColumns)(nil),
		(*Catalog_GetDatabase)(nil),
		(*Catalog_GetTable)(nil),
		(*Catalog_GetFunction)(nil),
		(*Catalog_DatabaseExists)(nil),
		(*Catalog_TableExists)(nil),
		(*Catalog_FunctionExists)(nil),
		(*Catalog_CreateExternalTable)(nil),
		(*Catalog_CreateTable)(nil),
		(*Catalog_DropTempView)(nil),
		(*Catalog_DropGlobalTempView)(nil),
		(*Catalog_RecoverPartitions)(nil),
		(*Catalog_IsCached)(nil),
		(*Catalog_CacheTable)(nil),
		(*Catalog_UncacheTable)(nil),
		(*Catalog_ClearCache)(nil),
		(*Catalog_RefreshTable)(nil),
		(*Catalog_RefreshByPath)(nil),
		(*Catalog_CurrentCatalog)(nil),
		(*Catalog_SetCurrentCatalog)(nil),
		(*Catalog_ListCatalogs)(nil),
		(*Catalog_DropTable)(nil),
		(*Catalog_DropView)(nil),
		(*Catalog_CreateDatabase)(nil),
		(*Catalog_DropDatabase)(nil),
		(*Catalog_ListPartitions)(nil),
		(*Catalog_ListViews)(nil),
		(*Catalog_GetTableProperties)(nil),
		(*Catalog_GetCreateTableString)(nil),
		(*Catalog_TruncateTable)(nil),
		(*Catalog_AnalyzeTable)(nil),
	}
	file_spark_connect_catalog_proto_msgTypes[3].OneofWrappers = []any{}
	file_spark_connect_catalog_proto_msgTypes[4].OneofWrappers = []any{}
	file_spark_connect_catalog_proto_msgTypes[5].OneofWrappers = []any{}
	file_spark_connect_catalog_proto_msgTypes[6].OneofWrappers = []any{}
	file_spark_connect_catalog_proto_msgTypes[8].OneofWrappers = []any{}
	file_spark_connect_catalog_proto_msgTypes[9].OneofWrappers = []any{}
	file_spark_connect_catalog_proto_msgTypes[11].OneofWrappers = []any{}
	file_spark_connect_catalog_proto_msgTypes[12].OneofWrappers = []any{}
	file_spark_connect_catalog_proto_msgTypes[13].OneofWrappers = []any{}
	file_spark_connect_catalog_proto_msgTypes[14].OneofWrappers = []any{}
	file_spark_connect_catalog_proto_msgTypes[19].OneofWrappers = []any{}
	file_spark_connect_catalog_proto_msgTypes[26].OneofWrappers = []any{}
	file_spark_connect_catalog_proto_msgTypes[32].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_spark_connect_catalog_proto_rawDesc), len(file_spark_connect_catalog_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   40,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_spark_connect_catalog_proto_goTypes,
		DependencyIndexes: file_spark_connect_catalog_proto_depIdxs,
		MessageInfos:      file_spark_connect_catalog_proto_msgTypes,
	}.Build()
	File_spark_connect_catalog_proto = out.File
	file_spark_connect_catalog_proto_goTypes = nil
	file_spark_connect_catalog_proto_depIdxs = nil
}
