//
// Licensed to the Apache Software Foundation (ASF) under one or more
// contributor license agreements.  See the NOTICE file distributed with
// this work for additional information regarding copyright ownership.
// The ASF licenses this file to You under the Apache License, Version 2.0
// (the "License"); you may not use this file except in compliance with
// the License.  You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: spark/connect/common.proto

package generated

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// StorageLevel for persisting Datasets/Tables.
type StorageLevel struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// (Required) Whether the cache should use disk or not.
	UseDisk bool `protobuf:"varint,1,opt,name=use_disk,json=useDisk,proto3" json:"use_disk,omitempty"`
	// (Required) Whether the cache should use memory or not.
	UseMemory bool `protobuf:"varint,2,opt,name=use_memory,json=useMemory,proto3" json:"use_memory,omitempty"`
	// (Required) Whether the cache should use off-heap or not.
	UseOffHeap bool `protobuf:"varint,3,opt,name=use_off_heap,json=useOffHeap,proto3" json:"use_off_heap,omitempty"`
	// (Required) Whether the cached data is deserialized or not.
	Deserialized bool `protobuf:"varint,4,opt,name=deserialized,proto3" json:"deserialized,omitempty"`
	// (Required) The number of replicas.
	Replication   int32 `protobuf:"varint,5,opt,name=replication,proto3" json:"replication,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StorageLevel) Reset() {
	*x = StorageLevel{}
	mi := &file_spark_connect_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageLevel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageLevel) ProtoMessage() {}

func (x *StorageLevel) ProtoReflect() protoreflect.Message {
	mi := &file_spark_connect_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageLevel.ProtoReflect.Descriptor instead.
func (*StorageLevel) Descriptor() ([]byte, []int) {
	return file_spark_connect_common_proto_rawDescGZIP(), []int{0}
}

func (x *StorageLevel) GetUseDisk() bool {
	if x != nil {
		return x.UseDisk
	}
	return false
}

func (x *StorageLevel) GetUseMemory() bool {
	if x != nil {
		return x.UseMemory
	}
	return false
}

func (x *StorageLevel) GetUseOffHeap() bool {
	if x != nil {
		return x.UseOffHeap
	}
	return false
}

func (x *StorageLevel) GetDeserialized() bool {
	if x != nil {
		return x.Deserialized
	}
	return false
}

func (x *StorageLevel) GetReplication() int32 {
	if x != nil {
		return x.Replication
	}
	return 0
}

// ResourceInformation to hold information about a type of Resource.
// The corresponding class is 'org.apache.spark.resource.ResourceInformation'
type ResourceInformation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// (Required) The name of the resource
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// (Required) An array of strings describing the addresses of the resource.
	Addresses     []string `protobuf:"bytes,2,rep,name=addresses,proto3" json:"addresses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceInformation) Reset() {
	*x = ResourceInformation{}
	mi := &file_spark_connect_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceInformation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceInformation) ProtoMessage() {}

func (x *ResourceInformation) ProtoReflect() protoreflect.Message {
	mi := &file_spark_connect_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceInformation.ProtoReflect.Descriptor instead.
func (*ResourceInformation) Descriptor() ([]byte, []int) {
	return file_spark_connect_common_proto_rawDescGZIP(), []int{1}
}

func (x *ResourceInformation) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ResourceInformation) GetAddresses() []string {
	if x != nil {
		return x.Addresses
	}
	return nil
}

// An executor resource request.
type ExecutorResourceRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// (Required) resource name.
	ResourceName string `protobuf:"bytes,1,opt,name=resource_name,json=resourceName,proto3" json:"resource_name,omitempty"`
	// (Required) resource amount requesting.
	Amount int64 `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	// Optional script used to discover the resources.
	DiscoveryScript *string `protobuf:"bytes,3,opt,name=discovery_script,json=discoveryScript,proto3,oneof" json:"discovery_script,omitempty"`
	// Optional vendor, required for some cluster managers.
	Vendor        *string `protobuf:"bytes,4,opt,name=vendor,proto3,oneof" json:"vendor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutorResourceRequest) Reset() {
	*x = ExecutorResourceRequest{}
	mi := &file_spark_connect_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutorResourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutorResourceRequest) ProtoMessage() {}

func (x *ExecutorResourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spark_connect_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutorResourceRequest.ProtoReflect.Descriptor instead.
func (*ExecutorResourceRequest) Descriptor() ([]byte, []int) {
	return file_spark_connect_common_proto_rawDescGZIP(), []int{2}
}

func (x *ExecutorResourceRequest) GetResourceName() string {
	if x != nil {
		return x.ResourceName
	}
	return ""
}

func (x *ExecutorResourceRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *ExecutorResourceRequest) GetDiscoveryScript() string {
	if x != nil && x.DiscoveryScript != nil {
		return *x.DiscoveryScript
	}
	return ""
}

func (x *ExecutorResourceRequest) GetVendor() string {
	if x != nil && x.Vendor != nil {
		return *x.Vendor
	}
	return ""
}

// A task resource request.
type TaskResourceRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// (Required) resource name.
	ResourceName string `protobuf:"bytes,1,opt,name=resource_name,json=resourceName,proto3" json:"resource_name,omitempty"`
	// (Required) resource amount requesting as a double to support fractional
	// resource requests.
	Amount        float64 `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskResourceRequest) Reset() {
	*x = TaskResourceRequest{}
	mi := &file_spark_connect_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResourceRequest) ProtoMessage() {}

func (x *TaskResourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spark_connect_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResourceRequest.ProtoReflect.Descriptor instead.
func (*TaskResourceRequest) Descriptor() ([]byte, []int) {
	return file_spark_connect_common_proto_rawDescGZIP(), []int{3}
}

func (x *TaskResourceRequest) GetResourceName() string {
	if x != nil {
		return x.ResourceName
	}
	return ""
}

func (x *TaskResourceRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type ResourceProfile struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// (Optional) Resource requests for executors. Mapped from the resource name
	// (e.g., cores, memory, CPU) to its specific request.
	ExecutorResources map[string]*ExecutorResourceRequest `protobuf:"bytes,1,rep,name=executor_resources,json=executorResources,proto3" json:"executor_resources,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// (Optional) Resource requests for tasks. Mapped from the resource name
	// (e.g., cores, memory, CPU) to its specific request.
	TaskResources map[string]*TaskResourceRequest `protobuf:"bytes,2,rep,name=task_resources,json=taskResources,proto3" json:"task_resources,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceProfile) Reset() {
	*x = ResourceProfile{}
	mi := &file_spark_connect_common_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceProfile) ProtoMessage() {}

func (x *ResourceProfile) ProtoReflect() protoreflect.Message {
	mi := &file_spark_connect_common_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceProfile.ProtoReflect.Descriptor instead.
func (*ResourceProfile) Descriptor() ([]byte, []int) {
	return file_spark_connect_common_proto_rawDescGZIP(), []int{4}
}

func (x *ResourceProfile) GetExecutorResources() map[string]*ExecutorResourceRequest {
	if x != nil {
		return x.ExecutorResources
	}
	return nil
}

func (x *ResourceProfile) GetTaskResources() map[string]*TaskResourceRequest {
	if x != nil {
		return x.TaskResources
	}
	return nil
}

type Origin struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// (Required) Indicate the origin type.
	//
	// Types that are valid to be assigned to Function:
	//
	//	*Origin_PythonOrigin
	//	*Origin_JvmOrigin
	Function      isOrigin_Function `protobuf_oneof:"function"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Origin) Reset() {
	*x = Origin{}
	mi := &file_spark_connect_common_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Origin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Origin) ProtoMessage() {}

func (x *Origin) ProtoReflect() protoreflect.Message {
	mi := &file_spark_connect_common_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Origin.ProtoReflect.Descriptor instead.
func (*Origin) Descriptor() ([]byte, []int) {
	return file_spark_connect_common_proto_rawDescGZIP(), []int{5}
}

func (x *Origin) GetFunction() isOrigin_Function {
	if x != nil {
		return x.Function
	}
	return nil
}

func (x *Origin) GetPythonOrigin() *PythonOrigin {
	if x != nil {
		if x, ok := x.Function.(*Origin_PythonOrigin); ok {
			return x.PythonOrigin
		}
	}
	return nil
}

func (x *Origin) GetJvmOrigin() *JvmOrigin {
	if x != nil {
		if x, ok := x.Function.(*Origin_JvmOrigin); ok {
			return x.JvmOrigin
		}
	}
	return nil
}

type isOrigin_Function interface {
	isOrigin_Function()
}

type Origin_PythonOrigin struct {
	PythonOrigin *PythonOrigin `protobuf:"bytes,1,opt,name=python_origin,json=pythonOrigin,proto3,oneof"`
}

type Origin_JvmOrigin struct {
	JvmOrigin *JvmOrigin `protobuf:"bytes,2,opt,name=jvm_origin,json=jvmOrigin,proto3,oneof"`
}

func (*Origin_PythonOrigin) isOrigin_Function() {}

func (*Origin_JvmOrigin) isOrigin_Function() {}

type PythonOrigin struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// (Required) Name of the origin, for example, the name of the function
	Fragment string `protobuf:"bytes,1,opt,name=fragment,proto3" json:"fragment,omitempty"`
	// (Required) Callsite to show to end users, for example, stacktrace.
	CallSite      string `protobuf:"bytes,2,opt,name=call_site,json=callSite,proto3" json:"call_site,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PythonOrigin) Reset() {
	*x = PythonOrigin{}
	mi := &file_spark_connect_common_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PythonOrigin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PythonOrigin) ProtoMessage() {}

func (x *PythonOrigin) ProtoReflect() protoreflect.Message {
	mi := &file_spark_connect_common_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PythonOrigin.ProtoReflect.Descriptor instead.
func (*PythonOrigin) Descriptor() ([]byte, []int) {
	return file_spark_connect_common_proto_rawDescGZIP(), []int{6}
}

func (x *PythonOrigin) GetFragment() string {
	if x != nil {
		return x.Fragment
	}
	return ""
}

func (x *PythonOrigin) GetCallSite() string {
	if x != nil {
		return x.CallSite
	}
	return ""
}

type JvmOrigin struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// (Optional) Line number in the source file.
	Line *int32 `protobuf:"varint,1,opt,name=line,proto3,oneof" json:"line,omitempty"`
	// (Optional) Start position in the source file.
	StartPosition *int32 `protobuf:"varint,2,opt,name=start_position,json=startPosition,proto3,oneof" json:"start_position,omitempty"`
	// (Optional) Start index in the source file.
	StartIndex *int32 `protobuf:"varint,3,opt,name=start_index,json=startIndex,proto3,oneof" json:"start_index,omitempty"`
	// (Optional) Stop index in the source file.
	StopIndex *int32 `protobuf:"varint,4,opt,name=stop_index,json=stopIndex,proto3,oneof" json:"stop_index,omitempty"`
	// (Optional) SQL text.
	SqlText *string `protobuf:"bytes,5,opt,name=sql_text,json=sqlText,proto3,oneof" json:"sql_text,omitempty"`
	// (Optional) Object type.
	ObjectType *string `protobuf:"bytes,6,opt,name=object_type,json=objectType,proto3,oneof" json:"object_type,omitempty"`
	// (Optional) Object name.
	ObjectName *string `protobuf:"bytes,7,opt,name=object_name,json=objectName,proto3,oneof" json:"object_name,omitempty"`
	// (Optional) Stack trace.
	StackTrace    []*StackTraceElement `protobuf:"bytes,8,rep,name=stack_trace,json=stackTrace,proto3" json:"stack_trace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JvmOrigin) Reset() {
	*x = JvmOrigin{}
	mi := &file_spark_connect_common_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JvmOrigin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JvmOrigin) ProtoMessage() {}

func (x *JvmOrigin) ProtoReflect() protoreflect.Message {
	mi := &file_spark_connect_common_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JvmOrigin.ProtoReflect.Descriptor instead.
func (*JvmOrigin) Descriptor() ([]byte, []int) {
	return file_spark_connect_common_proto_rawDescGZIP(), []int{7}
}

func (x *JvmOrigin) GetLine() int32 {
	if x != nil && x.Line != nil {
		return *x.Line
	}
	return 0
}

func (x *JvmOrigin) GetStartPosition() int32 {
	if x != nil && x.StartPosition != nil {
		return *x.StartPosition
	}
	return 0
}

func (x *JvmOrigin) GetStartIndex() int32 {
	if x != nil && x.StartIndex != nil {
		return *x.StartIndex
	}
	return 0
}

func (x *JvmOrigin) GetStopIndex() int32 {
	if x != nil && x.StopIndex != nil {
		return *x.StopIndex
	}
	return 0
}

func (x *JvmOrigin) GetSqlText() string {
	if x != nil && x.SqlText != nil {
		return *x.SqlText
	}
	return ""
}

func (x *JvmOrigin) GetObjectType() string {
	if x != nil && x.ObjectType != nil {
		return *x.ObjectType
	}
	return ""
}

func (x *JvmOrigin) GetObjectName() string {
	if x != nil && x.ObjectName != nil {
		return *x.ObjectName
	}
	return ""
}

func (x *JvmOrigin) GetStackTrace() []*StackTraceElement {
	if x != nil {
		return x.StackTrace
	}
	return nil
}

// A message to hold a [[java.lang.StackTraceElement]].
type StackTraceElement struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// (Optional) Class loader name
	ClassLoaderName *string `protobuf:"bytes,1,opt,name=class_loader_name,json=classLoaderName,proto3,oneof" json:"class_loader_name,omitempty"`
	// (Optional) Module name
	ModuleName *string `protobuf:"bytes,2,opt,name=module_name,json=moduleName,proto3,oneof" json:"module_name,omitempty"`
	// (Optional) Module version
	ModuleVersion *string `protobuf:"bytes,3,opt,name=module_version,json=moduleVersion,proto3,oneof" json:"module_version,omitempty"`
	// (Required) Declaring class
	DeclaringClass string `protobuf:"bytes,4,opt,name=declaring_class,json=declaringClass,proto3" json:"declaring_class,omitempty"`
	// (Required) Method name
	MethodName string `protobuf:"bytes,5,opt,name=method_name,json=methodName,proto3" json:"method_name,omitempty"`
	// (Optional) File name
	FileName *string `protobuf:"bytes,6,opt,name=file_name,json=fileName,proto3,oneof" json:"file_name,omitempty"`
	// (Required) Line number
	LineNumber    int32 `protobuf:"varint,7,opt,name=line_number,json=lineNumber,proto3" json:"line_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StackTraceElement) Reset() {
	*x = StackTraceElement{}
	mi := &file_spark_connect_common_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StackTraceElement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StackTraceElement) ProtoMessage() {}

func (x *StackTraceElement) ProtoReflect() protoreflect.Message {
	mi := &file_spark_connect_common_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StackTraceElement.ProtoReflect.Descriptor instead.
func (*StackTraceElement) Descriptor() ([]byte, []int) {
	return file_spark_connect_common_proto_rawDescGZIP(), []int{8}
}

func (x *StackTraceElement) GetClassLoaderName() string {
	if x != nil && x.ClassLoaderName != nil {
		return *x.ClassLoaderName
	}
	return ""
}

func (x *StackTraceElement) GetModuleName() string {
	if x != nil && x.ModuleName != nil {
		return *x.ModuleName
	}
	return ""
}

func (x *StackTraceElement) GetModuleVersion() string {
	if x != nil && x.ModuleVersion != nil {
		return *x.ModuleVersion
	}
	return ""
}

func (x *StackTraceElement) GetDeclaringClass() string {
	if x != nil {
		return x.DeclaringClass
	}
	return ""
}

func (x *StackTraceElement) GetMethodName() string {
	if x != nil {
		return x.MethodName
	}
	return ""
}

func (x *StackTraceElement) GetFileName() string {
	if x != nil && x.FileName != nil {
		return *x.FileName
	}
	return ""
}

func (x *StackTraceElement) GetLineNumber() int32 {
	if x != nil {
		return x.LineNumber
	}
	return 0
}

type ResolvedIdentifier struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CatalogName   string                 `protobuf:"bytes,1,opt,name=catalog_name,json=catalogName,proto3" json:"catalog_name,omitempty"`
	Namespace     []string               `protobuf:"bytes,2,rep,name=namespace,proto3" json:"namespace,omitempty"`
	TableName     string                 `protobuf:"bytes,3,opt,name=table_name,json=tableName,proto3" json:"table_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolvedIdentifier) Reset() {
	*x = ResolvedIdentifier{}
	mi := &file_spark_connect_common_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolvedIdentifier) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolvedIdentifier) ProtoMessage() {}

func (x *ResolvedIdentifier) ProtoReflect() protoreflect.Message {
	mi := &file_spark_connect_common_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolvedIdentifier.ProtoReflect.Descriptor instead.
func (*ResolvedIdentifier) Descriptor() ([]byte, []int) {
	return file_spark_connect_common_proto_rawDescGZIP(), []int{9}
}

func (x *ResolvedIdentifier) GetCatalogName() string {
	if x != nil {
		return x.CatalogName
	}
	return ""
}

func (x *ResolvedIdentifier) GetNamespace() []string {
	if x != nil {
		return x.Namespace
	}
	return nil
}

func (x *ResolvedIdentifier) GetTableName() string {
	if x != nil {
		return x.TableName
	}
	return ""
}

type Bools struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []bool                 `protobuf:"varint,1,rep,packed,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bools) Reset() {
	*x = Bools{}
	mi := &file_spark_connect_common_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bools) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bools) ProtoMessage() {}

func (x *Bools) ProtoReflect() protoreflect.Message {
	mi := &file_spark_connect_common_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bools.ProtoReflect.Descriptor instead.
func (*Bools) Descriptor() ([]byte, []int) {
	return file_spark_connect_common_proto_rawDescGZIP(), []int{10}
}

func (x *Bools) GetValues() []bool {
	if x != nil {
		return x.Values
	}
	return nil
}

type Ints struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []int32                `protobuf:"varint,1,rep,packed,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ints) Reset() {
	*x = Ints{}
	mi := &file_spark_connect_common_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ints) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ints) ProtoMessage() {}

func (x *Ints) ProtoReflect() protoreflect.Message {
	mi := &file_spark_connect_common_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ints.ProtoReflect.Descriptor instead.
func (*Ints) Descriptor() ([]byte, []int) {
	return file_spark_connect_common_proto_rawDescGZIP(), []int{11}
}

func (x *Ints) GetValues() []int32 {
	if x != nil {
		return x.Values
	}
	return nil
}

type Longs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []int64                `protobuf:"varint,1,rep,packed,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Longs) Reset() {
	*x = Longs{}
	mi := &file_spark_connect_common_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Longs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Longs) ProtoMessage() {}

func (x *Longs) ProtoReflect() protoreflect.Message {
	mi := &file_spark_connect_common_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Longs.ProtoReflect.Descriptor instead.
func (*Longs) Descriptor() ([]byte, []int) {
	return file_spark_connect_common_proto_rawDescGZIP(), []int{12}
}

func (x *Longs) GetValues() []int64 {
	if x != nil {
		return x.Values
	}
	return nil
}

type Floats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []float32              `protobuf:"fixed32,1,rep,packed,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Floats) Reset() {
	*x = Floats{}
	mi := &file_spark_connect_common_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Floats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Floats) ProtoMessage() {}

func (x *Floats) ProtoReflect() protoreflect.Message {
	mi := &file_spark_connect_common_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Floats.ProtoReflect.Descriptor instead.
func (*Floats) Descriptor() ([]byte, []int) {
	return file_spark_connect_common_proto_rawDescGZIP(), []int{13}
}

func (x *Floats) GetValues() []float32 {
	if x != nil {
		return x.Values
	}
	return nil
}

type Doubles struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []float64              `protobuf:"fixed64,1,rep,packed,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Doubles) Reset() {
	*x = Doubles{}
	mi := &file_spark_connect_common_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Doubles) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Doubles) ProtoMessage() {}

func (x *Doubles) ProtoReflect() protoreflect.Message {
	mi := &file_spark_connect_common_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Doubles.ProtoReflect.Descriptor instead.
func (*Doubles) Descriptor() ([]byte, []int) {
	return file_spark_connect_common_proto_rawDescGZIP(), []int{14}
}

func (x *Doubles) GetValues() []float64 {
	if x != nil {
		return x.Values
	}
	return nil
}

type Strings struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []string               `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Strings) Reset() {
	*x = Strings{}
	mi := &file_spark_connect_common_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Strings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Strings) ProtoMessage() {}

func (x *Strings) ProtoReflect() protoreflect.Message {
	mi := &file_spark_connect_common_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Strings.ProtoReflect.Descriptor instead.
func (*Strings) Descriptor() ([]byte, []int) {
	return file_spark_connect_common_proto_rawDescGZIP(), []int{15}
}

func (x *Strings) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

var File_spark_connect_common_proto protoreflect.FileDescriptor

const file_spark_connect_common_proto_rawDesc = "" +
	"\n" +
	"\x1aspark/connect/common.proto\x12\rspark.connect\"\xb0\x01\n" +
	"\fStorageLevel\x12\x19\n" +
	"\buse_disk\x18\x01 \x01(\bR\auseDisk\x12\x1d\n" +
	"\n" +
	"use_memory\x18\x02 \x01(\bR\tuseMemory\x12 \n" +
	"\fuse_off_heap\x18\x03 \x01(\bR\n" +
	"useOffHeap\x12\"\n" +
	"\fdeserialized\x18\x04 \x01(\bR\fdeserialized\x12 \n" +
	"\vreplication\x18\x05 \x01(\x05R\vreplication\"G\n" +
	"\x13ResourceInformation\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\taddresses\x18\x02 \x03(\tR\taddresses\"\xc3\x01\n" +
	"\x17ExecutorResourceRequest\x12#\n" +
	"\rresource_name\x18\x01 \x01(\tR\fresourceName\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x03R\x06amount\x12.\n" +
	"\x10discovery_script\x18\x03 \x01(\tH\x00R\x0fdiscoveryScript\x88\x01\x01\x12\x1b\n" +
	"\x06vendor\x18\x04 \x01(\tH\x01R\x06vendor\x88\x01\x01B\x13\n" +
	"\x11_discovery_scriptB\t\n" +
	"\a_vendor\"R\n" +
	"\x13TaskResourceRequest\x12#\n" +
	"\rresource_name\x18\x01 \x01(\tR\fresourceName\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x01R\x06amount\"\xa5\x03\n" +
	"\x0fResourceProfile\x12d\n" +
	"\x12executor_resources\x18\x01 \x03(\v25.spark.connect.ResourceProfile.ExecutorResourcesEntryR\x11executorResources\x12X\n" +
	"\x0etask_resources\x18\x02 \x03(\v21.spark.connect.ResourceProfile.TaskResourcesEntryR\rtaskResources\x1al\n" +
	"\x16ExecutorResourcesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12<\n" +
	"\x05value\x18\x02 \x01(\v2&.spark.connect.ExecutorResourceRequestR\x05value:\x028\x01\x1ad\n" +
	"\x12TaskResourcesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x128\n" +
	"\x05value\x18\x02 \x01(\v2\".spark.connect.TaskResourceRequestR\x05value:\x028\x01\"\x93\x01\n" +
	"\x06Origin\x12B\n" +
	"\rpython_origin\x18\x01 \x01(\v2\x1b.spark.connect.PythonOriginH\x00R\fpythonOrigin\x129\n" +
	"\n" +
	"jvm_origin\x18\x02 \x01(\v2\x18.spark.connect.JvmOriginH\x00R\tjvmOriginB\n" +
	"\n" +
	"\bfunction\"G\n" +
	"\fPythonOrigin\x12\x1a\n" +
	"\bfragment\x18\x01 \x01(\tR\bfragment\x12\x1b\n" +
	"\tcall_site\x18\x02 \x01(\tR\bcallSite\"\xb1\x03\n" +
	"\tJvmOrigin\x12\x17\n" +
	"\x04line\x18\x01 \x01(\x05H\x00R\x04line\x88\x01\x01\x12*\n" +
	"\x0estart_position\x18\x02 \x01(\x05H\x01R\rstartPosition\x88\x01\x01\x12$\n" +
	"\vstart_index\x18\x03 \x01(\x05H\x02R\n" +
	"startIndex\x88\x01\x01\x12\"\n" +
	"\n" +
	"stop_index\x18\x04 \x01(\x05H\x03R\tstopIndex\x88\x01\x01\x12\x1e\n" +
	"\bsql_text\x18\x05 \x01(\tH\x04R\asqlText\x88\x01\x01\x12$\n" +
	"\vobject_type\x18\x06 \x01(\tH\x05R\n" +
	"objectType\x88\x01\x01\x12$\n" +
	"\vobject_name\x18\a \x01(\tH\x06R\n" +
	"objectName\x88\x01\x01\x12A\n" +
	"\vstack_trace\x18\b \x03(\v2 .spark.connect.StackTraceElementR\n" +
	"stackTraceB\a\n" +
	"\x05_lineB\x11\n" +
	"\x0f_start_positionB\x0e\n" +
	"\f_start_indexB\r\n" +
	"\v_stop_indexB\v\n" +
	"\t_sql_textB\x0e\n" +
	"\f_object_typeB\x0e\n" +
	"\f_object_name\"\xea\x02\n" +
	"\x11StackTraceElement\x12/\n" +
	"\x11class_loader_name\x18\x01 \x01(\tH\x00R\x0fclassLoaderName\x88\x01\x01\x12$\n" +
	"\vmodule_name\x18\x02 \x01(\tH\x01R\n" +
	"moduleName\x88\x01\x01\x12*\n" +
	"\x0emodule_version\x18\x03 \x01(\tH\x02R\rmoduleVersion\x88\x01\x01\x12'\n" +
	"\x0fdeclaring_class\x18\x04 \x01(\tR\x0edeclaringClass\x12\x1f\n" +
	"\vmethod_name\x18\x05 \x01(\tR\n" +
	"methodName\x12 \n" +
	"\tfile_name\x18\x06 \x01(\tH\x03R\bfileName\x88\x01\x01\x12\x1f\n" +
	"\vline_number\x18\a \x01(\x05R\n" +
	"lineNumberB\x14\n" +
	"\x12_class_loader_nameB\x0e\n" +
	"\f_module_nameB\x11\n" +
	"\x0f_module_versionB\f\n" +
	"\n" +
	"_file_name\"t\n" +
	"\x12ResolvedIdentifier\x12!\n" +
	"\fcatalog_name\x18\x01 \x01(\tR\vcatalogName\x12\x1c\n" +
	"\tnamespace\x18\x02 \x03(\tR\tnamespace\x12\x1d\n" +
	"\n" +
	"table_name\x18\x03 \x01(\tR\ttableName\"\x1f\n" +
	"\x05Bools\x12\x16\n" +
	"\x06values\x18\x01 \x03(\bR\x06values\"\x1e\n" +
	"\x04Ints\x12\x16\n" +
	"\x06values\x18\x01 \x03(\x05R\x06values\"\x1f\n" +
	"\x05Longs\x12\x16\n" +
	"\x06values\x18\x01 \x03(\x03R\x06values\" \n" +
	"\x06Floats\x12\x16\n" +
	"\x06values\x18\x01 \x03(\x02R\x06values\"!\n" +
	"\aDoubles\x12\x16\n" +
	"\x06values\x18\x01 \x03(\x01R\x06values\"!\n" +
	"\aStrings\x12\x16\n" +
	"\x06values\x18\x01 \x03(\tR\x06valuesB6\n" +
	"\x1eorg.apache.spark.connect.protoP\x01Z\x12internal/generatedb\x06proto3"

var (
	file_spark_connect_common_proto_rawDescOnce sync.Once
	file_spark_connect_common_proto_rawDescData []byte
)

func file_spark_connect_common_proto_rawDescGZIP() []byte {
	file_spark_connect_common_proto_rawDescOnce.Do(func() {
		file_spark_connect_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_spark_connect_common_proto_rawDesc), len(file_spark_connect_common_proto_rawDesc)))
	})
	return file_spark_connect_common_proto_rawDescData
}

var file_spark_connect_common_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_spark_connect_common_proto_goTypes = []any{
	(*StorageLevel)(nil),            // 0: spark.connect.StorageLevel
	(*ResourceInformation)(nil),     // 1: spark.connect.ResourceInformation
	(*ExecutorResourceRequest)(nil), // 2: spark.connect.ExecutorResourceRequest
	(*TaskResourceRequest)(nil),     // 3: spark.connect.TaskResourceRequest
	(*ResourceProfile)(nil),         // 4: spark.connect.ResourceProfile
	(*Origin)(nil),                  // 5: spark.connect.Origin
	(*PythonOrigin)(nil),            // 6: spark.connect.PythonOrigin
	(*JvmOrigin)(nil),               // 7: spark.connect.JvmOrigin
	(*StackTraceElement)(nil),       // 8: spark.connect.StackTraceElement
	(*ResolvedIdentifier)(nil),      // 9: spark.connect.ResolvedIdentifier
	(*Bools)(nil),                   // 10: spark.connect.Bools
	(*Ints)(nil),                    // 11: spark.connect.Ints
	(*Longs)(nil),                   // 12: spark.connect.Longs
	(*Floats)(nil),                  // 13: spark.connect.Floats
	(*Doubles)(nil),                 // 14: spark.connect.Doubles
	(*Strings)(nil),                 // 15: spark.connect.Strings
	nil,                             // 16: spark.connect.ResourceProfile.ExecutorResourcesEntry
	nil,                             // 17: spark.connect.ResourceProfile.TaskResourcesEntry
}
var file_spark_connect_common_proto_depIdxs = []int32{
	16, // 0: spark.connect.ResourceProfile.executor_resources:type_name -> spark.connect.ResourceProfile.ExecutorResourcesEntry
	17, // 1: spark.connect.ResourceProfile.task_resources:type_name -> spark.connect.ResourceProfile.TaskResourcesEntry
	6,  // 2: spark.connect.Origin.python_origin:type_name -> spark.connect.PythonOrigin
	7,  // 3: spark.connect.Origin.jvm_origin:type_name -> spark.connect.JvmOrigin
	8,  // 4: spark.connect.JvmOrigin.stack_trace:type_name -> spark.connect.StackTraceElement
	2,  // 5: spark.connect.ResourceProfile.ExecutorResourcesEntry.value:type_name -> spark.connect.ExecutorResourceRequest
	3,  // 6: spark.connect.ResourceProfile.TaskResourcesEntry.value:type_name -> spark.connect.TaskResourceRequest
	7,  // [7:7] is the sub-list for method output_type
	7,  // [7:7] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_spark_connect_common_proto_init() }
func file_spark_connect_common_proto_init() {
	if File_spark_connect_common_proto != nil {
		return
	}
	file_spark_connect_common_proto_msgTypes[2].OneofWrappers = []any{}
	file_spark_connect_common_proto_msgTypes[5].OneofWrappers = []any{
		(*Origin_PythonOrigin)(nil),
		(*Origin_JvmOrigin)(nil),
	}
	file_spark_connect_common_proto_msgTypes[7].OneofWrappers = []any{}
	file_spark_connect_common_proto_msgTypes[8].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_spark_connect_common_proto_rawDesc), len(file_spark_connect_common_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_spark_connect_common_proto_goTypes,
		DependencyIndexes: file_spark_connect_common_proto_depIdxs,
		MessageInfos:      file_spark_connect_common_proto_msgTypes,
	}.Build()
	File_spark_connect_common_proto = out.File
	file_spark_connect_common_proto_goTypes = nil
	file_spark_connect_common_proto_depIdxs = nil
}
