//
// Licensed to the Apache Software Foundation (ASF) under one or more
// contributor license agreements.  See the NOTICE file distributed with
// this work for additional information regarding copyright ownership.
// The ASF licenses this file to You under the Apache License, Version 2.0
// (the "License"); you may not use this file except in compliance with
// the License.  You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: spark/connect/example_plugins.proto

package generated

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExamplePluginRelation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Input         *Relation              `protobuf:"bytes,1,opt,name=input,proto3" json:"input,omitempty"`
	CustomField   string                 `protobuf:"bytes,2,opt,name=custom_field,json=customField,proto3" json:"custom_field,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExamplePluginRelation) Reset() {
	*x = ExamplePluginRelation{}
	mi := &file_spark_connect_example_plugins_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExamplePluginRelation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExamplePluginRelation) ProtoMessage() {}

func (x *ExamplePluginRelation) ProtoReflect() protoreflect.Message {
	mi := &file_spark_connect_example_plugins_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExamplePluginRelation.ProtoReflect.Descriptor instead.
func (*ExamplePluginRelation) Descriptor() ([]byte, []int) {
	return file_spark_connect_example_plugins_proto_rawDescGZIP(), []int{0}
}

func (x *ExamplePluginRelation) GetInput() *Relation {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *ExamplePluginRelation) GetCustomField() string {
	if x != nil {
		return x.CustomField
	}
	return ""
}

type ExamplePluginExpression struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Child         *Expression            `protobuf:"bytes,1,opt,name=child,proto3" json:"child,omitempty"`
	CustomField   string                 `protobuf:"bytes,2,opt,name=custom_field,json=customField,proto3" json:"custom_field,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExamplePluginExpression) Reset() {
	*x = ExamplePluginExpression{}
	mi := &file_spark_connect_example_plugins_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExamplePluginExpression) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExamplePluginExpression) ProtoMessage() {}

func (x *ExamplePluginExpression) ProtoReflect() protoreflect.Message {
	mi := &file_spark_connect_example_plugins_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExamplePluginExpression.ProtoReflect.Descriptor instead.
func (*ExamplePluginExpression) Descriptor() ([]byte, []int) {
	return file_spark_connect_example_plugins_proto_rawDescGZIP(), []int{1}
}

func (x *ExamplePluginExpression) GetChild() *Expression {
	if x != nil {
		return x.Child
	}
	return nil
}

func (x *ExamplePluginExpression) GetCustomField() string {
	if x != nil {
		return x.CustomField
	}
	return ""
}

type ExamplePluginCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CustomField   string                 `protobuf:"bytes,1,opt,name=custom_field,json=customField,proto3" json:"custom_field,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExamplePluginCommand) Reset() {
	*x = ExamplePluginCommand{}
	mi := &file_spark_connect_example_plugins_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExamplePluginCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExamplePluginCommand) ProtoMessage() {}

func (x *ExamplePluginCommand) ProtoReflect() protoreflect.Message {
	mi := &file_spark_connect_example_plugins_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExamplePluginCommand.ProtoReflect.Descriptor instead.
func (*ExamplePluginCommand) Descriptor() ([]byte, []int) {
	return file_spark_connect_example_plugins_proto_rawDescGZIP(), []int{2}
}

func (x *ExamplePluginCommand) GetCustomField() string {
	if x != nil {
		return x.CustomField
	}
	return ""
}

var File_spark_connect_example_plugins_proto protoreflect.FileDescriptor

const file_spark_connect_example_plugins_proto_rawDesc = "" +
	"\n" +
	"#spark/connect/example_plugins.proto\x12\rspark.connect\x1a\x1dspark/connect/relations.proto\x1a\x1fspark/connect/expressions.proto\"i\n" +
	"\x15ExamplePluginRelation\x12-\n" +
	"\x05input\x18\x01 \x01(\v2\x17.spark.connect.RelationR\x05input\x12!\n" +
	"\fcustom_field\x18\x02 \x01(\tR\vcustomField\"m\n" +
	"\x17ExamplePluginExpression\x12/\n" +
	"\x05child\x18\x01 \x01(\v2\x19.spark.connect.ExpressionR\x05child\x12!\n" +
	"\fcustom_field\x18\x02 \x01(\tR\vcustomField\"9\n" +
	"\x14ExamplePluginCommand\x12!\n" +
	"\fcustom_field\x18\x01 \x01(\tR\vcustomFieldB6\n" +
	"\x1eorg.apache.spark.connect.protoP\x01Z\x12internal/generatedb\x06proto3"

var (
	file_spark_connect_example_plugins_proto_rawDescOnce sync.Once
	file_spark_connect_example_plugins_proto_rawDescData []byte
)

func file_spark_connect_example_plugins_proto_rawDescGZIP() []byte {
	file_spark_connect_example_plugins_proto_rawDescOnce.Do(func() {
		file_spark_connect_example_plugins_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_spark_connect_example_plugins_proto_rawDesc), len(file_spark_connect_example_plugins_proto_rawDesc)))
	})
	return file_spark_connect_example_plugins_proto_rawDescData
}

var file_spark_connect_example_plugins_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_spark_connect_example_plugins_proto_goTypes = []any{
	(*ExamplePluginRelation)(nil),   // 0: spark.connect.ExamplePluginRelation
	(*ExamplePluginExpression)(nil), // 1: spark.connect.ExamplePluginExpression
	(*ExamplePluginCommand)(nil),    // 2: spark.connect.ExamplePluginCommand
	(*Relation)(nil),                // 3: spark.connect.Relation
	(*Expression)(nil),              // 4: spark.connect.Expression
}
var file_spark_connect_example_plugins_proto_depIdxs = []int32{
	3, // 0: spark.connect.ExamplePluginRelation.input:type_name -> spark.connect.Relation
	4, // 1: spark.connect.ExamplePluginExpression.child:type_name -> spark.connect.Expression
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_spark_connect_example_plugins_proto_init() }
func file_spark_connect_example_plugins_proto_init() {
	if File_spark_connect_example_plugins_proto != nil {
		return
	}
	file_spark_connect_relations_proto_init()
	file_spark_connect_expressions_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_spark_connect_example_plugins_proto_rawDesc), len(file_spark_connect_example_plugins_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_spark_connect_example_plugins_proto_goTypes,
		DependencyIndexes: file_spark_connect_example_plugins_proto_depIdxs,
		MessageInfos:      file_spark_connect_example_plugins_proto_msgTypes,
	}.Build()
	File_spark_connect_example_plugins_proto = out.File
	file_spark_connect_example_plugins_proto_goTypes = nil
	file_spark_connect_example_plugins_proto_depIdxs = nil
}
