//
// Licensed to the Apache Software Foundation (ASF) under one or more
// contributor license agreements.  See the NOTICE file distributed with
// this work for additional information regarding copyright ownership.
// The ASF licenses this file to You under the Apache License, Version 2.0
// (the "License"); you may not use this file except in compliance with
// the License.  You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: spark/connect/ml.proto

package generated

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Command for ML
type MlCommand struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Command:
	//
	//	*MlCommand_Fit_
	//	*MlCommand_Fetch
	//	*MlCommand_Delete_
	//	*MlCommand_Write_
	//	*MlCommand_Read_
	//	*MlCommand_Evaluate_
	//	*MlCommand_CleanCache_
	//	*MlCommand_GetCacheInfo_
	//	*MlCommand_CreateSummary_
	//	*MlCommand_GetModelSize_
	Command       isMlCommand_Command `protobuf_oneof:"command"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MlCommand) Reset() {
	*x = MlCommand{}
	mi := &file_spark_connect_ml_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MlCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MlCommand) ProtoMessage() {}

func (x *MlCommand) ProtoReflect() protoreflect.Message {
	mi := &file_spark_connect_ml_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MlCommand.ProtoReflect.Descriptor instead.
func (*MlCommand) Descriptor() ([]byte, []int) {
	return file_spark_connect_ml_proto_rawDescGZIP(), []int{0}
}

func (x *MlCommand) GetCommand() isMlCommand_Command {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *MlCommand) GetFit() *MlCommand_Fit {
	if x != nil {
		if x, ok := x.Command.(*MlCommand_Fit_); ok {
			return x.Fit
		}
	}
	return nil
}

func (x *MlCommand) GetFetch() *Fetch {
	if x != nil {
		if x, ok := x.Command.(*MlCommand_Fetch); ok {
			return x.Fetch
		}
	}
	return nil
}

func (x *MlCommand) GetDelete() *MlCommand_Delete {
	if x != nil {
		if x, ok := x.Command.(*MlCommand_Delete_); ok {
			return x.Delete
		}
	}
	return nil
}

func (x *MlCommand) GetWrite() *MlCommand_Write {
	if x != nil {
		if x, ok := x.Command.(*MlCommand_Write_); ok {
			return x.Write
		}
	}
	return nil
}

func (x *MlCommand) GetRead() *MlCommand_Read {
	if x != nil {
		if x, ok := x.Command.(*MlCommand_Read_); ok {
			return x.Read
		}
	}
	return nil
}

func (x *MlCommand) GetEvaluate() *MlCommand_Evaluate {
	if x != nil {
		if x, ok := x.Command.(*MlCommand_Evaluate_); ok {
			return x.Evaluate
		}
	}
	return nil
}

func (x *MlCommand) GetCleanCache() *MlCommand_CleanCache {
	if x != nil {
		if x, ok := x.Command.(*MlCommand_CleanCache_); ok {
			return x.CleanCache
		}
	}
	return nil
}

func (x *MlCommand) GetGetCacheInfo() *MlCommand_GetCacheInfo {
	if x != nil {
		if x, ok := x.Command.(*MlCommand_GetCacheInfo_); ok {
			return x.GetCacheInfo
		}
	}
	return nil
}

func (x *MlCommand) GetCreateSummary() *MlCommand_CreateSummary {
	if x != nil {
		if x, ok := x.Command.(*MlCommand_CreateSummary_); ok {
			return x.CreateSummary
		}
	}
	return nil
}

func (x *MlCommand) GetGetModelSize() *MlCommand_GetModelSize {
	if x != nil {
		if x, ok := x.Command.(*MlCommand_GetModelSize_); ok {
			return x.GetModelSize
		}
	}
	return nil
}

type isMlCommand_Command interface {
	isMlCommand_Command()
}

type MlCommand_Fit_ struct {
	Fit *MlCommand_Fit `protobuf:"bytes,1,opt,name=fit,proto3,oneof"`
}

type MlCommand_Fetch struct {
	Fetch *Fetch `protobuf:"bytes,2,opt,name=fetch,proto3,oneof"`
}

type MlCommand_Delete_ struct {
	Delete *MlCommand_Delete `protobuf:"bytes,3,opt,name=delete,proto3,oneof"`
}

type MlCommand_Write_ struct {
	Write *MlCommand_Write `protobuf:"bytes,4,opt,name=write,proto3,oneof"`
}

type MlCommand_Read_ struct {
	Read *MlCommand_Read `protobuf:"bytes,5,opt,name=read,proto3,oneof"`
}

type MlCommand_Evaluate_ struct {
	Evaluate *MlCommand_Evaluate `protobuf:"bytes,6,opt,name=evaluate,proto3,oneof"`
}

type MlCommand_CleanCache_ struct {
	CleanCache *MlCommand_CleanCache `protobuf:"bytes,7,opt,name=clean_cache,json=cleanCache,proto3,oneof"`
}

type MlCommand_GetCacheInfo_ struct {
	GetCacheInfo *MlCommand_GetCacheInfo `protobuf:"bytes,8,opt,name=get_cache_info,json=getCacheInfo,proto3,oneof"`
}

type MlCommand_CreateSummary_ struct {
	CreateSummary *MlCommand_CreateSummary `protobuf:"bytes,9,opt,name=create_summary,json=createSummary,proto3,oneof"`
}

type MlCommand_GetModelSize_ struct {
	GetModelSize *MlCommand_GetModelSize `protobuf:"bytes,10,opt,name=get_model_size,json=getModelSize,proto3,oneof"`
}

func (*MlCommand_Fit_) isMlCommand_Command() {}

func (*MlCommand_Fetch) isMlCommand_Command() {}

func (*MlCommand_Delete_) isMlCommand_Command() {}

func (*MlCommand_Write_) isMlCommand_Command() {}

func (*MlCommand_Read_) isMlCommand_Command() {}

func (*MlCommand_Evaluate_) isMlCommand_Command() {}

func (*MlCommand_CleanCache_) isMlCommand_Command() {}

func (*MlCommand_GetCacheInfo_) isMlCommand_Command() {}

func (*MlCommand_CreateSummary_) isMlCommand_Command() {}

func (*MlCommand_GetModelSize_) isMlCommand_Command() {}

// The result of MlCommand
type MlCommandResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to ResultType:
	//
	//	*MlCommandResult_Param
	//	*MlCommandResult_Summary
	//	*MlCommandResult_OperatorInfo
	ResultType    isMlCommandResult_ResultType `protobuf_oneof:"result_type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MlCommandResult) Reset() {
	*x = MlCommandResult{}
	mi := &file_spark_connect_ml_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MlCommandResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MlCommandResult) ProtoMessage() {}

func (x *MlCommandResult) ProtoReflect() protoreflect.Message {
	mi := &file_spark_connect_ml_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MlCommandResult.ProtoReflect.Descriptor instead.
func (*MlCommandResult) Descriptor() ([]byte, []int) {
	return file_spark_connect_ml_proto_rawDescGZIP(), []int{1}
}

func (x *MlCommandResult) GetResultType() isMlCommandResult_ResultType {
	if x != nil {
		return x.ResultType
	}
	return nil
}

func (x *MlCommandResult) GetParam() *Expression_Literal {
	if x != nil {
		if x, ok := x.ResultType.(*MlCommandResult_Param); ok {
			return x.Param
		}
	}
	return nil
}

func (x *MlCommandResult) GetSummary() string {
	if x != nil {
		if x, ok := x.ResultType.(*MlCommandResult_Summary); ok {
			return x.Summary
		}
	}
	return ""
}

func (x *MlCommandResult) GetOperatorInfo() *MlCommandResult_MlOperatorInfo {
	if x != nil {
		if x, ok := x.ResultType.(*MlCommandResult_OperatorInfo); ok {
			return x.OperatorInfo
		}
	}
	return nil
}

type isMlCommandResult_ResultType interface {
	isMlCommandResult_ResultType()
}

type MlCommandResult_Param struct {
	// The result of the attribute
	Param *Expression_Literal `protobuf:"bytes,1,opt,name=param,proto3,oneof"`
}

type MlCommandResult_Summary struct {
	// Evaluate a Dataset in a model and return the cached ID of summary
	Summary string `protobuf:"bytes,2,opt,name=summary,proto3,oneof"`
}

type MlCommandResult_OperatorInfo struct {
	// Operator information
	OperatorInfo *MlCommandResult_MlOperatorInfo `protobuf:"bytes,3,opt,name=operator_info,json=operatorInfo,proto3,oneof"`
}

func (*MlCommandResult_Param) isMlCommandResult_ResultType() {}

func (*MlCommandResult_Summary) isMlCommandResult_ResultType() {}

func (*MlCommandResult_OperatorInfo) isMlCommandResult_ResultType() {}

// Command for estimator.fit(dataset)
type MlCommand_Fit struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// (Required) Estimator information (its type should be OPERATOR_TYPE_ESTIMATOR)
	Estimator *MlOperator `protobuf:"bytes,1,opt,name=estimator,proto3" json:"estimator,omitempty"`
	// (Optional) parameters of the Estimator
	Params *MlParams `protobuf:"bytes,2,opt,name=params,proto3,oneof" json:"params,omitempty"`
	// (Required) the training dataset
	Dataset       *Relation `protobuf:"bytes,3,opt,name=dataset,proto3" json:"dataset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MlCommand_Fit) Reset() {
	*x = MlCommand_Fit{}
	mi := &file_spark_connect_ml_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MlCommand_Fit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MlCommand_Fit) ProtoMessage() {}

func (x *MlCommand_Fit) ProtoReflect() protoreflect.Message {
	mi := &file_spark_connect_ml_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MlCommand_Fit.ProtoReflect.Descriptor instead.
func (*MlCommand_Fit) Descriptor() ([]byte, []int) {
	return file_spark_connect_ml_proto_rawDescGZIP(), []int{0, 0}
}

func (x *MlCommand_Fit) GetEstimator() *MlOperator {
	if x != nil {
		return x.Estimator
	}
	return nil
}

func (x *MlCommand_Fit) GetParams() *MlParams {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *MlCommand_Fit) GetDataset() *Relation {
	if x != nil {
		return x.Dataset
	}
	return nil
}

// Command to delete the cached objects which could be a model
// or summary evaluated by a model
type MlCommand_Delete struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	ObjRefs []*ObjectRef           `protobuf:"bytes,1,rep,name=obj_refs,json=objRefs,proto3" json:"obj_refs,omitempty"`
	// if set `evict_only` to true, only evict the cached model from memory,
	// but keep the offloaded model in Spark driver local disk.
	EvictOnly     *bool `protobuf:"varint,2,opt,name=evict_only,json=evictOnly,proto3,oneof" json:"evict_only,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MlCommand_Delete) Reset() {
	*x = MlCommand_Delete{}
	mi := &file_spark_connect_ml_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MlCommand_Delete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MlCommand_Delete) ProtoMessage() {}

func (x *MlCommand_Delete) ProtoReflect() protoreflect.Message {
	mi := &file_spark_connect_ml_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MlCommand_Delete.ProtoReflect.Descriptor instead.
func (*MlCommand_Delete) Descriptor() ([]byte, []int) {
	return file_spark_connect_ml_proto_rawDescGZIP(), []int{0, 1}
}

func (x *MlCommand_Delete) GetObjRefs() []*ObjectRef {
	if x != nil {
		return x.ObjRefs
	}
	return nil
}

func (x *MlCommand_Delete) GetEvictOnly() bool {
	if x != nil && x.EvictOnly != nil {
		return *x.EvictOnly
	}
	return false
}

// Force to clean up all the ML cached objects
type MlCommand_CleanCache struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MlCommand_CleanCache) Reset() {
	*x = MlCommand_CleanCache{}
	mi := &file_spark_connect_ml_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MlCommand_CleanCache) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MlCommand_CleanCache) ProtoMessage() {}

func (x *MlCommand_CleanCache) ProtoReflect() protoreflect.Message {
	mi := &file_spark_connect_ml_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MlCommand_CleanCache.ProtoReflect.Descriptor instead.
func (*MlCommand_CleanCache) Descriptor() ([]byte, []int) {
	return file_spark_connect_ml_proto_rawDescGZIP(), []int{0, 2}
}

// Get the information of all the ML cached objects
type MlCommand_GetCacheInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MlCommand_GetCacheInfo) Reset() {
	*x = MlCommand_GetCacheInfo{}
	mi := &file_spark_connect_ml_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MlCommand_GetCacheInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MlCommand_GetCacheInfo) ProtoMessage() {}

func (x *MlCommand_GetCacheInfo) ProtoReflect() protoreflect.Message {
	mi := &file_spark_connect_ml_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MlCommand_GetCacheInfo.ProtoReflect.Descriptor instead.
func (*MlCommand_GetCacheInfo) Descriptor() ([]byte, []int) {
	return file_spark_connect_ml_proto_rawDescGZIP(), []int{0, 3}
}

// Command to write ML operator
type MlCommand_Write struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// It could be an estimator/evaluator or the cached model
	//
	// Types that are valid to be assigned to Type:
	//
	//	*MlCommand_Write_Operator
	//	*MlCommand_Write_ObjRef
	Type isMlCommand_Write_Type `protobuf_oneof:"type"`
	// (Optional) The parameters of operator which could be estimator/evaluator or a cached model
	Params *MlParams `protobuf:"bytes,3,opt,name=params,proto3,oneof" json:"params,omitempty"`
	// (Required) Save the ML instance to the path
	Path string `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
	// (Optional) Overwrites if the output path already exists.
	ShouldOverwrite *bool `protobuf:"varint,5,opt,name=should_overwrite,json=shouldOverwrite,proto3,oneof" json:"should_overwrite,omitempty"`
	// (Optional) The options of the writer
	Options       map[string]string `protobuf:"bytes,6,rep,name=options,proto3" json:"options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MlCommand_Write) Reset() {
	*x = MlCommand_Write{}
	mi := &file_spark_connect_ml_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MlCommand_Write) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MlCommand_Write) ProtoMessage() {}

func (x *MlCommand_Write) ProtoReflect() protoreflect.Message {
	mi := &file_spark_connect_ml_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MlCommand_Write.ProtoReflect.Descriptor instead.
func (*MlCommand_Write) Descriptor() ([]byte, []int) {
	return file_spark_connect_ml_proto_rawDescGZIP(), []int{0, 4}
}

func (x *MlCommand_Write) GetType() isMlCommand_Write_Type {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *MlCommand_Write) GetOperator() *MlOperator {
	if x != nil {
		if x, ok := x.Type.(*MlCommand_Write_Operator); ok {
			return x.Operator
		}
	}
	return nil
}

func (x *MlCommand_Write) GetObjRef() *ObjectRef {
	if x != nil {
		if x, ok := x.Type.(*MlCommand_Write_ObjRef); ok {
			return x.ObjRef
		}
	}
	return nil
}

func (x *MlCommand_Write) GetParams() *MlParams {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *MlCommand_Write) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *MlCommand_Write) GetShouldOverwrite() bool {
	if x != nil && x.ShouldOverwrite != nil {
		return *x.ShouldOverwrite
	}
	return false
}

func (x *MlCommand_Write) GetOptions() map[string]string {
	if x != nil {
		return x.Options
	}
	return nil
}

type isMlCommand_Write_Type interface {
	isMlCommand_Write_Type()
}

type MlCommand_Write_Operator struct {
	// Estimator or evaluator
	Operator *MlOperator `protobuf:"bytes,1,opt,name=operator,proto3,oneof"`
}

type MlCommand_Write_ObjRef struct {
	// The cached model
	ObjRef *ObjectRef `protobuf:"bytes,2,opt,name=obj_ref,json=objRef,proto3,oneof"`
}

func (*MlCommand_Write_Operator) isMlCommand_Write_Type() {}

func (*MlCommand_Write_ObjRef) isMlCommand_Write_Type() {}

// Command to load ML operator.
type MlCommand_Read struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// (Required) ML operator information
	Operator *MlOperator `protobuf:"bytes,1,opt,name=operator,proto3" json:"operator,omitempty"`
	// (Required) Load the ML instance from the input path
	Path          string `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MlCommand_Read) Reset() {
	*x = MlCommand_Read{}
	mi := &file_spark_connect_ml_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MlCommand_Read) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MlCommand_Read) ProtoMessage() {}

func (x *MlCommand_Read) ProtoReflect() protoreflect.Message {
	mi := &file_spark_connect_ml_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MlCommand_Read.ProtoReflect.Descriptor instead.
func (*MlCommand_Read) Descriptor() ([]byte, []int) {
	return file_spark_connect_ml_proto_rawDescGZIP(), []int{0, 5}
}

func (x *MlCommand_Read) GetOperator() *MlOperator {
	if x != nil {
		return x.Operator
	}
	return nil
}

func (x *MlCommand_Read) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

// Command for evaluator.evaluate(dataset)
type MlCommand_Evaluate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// (Required) Evaluator information (its type should be OPERATOR_TYPE_EVALUATOR)
	Evaluator *MlOperator `protobuf:"bytes,1,opt,name=evaluator,proto3" json:"evaluator,omitempty"`
	// (Optional) parameters of the Evaluator
	Params *MlParams `protobuf:"bytes,2,opt,name=params,proto3,oneof" json:"params,omitempty"`
	// (Required) the evaluating dataset
	Dataset       *Relation `protobuf:"bytes,3,opt,name=dataset,proto3" json:"dataset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MlCommand_Evaluate) Reset() {
	*x = MlCommand_Evaluate{}
	mi := &file_spark_connect_ml_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MlCommand_Evaluate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MlCommand_Evaluate) ProtoMessage() {}

func (x *MlCommand_Evaluate) ProtoReflect() protoreflect.Message {
	mi := &file_spark_connect_ml_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MlCommand_Evaluate.ProtoReflect.Descriptor instead.
func (*MlCommand_Evaluate) Descriptor() ([]byte, []int) {
	return file_spark_connect_ml_proto_rawDescGZIP(), []int{0, 6}
}

func (x *MlCommand_Evaluate) GetEvaluator() *MlOperator {
	if x != nil {
		return x.Evaluator
	}
	return nil
}

func (x *MlCommand_Evaluate) GetParams() *MlParams {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *MlCommand_Evaluate) GetDataset() *Relation {
	if x != nil {
		return x.Dataset
	}
	return nil
}

// This is for re-creating the model summary when the model summary is lost
// (model summary is lost when the model is offloaded and then loaded back)
type MlCommand_CreateSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModelRef      *ObjectRef             `protobuf:"bytes,1,opt,name=model_ref,json=modelRef,proto3" json:"model_ref,omitempty"`
	Dataset       *Relation              `protobuf:"bytes,2,opt,name=dataset,proto3" json:"dataset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MlCommand_CreateSummary) Reset() {
	*x = MlCommand_CreateSummary{}
	mi := &file_spark_connect_ml_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MlCommand_CreateSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MlCommand_CreateSummary) ProtoMessage() {}

func (x *MlCommand_CreateSummary) ProtoReflect() protoreflect.Message {
	mi := &file_spark_connect_ml_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MlCommand_CreateSummary.ProtoReflect.Descriptor instead.
func (*MlCommand_CreateSummary) Descriptor() ([]byte, []int) {
	return file_spark_connect_ml_proto_rawDescGZIP(), []int{0, 7}
}

func (x *MlCommand_CreateSummary) GetModelRef() *ObjectRef {
	if x != nil {
		return x.ModelRef
	}
	return nil
}

func (x *MlCommand_CreateSummary) GetDataset() *Relation {
	if x != nil {
		return x.Dataset
	}
	return nil
}

// This is for query the model estimated in-memory size
type MlCommand_GetModelSize struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModelRef      *ObjectRef             `protobuf:"bytes,1,opt,name=model_ref,json=modelRef,proto3" json:"model_ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MlCommand_GetModelSize) Reset() {
	*x = MlCommand_GetModelSize{}
	mi := &file_spark_connect_ml_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MlCommand_GetModelSize) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MlCommand_GetModelSize) ProtoMessage() {}

func (x *MlCommand_GetModelSize) ProtoReflect() protoreflect.Message {
	mi := &file_spark_connect_ml_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MlCommand_GetModelSize.ProtoReflect.Descriptor instead.
func (*MlCommand_GetModelSize) Descriptor() ([]byte, []int) {
	return file_spark_connect_ml_proto_rawDescGZIP(), []int{0, 8}
}

func (x *MlCommand_GetModelSize) GetModelRef() *ObjectRef {
	if x != nil {
		return x.ModelRef
	}
	return nil
}

// Represents an operator info
type MlCommandResult_MlOperatorInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Type:
	//
	//	*MlCommandResult_MlOperatorInfo_ObjRef
	//	*MlCommandResult_MlOperatorInfo_Name
	Type isMlCommandResult_MlOperatorInfo_Type `protobuf_oneof:"type"`
	// (Optional) the 'uid' of a ML object
	// Note it is different from the 'id' of a cached object.
	Uid *string `protobuf:"bytes,3,opt,name=uid,proto3,oneof" json:"uid,omitempty"`
	// (Optional) parameters
	Params *MlParams `protobuf:"bytes,4,opt,name=params,proto3,oneof" json:"params,omitempty"`
	// (Optional) warning message generated during the ML command execution
	WarningMessage *string `protobuf:"bytes,5,opt,name=warning_message,json=warningMessage,proto3,oneof" json:"warning_message,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MlCommandResult_MlOperatorInfo) Reset() {
	*x = MlCommandResult_MlOperatorInfo{}
	mi := &file_spark_connect_ml_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MlCommandResult_MlOperatorInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MlCommandResult_MlOperatorInfo) ProtoMessage() {}

func (x *MlCommandResult_MlOperatorInfo) ProtoReflect() protoreflect.Message {
	mi := &file_spark_connect_ml_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MlCommandResult_MlOperatorInfo.ProtoReflect.Descriptor instead.
func (*MlCommandResult_MlOperatorInfo) Descriptor() ([]byte, []int) {
	return file_spark_connect_ml_proto_rawDescGZIP(), []int{1, 0}
}

func (x *MlCommandResult_MlOperatorInfo) GetType() isMlCommandResult_MlOperatorInfo_Type {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *MlCommandResult_MlOperatorInfo) GetObjRef() *ObjectRef {
	if x != nil {
		if x, ok := x.Type.(*MlCommandResult_MlOperatorInfo_ObjRef); ok {
			return x.ObjRef
		}
	}
	return nil
}

func (x *MlCommandResult_MlOperatorInfo) GetName() string {
	if x != nil {
		if x, ok := x.Type.(*MlCommandResult_MlOperatorInfo_Name); ok {
			return x.Name
		}
	}
	return ""
}

func (x *MlCommandResult_MlOperatorInfo) GetUid() string {
	if x != nil && x.Uid != nil {
		return *x.Uid
	}
	return ""
}

func (x *MlCommandResult_MlOperatorInfo) GetParams() *MlParams {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *MlCommandResult_MlOperatorInfo) GetWarningMessage() string {
	if x != nil && x.WarningMessage != nil {
		return *x.WarningMessage
	}
	return ""
}

type isMlCommandResult_MlOperatorInfo_Type interface {
	isMlCommandResult_MlOperatorInfo_Type()
}

type MlCommandResult_MlOperatorInfo_ObjRef struct {
	// The cached object which could be a model or summary evaluated by a model
	ObjRef *ObjectRef `protobuf:"bytes,1,opt,name=obj_ref,json=objRef,proto3,oneof"`
}

type MlCommandResult_MlOperatorInfo_Name struct {
	// Operator name
	Name string `protobuf:"bytes,2,opt,name=name,proto3,oneof"`
}

func (*MlCommandResult_MlOperatorInfo_ObjRef) isMlCommandResult_MlOperatorInfo_Type() {}

func (*MlCommandResult_MlOperatorInfo_Name) isMlCommandResult_MlOperatorInfo_Type() {}

var File_spark_connect_ml_proto protoreflect.FileDescriptor

const file_spark_connect_ml_proto_rawDesc = "" +
	"\n" +
	"\x16spark/connect/ml.proto\x12\rspark.connect\x1a\x1dspark/connect/relations.proto\x1a\x1fspark/connect/expressions.proto\x1a\x1dspark/connect/ml_common.proto\"\xc7\x0e\n" +
	"\tMlCommand\x120\n" +
	"\x03fit\x18\x01 \x01(\v2\x1c.spark.connect.MlCommand.FitH\x00R\x03fit\x12,\n" +
	"\x05fetch\x18\x02 \x01(\v2\x14.spark.connect.FetchH\x00R\x05fetch\x129\n" +
	"\x06delete\x18\x03 \x01(\v2\x1f.spark.connect.MlCommand.DeleteH\x00R\x06delete\x126\n" +
	"\x05write\x18\x04 \x01(\v2\x1e.spark.connect.MlCommand.WriteH\x00R\x05write\x123\n" +
	"\x04read\x18\x05 \x01(\v2\x1d.spark.connect.MlCommand.ReadH\x00R\x04read\x12?\n" +
	"\bevaluate\x18\x06 \x01(\v2!.spark.connect.MlCommand.EvaluateH\x00R\bevaluate\x12F\n" +
	"\vclean_cache\x18\a \x01(\v2#.spark.connect.MlCommand.CleanCacheH\x00R\n" +
	"cleanCache\x12M\n" +
	"\x0eget_cache_info\x18\b \x01(\v2%.spark.connect.MlCommand.GetCacheInfoH\x00R\fgetCacheInfo\x12O\n" +
	"\x0ecreate_summary\x18\t \x01(\v2&.spark.connect.MlCommand.CreateSummaryH\x00R\rcreateSummary\x12M\n" +
	"\x0eget_model_size\x18\n" +
	" \x01(\v2%.spark.connect.MlCommand.GetModelSizeH\x00R\fgetModelSize\x1a\xb2\x01\n" +
	"\x03Fit\x127\n" +
	"\testimator\x18\x01 \x01(\v2\x19.spark.connect.MlOperatorR\testimator\x124\n" +
	"\x06params\x18\x02 \x01(\v2\x17.spark.connect.MlParamsH\x00R\x06params\x88\x01\x01\x121\n" +
	"\adataset\x18\x03 \x01(\v2\x17.spark.connect.RelationR\adatasetB\t\n" +
	"\a_params\x1ap\n" +
	"\x06Delete\x123\n" +
	"\bobj_refs\x18\x01 \x03(\v2\x18.spark.connect.ObjectRefR\aobjRefs\x12\"\n" +
	"\n" +
	"evict_only\x18\x02 \x01(\bH\x00R\tevictOnly\x88\x01\x01B\r\n" +
	"\v_evict_only\x1a\f\n" +
	"\n" +
	"CleanCache\x1a\x0e\n" +
	"\fGetCacheInfo\x1a\x9a\x03\n" +
	"\x05Write\x127\n" +
	"\boperator\x18\x01 \x01(\v2\x19.spark.connect.MlOperatorH\x00R\boperator\x123\n" +
	"\aobj_ref\x18\x02 \x01(\v2\x18.spark.connect.ObjectRefH\x00R\x06objRef\x124\n" +
	"\x06params\x18\x03 \x01(\v2\x17.spark.connect.MlParamsH\x01R\x06params\x88\x01\x01\x12\x12\n" +
	"\x04path\x18\x04 \x01(\tR\x04path\x12.\n" +
	"\x10should_overwrite\x18\x05 \x01(\bH\x02R\x0fshouldOverwrite\x88\x01\x01\x12E\n" +
	"\aoptions\x18\x06 \x03(\v2+.spark.connect.MlCommand.Write.OptionsEntryR\aoptions\x1a:\n" +
	"\fOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x06\n" +
	"\x04typeB\t\n" +
	"\a_paramsB\x13\n" +
	"\x11_should_overwrite\x1aQ\n" +
	"\x04Read\x125\n" +
	"\boperator\x18\x01 \x01(\v2\x19.spark.connect.MlOperatorR\boperator\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x1a\xb7\x01\n" +
	"\bEvaluate\x127\n" +
	"\tevaluator\x18\x01 \x01(\v2\x19.spark.connect.MlOperatorR\tevaluator\x124\n" +
	"\x06params\x18\x02 \x01(\v2\x17.spark.connect.MlParamsH\x00R\x06params\x88\x01\x01\x121\n" +
	"\adataset\x18\x03 \x01(\v2\x17.spark.connect.RelationR\adatasetB\t\n" +
	"\a_params\x1ay\n" +
	"\rCreateSummary\x125\n" +
	"\tmodel_ref\x18\x01 \x01(\v2\x18.spark.connect.ObjectRefR\bmodelRef\x121\n" +
	"\adataset\x18\x02 \x01(\v2\x17.spark.connect.RelationR\adataset\x1aE\n" +
	"\fGetModelSize\x125\n" +
	"\tmodel_ref\x18\x01 \x01(\v2\x18.spark.connect.ObjectRefR\bmodelRefB\t\n" +
	"\acommand\"\xd5\x03\n" +
	"\x0fMlCommandResult\x129\n" +
	"\x05param\x18\x01 \x01(\v2!.spark.connect.Expression.LiteralH\x00R\x05param\x12\x1a\n" +
	"\asummary\x18\x02 \x01(\tH\x00R\asummary\x12T\n" +
	"\roperator_info\x18\x03 \x01(\v2-.spark.connect.MlCommandResult.MlOperatorInfoH\x00R\foperatorInfo\x1a\x85\x02\n" +
	"\x0eMlOperatorInfo\x123\n" +
	"\aobj_ref\x18\x01 \x01(\v2\x18.spark.connect.ObjectRefH\x00R\x06objRef\x12\x14\n" +
	"\x04name\x18\x02 \x01(\tH\x00R\x04name\x12\x15\n" +
	"\x03uid\x18\x03 \x01(\tH\x01R\x03uid\x88\x01\x01\x124\n" +
	"\x06params\x18\x04 \x01(\v2\x17.spark.connect.MlParamsH\x02R\x06params\x88\x01\x01\x12,\n" +
	"\x0fwarning_message\x18\x05 \x01(\tH\x03R\x0ewarningMessage\x88\x01\x01B\x06\n" +
	"\x04typeB\x06\n" +
	"\x04_uidB\t\n" +
	"\a_paramsB\x12\n" +
	"\x10_warning_messageB\r\n" +
	"\vresult_typeB6\n" +
	"\x1eorg.apache.spark.connect.protoP\x01Z\x12internal/generatedb\x06proto3"

var (
	file_spark_connect_ml_proto_rawDescOnce sync.Once
	file_spark_connect_ml_proto_rawDescData []byte
)

func file_spark_connect_ml_proto_rawDescGZIP() []byte {
	file_spark_connect_ml_proto_rawDescOnce.Do(func() {
		file_spark_connect_ml_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_spark_connect_ml_proto_rawDesc), len(file_spark_connect_ml_proto_rawDesc)))
	})
	return file_spark_connect_ml_proto_rawDescData
}

var file_spark_connect_ml_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_spark_connect_ml_proto_goTypes = []any{
	(*MlCommand)(nil),                      // 0: spark.connect.MlCommand
	(*MlCommandResult)(nil),                // 1: spark.connect.MlCommandResult
	(*MlCommand_Fit)(nil),                  // 2: spark.connect.MlCommand.Fit
	(*MlCommand_Delete)(nil),               // 3: spark.connect.MlCommand.Delete
	(*MlCommand_CleanCache)(nil),           // 4: spark.connect.MlCommand.CleanCache
	(*MlCommand_GetCacheInfo)(nil),         // 5: spark.connect.MlCommand.GetCacheInfo
	(*MlCommand_Write)(nil),                // 6: spark.connect.MlCommand.Write
	(*MlCommand_Read)(nil),                 // 7: spark.connect.MlCommand.Read
	(*MlCommand_Evaluate)(nil),             // 8: spark.connect.MlCommand.Evaluate
	(*MlCommand_CreateSummary)(nil),        // 9: spark.connect.MlCommand.CreateSummary
	(*MlCommand_GetModelSize)(nil),         // 10: spark.connect.MlCommand.GetModelSize
	nil,                                    // 11: spark.connect.MlCommand.Write.OptionsEntry
	(*MlCommandResult_MlOperatorInfo)(nil), // 12: spark.connect.MlCommandResult.MlOperatorInfo
	(*Fetch)(nil),                          // 13: spark.connect.Fetch
	(*Expression_Literal)(nil),             // 14: spark.connect.Expression.Literal
	(*MlOperator)(nil),                     // 15: spark.connect.MlOperator
	(*MlParams)(nil),                       // 16: spark.connect.MlParams
	(*Relation)(nil),                       // 17: spark.connect.Relation
	(*ObjectRef)(nil),                      // 18: spark.connect.ObjectRef
}
var file_spark_connect_ml_proto_depIdxs = []int32{
	2,  // 0: spark.connect.MlCommand.fit:type_name -> spark.connect.MlCommand.Fit
	13, // 1: spark.connect.MlCommand.fetch:type_name -> spark.connect.Fetch
	3,  // 2: spark.connect.MlCommand.delete:type_name -> spark.connect.MlCommand.Delete
	6,  // 3: spark.connect.MlCommand.write:type_name -> spark.connect.MlCommand.Write
	7,  // 4: spark.connect.MlCommand.read:type_name -> spark.connect.MlCommand.Read
	8,  // 5: spark.connect.MlCommand.evaluate:type_name -> spark.connect.MlCommand.Evaluate
	4,  // 6: spark.connect.MlCommand.clean_cache:type_name -> spark.connect.MlCommand.CleanCache
	5,  // 7: spark.connect.MlCommand.get_cache_info:type_name -> spark.connect.MlCommand.GetCacheInfo
	9,  // 8: spark.connect.MlCommand.create_summary:type_name -> spark.connect.MlCommand.CreateSummary
	10, // 9: spark.connect.MlCommand.get_model_size:type_name -> spark.connect.MlCommand.GetModelSize
	14, // 10: spark.connect.MlCommandResult.param:type_name -> spark.connect.Expression.Literal
	12, // 11: spark.connect.MlCommandResult.operator_info:type_name -> spark.connect.MlCommandResult.MlOperatorInfo
	15, // 12: spark.connect.MlCommand.Fit.estimator:type_name -> spark.connect.MlOperator
	16, // 13: spark.connect.MlCommand.Fit.params:type_name -> spark.connect.MlParams
	17, // 14: spark.connect.MlCommand.Fit.dataset:type_name -> spark.connect.Relation
	18, // 15: spark.connect.MlCommand.Delete.obj_refs:type_name -> spark.connect.ObjectRef
	15, // 16: spark.connect.MlCommand.Write.operator:type_name -> spark.connect.MlOperator
	18, // 17: spark.connect.MlCommand.Write.obj_ref:type_name -> spark.connect.ObjectRef
	16, // 18: spark.connect.MlCommand.Write.params:type_name -> spark.connect.MlParams
	11, // 19: spark.connect.MlCommand.Write.options:type_name -> spark.connect.MlCommand.Write.OptionsEntry
	15, // 20: spark.connect.MlCommand.Read.operator:type_name -> spark.connect.MlOperator
	15, // 21: spark.connect.MlCommand.Evaluate.evaluator:type_name -> spark.connect.MlOperator
	16, // 22: spark.connect.MlCommand.Evaluate.params:type_name -> spark.connect.MlParams
	17, // 23: spark.connect.MlCommand.Evaluate.dataset:type_name -> spark.connect.Relation
	18, // 24: spark.connect.MlCommand.CreateSummary.model_ref:type_name -> spark.connect.ObjectRef
	17, // 25: spark.connect.MlCommand.CreateSummary.dataset:type_name -> spark.connect.Relation
	18, // 26: spark.connect.MlCommand.GetModelSize.model_ref:type_name -> spark.connect.ObjectRef
	18, // 27: spark.connect.MlCommandResult.MlOperatorInfo.obj_ref:type_name -> spark.connect.ObjectRef
	16, // 28: spark.connect.MlCommandResult.MlOperatorInfo.params:type_name -> spark.connect.MlParams
	29, // [29:29] is the sub-list for method output_type
	29, // [29:29] is the sub-list for method input_type
	29, // [29:29] is the sub-list for extension type_name
	29, // [29:29] is the sub-list for extension extendee
	0,  // [0:29] is the sub-list for field type_name
}

func init() { file_spark_connect_ml_proto_init() }
func file_spark_connect_ml_proto_init() {
	if File_spark_connect_ml_proto != nil {
		return
	}
	file_spark_connect_relations_proto_init()
	file_spark_connect_expressions_proto_init()
	file_spark_connect_ml_common_proto_init()
	file_spark_connect_ml_proto_msgTypes[0].OneofWrappers = []any{
		(*MlCommand_Fit_)(nil),
		(*MlCommand_Fetch)(nil),
		(*MlCommand_Delete_)(nil),
		(*MlCommand_Write_)(nil),
		(*MlCommand_Read_)(nil),
		(*MlCommand_Evaluate_)(nil),
		(*MlCommand_CleanCache_)(nil),
		(*MlCommand_GetCacheInfo_)(nil),
		(*MlCommand_CreateSummary_)(nil),
		(*MlCommand_GetModelSize_)(nil),
	}
	file_spark_connect_ml_proto_msgTypes[1].OneofWrappers = []any{
		(*MlCommandResult_Param)(nil),
		(*MlCommandResult_Summary)(nil),
		(*MlCommandResult_OperatorInfo)(nil),
	}
	file_spark_connect_ml_proto_msgTypes[2].OneofWrappers = []any{}
	file_spark_connect_ml_proto_msgTypes[3].OneofWrappers = []any{}
	file_spark_connect_ml_proto_msgTypes[6].OneofWrappers = []any{
		(*MlCommand_Write_Operator)(nil),
		(*MlCommand_Write_ObjRef)(nil),
	}
	file_spark_connect_ml_proto_msgTypes[8].OneofWrappers = []any{}
	file_spark_connect_ml_proto_msgTypes[12].OneofWrappers = []any{
		(*MlCommandResult_MlOperatorInfo_ObjRef)(nil),
		(*MlCommandResult_MlOperatorInfo_Name)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_spark_connect_ml_proto_rawDesc), len(file_spark_connect_ml_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_spark_connect_ml_proto_goTypes,
		DependencyIndexes: file_spark_connect_ml_proto_depIdxs,
		MessageInfos:      file_spark_connect_ml_proto_msgTypes,
	}.Build()
	File_spark_connect_ml_proto = out.File
	file_spark_connect_ml_proto_goTypes = nil
	file_spark_connect_ml_proto_depIdxs = nil
}
