//
// Licensed to the Apache Software Foundation (ASF) under one or more
// contributor license agreements.  See the NOTICE file distributed with
// this work for additional information regarding copyright ownership.
// The ASF licenses this file to You under the Apache License, Version 2.0
// (the "License"); you may not use this file except in compliance with
// the License.  You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: spark/connect/ml_common.proto

package generated

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MlOperator_OperatorType int32

const (
	MlOperator_OPERATOR_TYPE_UNSPECIFIED MlOperator_OperatorType = 0
	// ML estimator
	MlOperator_OPERATOR_TYPE_ESTIMATOR MlOperator_OperatorType = 1
	// ML transformer (non-model)
	MlOperator_OPERATOR_TYPE_TRANSFORMER MlOperator_OperatorType = 2
	// ML evaluator
	MlOperator_OPERATOR_TYPE_EVALUATOR MlOperator_OperatorType = 3
	// ML model
	MlOperator_OPERATOR_TYPE_MODEL MlOperator_OperatorType = 4
)

// Enum value maps for MlOperator_OperatorType.
var (
	MlOperator_OperatorType_name = map[int32]string{
		0: "OPERATOR_TYPE_UNSPECIFIED",
		1: "OPERATOR_TYPE_ESTIMATOR",
		2: "OPERATOR_TYPE_TRANSFORMER",
		3: "OPERATOR_TYPE_EVALUATOR",
		4: "OPERATOR_TYPE_MODEL",
	}
	MlOperator_OperatorType_value = map[string]int32{
		"OPERATOR_TYPE_UNSPECIFIED": 0,
		"OPERATOR_TYPE_ESTIMATOR":   1,
		"OPERATOR_TYPE_TRANSFORMER": 2,
		"OPERATOR_TYPE_EVALUATOR":   3,
		"OPERATOR_TYPE_MODEL":       4,
	}
)

func (x MlOperator_OperatorType) Enum() *MlOperator_OperatorType {
	p := new(MlOperator_OperatorType)
	*p = x
	return p
}

func (x MlOperator_OperatorType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MlOperator_OperatorType) Descriptor() protoreflect.EnumDescriptor {
	return file_spark_connect_ml_common_proto_enumTypes[0].Descriptor()
}

func (MlOperator_OperatorType) Type() protoreflect.EnumType {
	return &file_spark_connect_ml_common_proto_enumTypes[0]
}

func (x MlOperator_OperatorType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MlOperator_OperatorType.Descriptor instead.
func (MlOperator_OperatorType) EnumDescriptor() ([]byte, []int) {
	return file_spark_connect_ml_common_proto_rawDescGZIP(), []int{1, 0}
}

// MlParams stores param settings for ML Estimator / Transformer / Evaluator
type MlParams struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// User-supplied params
	Params        map[string]*Expression_Literal `protobuf:"bytes,1,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MlParams) Reset() {
	*x = MlParams{}
	mi := &file_spark_connect_ml_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MlParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MlParams) ProtoMessage() {}

func (x *MlParams) ProtoReflect() protoreflect.Message {
	mi := &file_spark_connect_ml_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MlParams.ProtoReflect.Descriptor instead.
func (*MlParams) Descriptor() ([]byte, []int) {
	return file_spark_connect_ml_common_proto_rawDescGZIP(), []int{0}
}

func (x *MlParams) GetParams() map[string]*Expression_Literal {
	if x != nil {
		return x.Params
	}
	return nil
}

// MLOperator represents the ML operators like (Estimator, Transformer or Evaluator)
type MlOperator struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// (Required) The qualified name of the ML operator.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// (Required) Unique id of the ML operator
	Uid string `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	// (Required) Represents what the ML operator is
	Type          MlOperator_OperatorType `protobuf:"varint,3,opt,name=type,proto3,enum=spark.connect.MlOperator_OperatorType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MlOperator) Reset() {
	*x = MlOperator{}
	mi := &file_spark_connect_ml_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MlOperator) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MlOperator) ProtoMessage() {}

func (x *MlOperator) ProtoReflect() protoreflect.Message {
	mi := &file_spark_connect_ml_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MlOperator.ProtoReflect.Descriptor instead.
func (*MlOperator) Descriptor() ([]byte, []int) {
	return file_spark_connect_ml_common_proto_rawDescGZIP(), []int{1}
}

func (x *MlOperator) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MlOperator) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *MlOperator) GetType() MlOperator_OperatorType {
	if x != nil {
		return x.Type
	}
	return MlOperator_OPERATOR_TYPE_UNSPECIFIED
}

// Represents a reference to the cached object which could be a model
// or summary evaluated by a model
type ObjectRef struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// (Required) The ID is used to lookup the object on the server side.
	// Note it is different from the 'uid' of a ML object.
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObjectRef) Reset() {
	*x = ObjectRef{}
	mi := &file_spark_connect_ml_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObjectRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectRef) ProtoMessage() {}

func (x *ObjectRef) ProtoReflect() protoreflect.Message {
	mi := &file_spark_connect_ml_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectRef.ProtoReflect.Descriptor instead.
func (*ObjectRef) Descriptor() ([]byte, []int) {
	return file_spark_connect_ml_common_proto_rawDescGZIP(), []int{2}
}

func (x *ObjectRef) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_spark_connect_ml_common_proto protoreflect.FileDescriptor

const file_spark_connect_ml_common_proto_rawDesc = "" +
	"\n" +
	"\x1dspark/connect/ml_common.proto\x12\rspark.connect\x1a\x1fspark/connect/expressions.proto\"\xa5\x01\n" +
	"\bMlParams\x12;\n" +
	"\x06params\x18\x01 \x03(\v2#.spark.connect.MlParams.ParamsEntryR\x06params\x1a\\\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x127\n" +
	"\x05value\x18\x02 \x01(\v2!.spark.connect.Expression.LiteralR\x05value:\x028\x01\"\x90\x02\n" +
	"\n" +
	"MlOperator\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\tR\x03uid\x12:\n" +
	"\x04type\x18\x03 \x01(\x0e2&.spark.connect.MlOperator.OperatorTypeR\x04type\"\x9f\x01\n" +
	"\fOperatorType\x12\x1d\n" +
	"\x19OPERATOR_TYPE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17OPERATOR_TYPE_ESTIMATOR\x10\x01\x12\x1d\n" +
	"\x19OPERATOR_TYPE_TRANSFORMER\x10\x02\x12\x1b\n" +
	"\x17OPERATOR_TYPE_EVALUATOR\x10\x03\x12\x17\n" +
	"\x13OPERATOR_TYPE_MODEL\x10\x04\"\x1b\n" +
	"\tObjectRef\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02idB6\n" +
	"\x1eorg.apache.spark.connect.protoP\x01Z\x12internal/generatedb\x06proto3"

var (
	file_spark_connect_ml_common_proto_rawDescOnce sync.Once
	file_spark_connect_ml_common_proto_rawDescData []byte
)

func file_spark_connect_ml_common_proto_rawDescGZIP() []byte {
	file_spark_connect_ml_common_proto_rawDescOnce.Do(func() {
		file_spark_connect_ml_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_spark_connect_ml_common_proto_rawDesc), len(file_spark_connect_ml_common_proto_rawDesc)))
	})
	return file_spark_connect_ml_common_proto_rawDescData
}

var file_spark_connect_ml_common_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_spark_connect_ml_common_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_spark_connect_ml_common_proto_goTypes = []any{
	(MlOperator_OperatorType)(0), // 0: spark.connect.MlOperator.OperatorType
	(*MlParams)(nil),             // 1: spark.connect.MlParams
	(*MlOperator)(nil),           // 2: spark.connect.MlOperator
	(*ObjectRef)(nil),            // 3: spark.connect.ObjectRef
	nil,                          // 4: spark.connect.MlParams.ParamsEntry
	(*Expression_Literal)(nil),   // 5: spark.connect.Expression.Literal
}
var file_spark_connect_ml_common_proto_depIdxs = []int32{
	4, // 0: spark.connect.MlParams.params:type_name -> spark.connect.MlParams.ParamsEntry
	0, // 1: spark.connect.MlOperator.type:type_name -> spark.connect.MlOperator.OperatorType
	5, // 2: spark.connect.MlParams.ParamsEntry.value:type_name -> spark.connect.Expression.Literal
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_spark_connect_ml_common_proto_init() }
func file_spark_connect_ml_common_proto_init() {
	if File_spark_connect_ml_common_proto != nil {
		return
	}
	file_spark_connect_expressions_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_spark_connect_ml_common_proto_rawDesc), len(file_spark_connect_ml_common_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_spark_connect_ml_common_proto_goTypes,
		DependencyIndexes: file_spark_connect_ml_common_proto_depIdxs,
		EnumInfos:         file_spark_connect_ml_common_proto_enumTypes,
		MessageInfos:      file_spark_connect_ml_common_proto_msgTypes,
	}.Build()
	File_spark_connect_ml_common_proto = out.File
	file_spark_connect_ml_common_proto_goTypes = nil
	file_spark_connect_ml_common_proto_depIdxs = nil
}
