//
// Licensed to the Apache Software Foundation (ASF) under one or more
// contributor license agreements.  See the NOTICE file distributed with
// this work for additional information regarding copyright ownership.
// The ASF licenses this file to You under the Apache License, Version 2.0
// (the "License"); you may not use this file except in compliance with
// the License.  You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: spark/connect/pipelines.proto

package generated

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The type of output.
type OutputType int32

const (
	// Safe default value. Should not be used.
	OutputType_OUTPUT_TYPE_UNSPECIFIED OutputType = 0
	// A materialized view which is published to the catalog
	OutputType_MATERIALIZED_VIEW OutputType = 1
	// A table which is published to the catalog
	OutputType_TABLE OutputType = 2
	// A view which is not published to the catalog
	OutputType_TEMPORARY_VIEW OutputType = 3
	// A sink which is not published to the catalog
	OutputType_SINK OutputType = 4
)

// Enum value maps for OutputType.
var (
	OutputType_name = map[int32]string{
		0: "OUTPUT_TYPE_UNSPECIFIED",
		1: "MATERIALIZED_VIEW",
		2: "TABLE",
		3: "TEMPORARY_VIEW",
		4: "SINK",
	}
	OutputType_value = map[string]int32{
		"OUTPUT_TYPE_UNSPECIFIED": 0,
		"MATERIALIZED_VIEW":       1,
		"TABLE":                   2,
		"TEMPORARY_VIEW":          3,
		"SINK":                    4,
	}
)

func (x OutputType) Enum() *OutputType {
	p := new(OutputType)
	*p = x
	return p
}

func (x OutputType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OutputType) Descriptor() protoreflect.EnumDescriptor {
	return file_spark_connect_pipelines_proto_enumTypes[0].Descriptor()
}

func (OutputType) Type() protoreflect.EnumType {
	return &file_spark_connect_pipelines_proto_enumTypes[0]
}

func (x OutputType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OutputType.Descriptor instead.
func (OutputType) EnumDescriptor() ([]byte, []int) {
	return file_spark_connect_pipelines_proto_rawDescGZIP(), []int{0}
}

// Dispatch object for pipelines commands. See each individual command for documentation.
type PipelineCommand struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to CommandType:
	//
	//	*PipelineCommand_CreateDataflowGraph_
	//	*PipelineCommand_DefineOutput_
	//	*PipelineCommand_DefineFlow_
	//	*PipelineCommand_DropDataflowGraph_
	//	*PipelineCommand_StartRun_
	//	*PipelineCommand_DefineSqlGraphElements_
	//	*PipelineCommand_GetQueryFunctionExecutionSignalStream_
	//	*PipelineCommand_DefineFlowQueryFunctionResult_
	//	*PipelineCommand_ExecuteOutputFlows_
	//	*PipelineCommand_Extension
	CommandType   isPipelineCommand_CommandType `protobuf_oneof:"command_type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PipelineCommand) Reset() {
	*x = PipelineCommand{}
	mi := &file_spark_connect_pipelines_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PipelineCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PipelineCommand) ProtoMessage() {}

func (x *PipelineCommand) ProtoReflect() protoreflect.Message {
	mi := &file_spark_connect_pipelines_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PipelineCommand.ProtoReflect.Descriptor instead.
func (*PipelineCommand) Descriptor() ([]byte, []int) {
	return file_spark_connect_pipelines_proto_rawDescGZIP(), []int{0}
}

func (x *PipelineCommand) GetCommandType() isPipelineCommand_CommandType {
	if x != nil {
		return x.CommandType
	}
	return nil
}

func (x *PipelineCommand) GetCreateDataflowGraph() *PipelineCommand_CreateDataflowGraph {
	if x != nil {
		if x, ok := x.CommandType.(*PipelineCommand_CreateDataflowGraph_); ok {
			return x.CreateDataflowGraph
		}
	}
	return nil
}

func (x *PipelineCommand) GetDefineOutput() *PipelineCommand_DefineOutput {
	if x != nil {
		if x, ok := x.CommandType.(*PipelineCommand_DefineOutput_); ok {
			return x.DefineOutput
		}
	}
	return nil
}

func (x *PipelineCommand) GetDefineFlow() *PipelineCommand_DefineFlow {
	if x != nil {
		if x, ok := x.CommandType.(*PipelineCommand_DefineFlow_); ok {
			return x.DefineFlow
		}
	}
	return nil
}

func (x *PipelineCommand) GetDropDataflowGraph() *PipelineCommand_DropDataflowGraph {
	if x != nil {
		if x, ok := x.CommandType.(*PipelineCommand_DropDataflowGraph_); ok {
			return x.DropDataflowGraph
		}
	}
	return nil
}

func (x *PipelineCommand) GetStartRun() *PipelineCommand_StartRun {
	if x != nil {
		if x, ok := x.CommandType.(*PipelineCommand_StartRun_); ok {
			return x.StartRun
		}
	}
	return nil
}

func (x *PipelineCommand) GetDefineSqlGraphElements() *PipelineCommand_DefineSqlGraphElements {
	if x != nil {
		if x, ok := x.CommandType.(*PipelineCommand_DefineSqlGraphElements_); ok {
			return x.DefineSqlGraphElements
		}
	}
	return nil
}

func (x *PipelineCommand) GetGetQueryFunctionExecutionSignalStream() *PipelineCommand_GetQueryFunctionExecutionSignalStream {
	if x != nil {
		if x, ok := x.CommandType.(*PipelineCommand_GetQueryFunctionExecutionSignalStream_); ok {
			return x.GetQueryFunctionExecutionSignalStream
		}
	}
	return nil
}

func (x *PipelineCommand) GetDefineFlowQueryFunctionResult() *PipelineCommand_DefineFlowQueryFunctionResult {
	if x != nil {
		if x, ok := x.CommandType.(*PipelineCommand_DefineFlowQueryFunctionResult_); ok {
			return x.DefineFlowQueryFunctionResult
		}
	}
	return nil
}

func (x *PipelineCommand) GetExecuteOutputFlows() *PipelineCommand_ExecuteOutputFlows {
	if x != nil {
		if x, ok := x.CommandType.(*PipelineCommand_ExecuteOutputFlows_); ok {
			return x.ExecuteOutputFlows
		}
	}
	return nil
}

func (x *PipelineCommand) GetExtension() *anypb.Any {
	if x != nil {
		if x, ok := x.CommandType.(*PipelineCommand_Extension); ok {
			return x.Extension
		}
	}
	return nil
}

type isPipelineCommand_CommandType interface {
	isPipelineCommand_CommandType()
}

type PipelineCommand_CreateDataflowGraph_ struct {
	CreateDataflowGraph *PipelineCommand_CreateDataflowGraph `protobuf:"bytes,1,opt,name=create_dataflow_graph,json=createDataflowGraph,proto3,oneof"`
}

type PipelineCommand_DefineOutput_ struct {
	DefineOutput *PipelineCommand_DefineOutput `protobuf:"bytes,2,opt,name=define_output,json=defineOutput,proto3,oneof"`
}

type PipelineCommand_DefineFlow_ struct {
	DefineFlow *PipelineCommand_DefineFlow `protobuf:"bytes,3,opt,name=define_flow,json=defineFlow,proto3,oneof"`
}

type PipelineCommand_DropDataflowGraph_ struct {
	DropDataflowGraph *PipelineCommand_DropDataflowGraph `protobuf:"bytes,4,opt,name=drop_dataflow_graph,json=dropDataflowGraph,proto3,oneof"`
}

type PipelineCommand_StartRun_ struct {
	StartRun *PipelineCommand_StartRun `protobuf:"bytes,5,opt,name=start_run,json=startRun,proto3,oneof"`
}

type PipelineCommand_DefineSqlGraphElements_ struct {
	DefineSqlGraphElements *PipelineCommand_DefineSqlGraphElements `protobuf:"bytes,6,opt,name=define_sql_graph_elements,json=defineSqlGraphElements,proto3,oneof"`
}

type PipelineCommand_GetQueryFunctionExecutionSignalStream_ struct {
	GetQueryFunctionExecutionSignalStream *PipelineCommand_GetQueryFunctionExecutionSignalStream `protobuf:"bytes,7,opt,name=get_query_function_execution_signal_stream,json=getQueryFunctionExecutionSignalStream,proto3,oneof"`
}

type PipelineCommand_DefineFlowQueryFunctionResult_ struct {
	DefineFlowQueryFunctionResult *PipelineCommand_DefineFlowQueryFunctionResult `protobuf:"bytes,8,opt,name=define_flow_query_function_result,json=defineFlowQueryFunctionResult,proto3,oneof"`
}

type PipelineCommand_ExecuteOutputFlows_ struct {
	ExecuteOutputFlows *PipelineCommand_ExecuteOutputFlows `protobuf:"bytes,9,opt,name=execute_output_flows,json=executeOutputFlows,proto3,oneof"`
}

type PipelineCommand_Extension struct {
	// Reserved field for protocol extensions.
	// Used to support forward-compatibility by carrying additional command types
	// that are not yet defined in this version of the proto. During planning, the
	// engine will resolve and dispatch the concrete command contained in this field.
	Extension *anypb.Any `protobuf:"bytes,999,opt,name=extension,proto3,oneof"`
}

func (*PipelineCommand_CreateDataflowGraph_) isPipelineCommand_CommandType() {}

func (*PipelineCommand_DefineOutput_) isPipelineCommand_CommandType() {}

func (*PipelineCommand_DefineFlow_) isPipelineCommand_CommandType() {}

func (*PipelineCommand_DropDataflowGraph_) isPipelineCommand_CommandType() {}

func (*PipelineCommand_StartRun_) isPipelineCommand_CommandType() {}

func (*PipelineCommand_DefineSqlGraphElements_) isPipelineCommand_CommandType() {}

func (*PipelineCommand_GetQueryFunctionExecutionSignalStream_) isPipelineCommand_CommandType() {}

func (*PipelineCommand_DefineFlowQueryFunctionResult_) isPipelineCommand_CommandType() {}

func (*PipelineCommand_ExecuteOutputFlows_) isPipelineCommand_CommandType() {}

func (*PipelineCommand_Extension) isPipelineCommand_CommandType() {}

// Dispatch object for pipelines command results.
type PipelineCommandResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to ResultType:
	//
	//	*PipelineCommandResult_CreateDataflowGraphResult_
	//	*PipelineCommandResult_DefineOutputResult_
	//	*PipelineCommandResult_DefineFlowResult_
	ResultType    isPipelineCommandResult_ResultType `protobuf_oneof:"result_type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PipelineCommandResult) Reset() {
	*x = PipelineCommandResult{}
	mi := &file_spark_connect_pipelines_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PipelineCommandResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PipelineCommandResult) ProtoMessage() {}

func (x *PipelineCommandResult) ProtoReflect() protoreflect.Message {
	mi := &file_spark_connect_pipelines_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PipelineCommandResult.ProtoReflect.Descriptor instead.
func (*PipelineCommandResult) Descriptor() ([]byte, []int) {
	return file_spark_connect_pipelines_proto_rawDescGZIP(), []int{1}
}

func (x *PipelineCommandResult) GetResultType() isPipelineCommandResult_ResultType {
	if x != nil {
		return x.ResultType
	}
	return nil
}

func (x *PipelineCommandResult) GetCreateDataflowGraphResult() *PipelineCommandResult_CreateDataflowGraphResult {
	if x != nil {
		if x, ok := x.ResultType.(*PipelineCommandResult_CreateDataflowGraphResult_); ok {
			return x.CreateDataflowGraphResult
		}
	}
	return nil
}

func (x *PipelineCommandResult) GetDefineOutputResult() *PipelineCommandResult_DefineOutputResult {
	if x != nil {
		if x, ok := x.ResultType.(*PipelineCommandResult_DefineOutputResult_); ok {
			return x.DefineOutputResult
		}
	}
	return nil
}

func (x *PipelineCommandResult) GetDefineFlowResult() *PipelineCommandResult_DefineFlowResult {
	if x != nil {
		if x, ok := x.ResultType.(*PipelineCommandResult_DefineFlowResult_); ok {
			return x.DefineFlowResult
		}
	}
	return nil
}

type isPipelineCommandResult_ResultType interface {
	isPipelineCommandResult_ResultType()
}

type PipelineCommandResult_CreateDataflowGraphResult_ struct {
	CreateDataflowGraphResult *PipelineCommandResult_CreateDataflowGraphResult `protobuf:"bytes,1,opt,name=create_dataflow_graph_result,json=createDataflowGraphResult,proto3,oneof"`
}

type PipelineCommandResult_DefineOutputResult_ struct {
	DefineOutputResult *PipelineCommandResult_DefineOutputResult `protobuf:"bytes,2,opt,name=define_output_result,json=defineOutputResult,proto3,oneof"`
}

type PipelineCommandResult_DefineFlowResult_ struct {
	DefineFlowResult *PipelineCommandResult_DefineFlowResult `protobuf:"bytes,3,opt,name=define_flow_result,json=defineFlowResult,proto3,oneof"`
}

func (*PipelineCommandResult_CreateDataflowGraphResult_) isPipelineCommandResult_ResultType() {}

func (*PipelineCommandResult_DefineOutputResult_) isPipelineCommandResult_ResultType() {}

func (*PipelineCommandResult_DefineFlowResult_) isPipelineCommandResult_ResultType() {}

// A response containing an event emitted during the run of a pipeline.
type PipelineEventResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         *PipelineEvent         `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PipelineEventResult) Reset() {
	*x = PipelineEventResult{}
	mi := &file_spark_connect_pipelines_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PipelineEventResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PipelineEventResult) ProtoMessage() {}

func (x *PipelineEventResult) ProtoReflect() protoreflect.Message {
	mi := &file_spark_connect_pipelines_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PipelineEventResult.ProtoReflect.Descriptor instead.
func (*PipelineEventResult) Descriptor() ([]byte, []int) {
	return file_spark_connect_pipelines_proto_rawDescGZIP(), []int{2}
}

func (x *PipelineEventResult) GetEvent() *PipelineEvent {
	if x != nil {
		return x.Event
	}
	return nil
}

type PipelineEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The timestamp corresponding to when the event occurred.
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// The message that should be displayed to users.
	Message       *string `protobuf:"bytes,2,opt,name=message,proto3,oneof" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PipelineEvent) Reset() {
	*x = PipelineEvent{}
	mi := &file_spark_connect_pipelines_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PipelineEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PipelineEvent) ProtoMessage() {}

func (x *PipelineEvent) ProtoReflect() protoreflect.Message {
	mi := &file_spark_connect_pipelines_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PipelineEvent.ProtoReflect.Descriptor instead.
func (*PipelineEvent) Descriptor() ([]byte, []int) {
	return file_spark_connect_pipelines_proto_rawDescGZIP(), []int{3}
}

func (x *PipelineEvent) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *PipelineEvent) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

// Source code location information associated with a particular dataset or flow.
type SourceCodeLocation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The file that this pipeline source code was defined in.
	FileName *string `protobuf:"bytes,1,opt,name=file_name,json=fileName,proto3,oneof" json:"file_name,omitempty"`
	// The specific line number that this pipeline source code is located at, if applicable.
	LineNumber *int32 `protobuf:"varint,2,opt,name=line_number,json=lineNumber,proto3,oneof" json:"line_number,omitempty"`
	// The path of the top-level pipeline file determined at runtime during pipeline initialization.
	DefinitionPath *string `protobuf:"bytes,3,opt,name=definition_path,json=definitionPath,proto3,oneof" json:"definition_path,omitempty"`
	// Reserved field for protocol extensions.
	// Used to support forward-compatibility by carrying additional fields
	// that are not yet defined in this version of the proto. During planning, the
	// engine will resolve and dispatch the concrete command contained in this field.
	Extension     []*anypb.Any `protobuf:"bytes,999,rep,name=extension,proto3" json:"extension,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SourceCodeLocation) Reset() {
	*x = SourceCodeLocation{}
	mi := &file_spark_connect_pipelines_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SourceCodeLocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourceCodeLocation) ProtoMessage() {}

func (x *SourceCodeLocation) ProtoReflect() protoreflect.Message {
	mi := &file_spark_connect_pipelines_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourceCodeLocation.ProtoReflect.Descriptor instead.
func (*SourceCodeLocation) Descriptor() ([]byte, []int) {
	return file_spark_connect_pipelines_proto_rawDescGZIP(), []int{4}
}

func (x *SourceCodeLocation) GetFileName() string {
	if x != nil && x.FileName != nil {
		return *x.FileName
	}
	return ""
}

func (x *SourceCodeLocation) GetLineNumber() int32 {
	if x != nil && x.LineNumber != nil {
		return *x.LineNumber
	}
	return 0
}

func (x *SourceCodeLocation) GetDefinitionPath() string {
	if x != nil && x.DefinitionPath != nil {
		return *x.DefinitionPath
	}
	return ""
}

func (x *SourceCodeLocation) GetExtension() []*anypb.Any {
	if x != nil {
		return x.Extension
	}
	return nil
}

// A signal from the server to the client to execute the query function for one or more flows, and
// to register their results with the server.
type PipelineQueryFunctionExecutionSignal struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// (Deprecated) The name of flows that are ready to be re-evaluated.
	//
	// This field is deprecated since Spark 4.2+. Use flow_identifiers field instead.
	//
	// Deprecated: Marked as deprecated in spark/connect/pipelines.proto.
	FlowNames []string `protobuf:"bytes,1,rep,name=flow_names,json=flowNames,proto3" json:"flow_names,omitempty"`
	// The identifier of flows that are ready to be re-evaluated
	FlowIdentifiers []*ResolvedIdentifier `protobuf:"bytes,2,rep,name=flow_identifiers,json=flowIdentifiers,proto3" json:"flow_identifiers,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PipelineQueryFunctionExecutionSignal) Reset() {
	*x = PipelineQueryFunctionExecutionSignal{}
	mi := &file_spark_connect_pipelines_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PipelineQueryFunctionExecutionSignal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PipelineQueryFunctionExecutionSignal) ProtoMessage() {}

func (x *PipelineQueryFunctionExecutionSignal) ProtoReflect() protoreflect.Message {
	mi := &file_spark_connect_pipelines_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PipelineQueryFunctionExecutionSignal.ProtoReflect.Descriptor instead.
func (*PipelineQueryFunctionExecutionSignal) Descriptor() ([]byte, []int) {
	return file_spark_connect_pipelines_proto_rawDescGZIP(), []int{5}
}

// Deprecated: Marked as deprecated in spark/connect/pipelines.proto.
func (x *PipelineQueryFunctionExecutionSignal) GetFlowNames() []string {
	if x != nil {
		return x.FlowNames
	}
	return nil
}

func (x *PipelineQueryFunctionExecutionSignal) GetFlowIdentifiers() []*ResolvedIdentifier {
	if x != nil {
		return x.FlowIdentifiers
	}
	return nil
}

// Metadata providing context about the pipeline during Spark Connect query analysis.
type PipelineAnalysisContext struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier of the dataflow graph associated with this pipeline.
	DataflowGraphId *string `protobuf:"bytes,1,opt,name=dataflow_graph_id,json=dataflowGraphId,proto3,oneof" json:"dataflow_graph_id,omitempty"`
	// The path of the top-level pipeline file determined at runtime during pipeline initialization.
	DefinitionPath *string `protobuf:"bytes,2,opt,name=definition_path,json=definitionPath,proto3,oneof" json:"definition_path,omitempty"`
	// (Deprecated) The name of the Flow involved in this analysis
	//
	// This field is deprecated since Spark 4.2+. Use flow_identifier field instead.
	//
	// Deprecated: Marked as deprecated in spark/connect/pipelines.proto.
	FlowName *string `protobuf:"bytes,3,opt,name=flow_name,json=flowName,proto3,oneof" json:"flow_name,omitempty"`
	// The identifier of the Flow involved in this analysis
	FlowIdentifier *ResolvedIdentifier `protobuf:"bytes,4,opt,name=flow_identifier,json=flowIdentifier,proto3,oneof" json:"flow_identifier,omitempty"`
	// Reserved field for protocol extensions.
	Extension     []*anypb.Any `protobuf:"bytes,999,rep,name=extension,proto3" json:"extension,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PipelineAnalysisContext) Reset() {
	*x = PipelineAnalysisContext{}
	mi := &file_spark_connect_pipelines_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PipelineAnalysisContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PipelineAnalysisContext) ProtoMessage() {}

func (x *PipelineAnalysisContext) ProtoReflect() protoreflect.Message {
	mi := &file_spark_connect_pipelines_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PipelineAnalysisContext.ProtoReflect.Descriptor instead.
func (*PipelineAnalysisContext) Descriptor() ([]byte, []int) {
	return file_spark_connect_pipelines_proto_rawDescGZIP(), []int{6}
}

func (x *PipelineAnalysisContext) GetDataflowGraphId() string {
	if x != nil && x.DataflowGraphId != nil {
		return *x.DataflowGraphId
	}
	return ""
}

func (x *PipelineAnalysisContext) GetDefinitionPath() string {
	if x != nil && x.DefinitionPath != nil {
		return *x.DefinitionPath
	}
	return ""
}

// Deprecated: Marked as deprecated in spark/connect/pipelines.proto.
func (x *PipelineAnalysisContext) GetFlowName() string {
	if x != nil && x.FlowName != nil {
		return *x.FlowName
	}
	return ""
}

func (x *PipelineAnalysisContext) GetFlowIdentifier() *ResolvedIdentifier {
	if x != nil {
		return x.FlowIdentifier
	}
	return nil
}

func (x *PipelineAnalysisContext) GetExtension() []*anypb.Any {
	if x != nil {
		return x.Extension
	}
	return nil
}

// Request to create a new dataflow graph.
type PipelineCommand_CreateDataflowGraph struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The default catalog.
	DefaultCatalog *string `protobuf:"bytes,1,opt,name=default_catalog,json=defaultCatalog,proto3,oneof" json:"default_catalog,omitempty"`
	// The default database.
	DefaultDatabase *string `protobuf:"bytes,2,opt,name=default_database,json=defaultDatabase,proto3,oneof" json:"default_database,omitempty"`
	// SQL configurations for all flows in this graph.
	SqlConf       map[string]string `protobuf:"bytes,5,rep,name=sql_conf,json=sqlConf,proto3" json:"sql_conf,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PipelineCommand_CreateDataflowGraph) Reset() {
	*x = PipelineCommand_CreateDataflowGraph{}
	mi := &file_spark_connect_pipelines_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PipelineCommand_CreateDataflowGraph) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PipelineCommand_CreateDataflowGraph) ProtoMessage() {}

func (x *PipelineCommand_CreateDataflowGraph) ProtoReflect() protoreflect.Message {
	mi := &file_spark_connect_pipelines_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PipelineCommand_CreateDataflowGraph.ProtoReflect.Descriptor instead.
func (*PipelineCommand_CreateDataflowGraph) Descriptor() ([]byte, []int) {
	return file_spark_connect_pipelines_proto_rawDescGZIP(), []int{0, 0}
}

func (x *PipelineCommand_CreateDataflowGraph) GetDefaultCatalog() string {
	if x != nil && x.DefaultCatalog != nil {
		return *x.DefaultCatalog
	}
	return ""
}

func (x *PipelineCommand_CreateDataflowGraph) GetDefaultDatabase() string {
	if x != nil && x.DefaultDatabase != nil {
		return *x.DefaultDatabase
	}
	return ""
}

func (x *PipelineCommand_CreateDataflowGraph) GetSqlConf() map[string]string {
	if x != nil {
		return x.SqlConf
	}
	return nil
}

// Drops the graph and stops any running attached flows.
type PipelineCommand_DropDataflowGraph struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The graph to drop.
	DataflowGraphId *string `protobuf:"bytes,1,opt,name=dataflow_graph_id,json=dataflowGraphId,proto3,oneof" json:"dataflow_graph_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PipelineCommand_DropDataflowGraph) Reset() {
	*x = PipelineCommand_DropDataflowGraph{}
	mi := &file_spark_connect_pipelines_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PipelineCommand_DropDataflowGraph) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PipelineCommand_DropDataflowGraph) ProtoMessage() {}

func (x *PipelineCommand_DropDataflowGraph) ProtoReflect() protoreflect.Message {
	mi := &file_spark_connect_pipelines_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PipelineCommand_DropDataflowGraph.ProtoReflect.Descriptor instead.
func (*PipelineCommand_DropDataflowGraph) Descriptor() ([]byte, []int) {
	return file_spark_connect_pipelines_proto_rawDescGZIP(), []int{0, 1}
}

func (x *PipelineCommand_DropDataflowGraph) GetDataflowGraphId() string {
	if x != nil && x.DataflowGraphId != nil {
		return *x.DataflowGraphId
	}
	return ""
}

// Request to define an output: a table, a materialized view, a temporary view or a sink.
type PipelineCommand_DefineOutput struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The graph to attach this output to.
	DataflowGraphId *string `protobuf:"bytes,1,opt,name=dataflow_graph_id,json=dataflowGraphId,proto3,oneof" json:"dataflow_graph_id,omitempty"`
	// Name of the output. Can be partially or fully qualified.
	OutputName *string `protobuf:"bytes,2,opt,name=output_name,json=outputName,proto3,oneof" json:"output_name,omitempty"`
	// The type of the output.
	OutputType *OutputType `protobuf:"varint,3,opt,name=output_type,json=outputType,proto3,enum=spark.connect.OutputType,oneof" json:"output_type,omitempty"`
	// Optional comment for the output.
	Comment *string `protobuf:"bytes,4,opt,name=comment,proto3,oneof" json:"comment,omitempty"`
	// The location in source code that this output was defined.
	SourceCodeLocation *SourceCodeLocation `protobuf:"bytes,5,opt,name=source_code_location,json=sourceCodeLocation,proto3,oneof" json:"source_code_location,omitempty"`
	// Types that are valid to be assigned to Details:
	//
	//	*PipelineCommand_DefineOutput_TableDetails_
	//	*PipelineCommand_DefineOutput_SinkDetails_
	//	*PipelineCommand_DefineOutput_Extension
	Details       isPipelineCommand_DefineOutput_Details `protobuf_oneof:"details"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PipelineCommand_DefineOutput) Reset() {
	*x = PipelineCommand_DefineOutput{}
	mi := &file_spark_connect_pipelines_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PipelineCommand_DefineOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PipelineCommand_DefineOutput) ProtoMessage() {}

func (x *PipelineCommand_DefineOutput) ProtoReflect() protoreflect.Message {
	mi := &file_spark_connect_pipelines_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PipelineCommand_DefineOutput.ProtoReflect.Descriptor instead.
func (*PipelineCommand_DefineOutput) Descriptor() ([]byte, []int) {
	return file_spark_connect_pipelines_proto_rawDescGZIP(), []int{0, 2}
}

func (x *PipelineCommand_DefineOutput) GetDataflowGraphId() string {
	if x != nil && x.DataflowGraphId != nil {
		return *x.DataflowGraphId
	}
	return ""
}

func (x *PipelineCommand_DefineOutput) GetOutputName() string {
	if x != nil && x.OutputName != nil {
		return *x.OutputName
	}
	return ""
}

func (x *PipelineCommand_DefineOutput) GetOutputType() OutputType {
	if x != nil && x.OutputType != nil {
		return *x.OutputType
	}
	return OutputType_OUTPUT_TYPE_UNSPECIFIED
}

func (x *PipelineCommand_DefineOutput) GetComment() string {
	if x != nil && x.Comment != nil {
		return *x.Comment
	}
	return ""
}

func (x *PipelineCommand_DefineOutput) GetSourceCodeLocation() *SourceCodeLocation {
	if x != nil {
		return x.SourceCodeLocation
	}
	return nil
}

func (x *PipelineCommand_DefineOutput) GetDetails() isPipelineCommand_DefineOutput_Details {
	if x != nil {
		return x.Details
	}
	return nil
}

func (x *PipelineCommand_DefineOutput) GetTableDetails() *PipelineCommand_DefineOutput_TableDetails {
	if x != nil {
		if x, ok := x.Details.(*PipelineCommand_DefineOutput_TableDetails_); ok {
			return x.TableDetails
		}
	}
	return nil
}

func (x *PipelineCommand_DefineOutput) GetSinkDetails() *PipelineCommand_DefineOutput_SinkDetails {
	if x != nil {
		if x, ok := x.Details.(*PipelineCommand_DefineOutput_SinkDetails_); ok {
			return x.SinkDetails
		}
	}
	return nil
}

func (x *PipelineCommand_DefineOutput) GetExtension() *anypb.Any {
	if x != nil {
		if x, ok := x.Details.(*PipelineCommand_DefineOutput_Extension); ok {
			return x.Extension
		}
	}
	return nil
}

type isPipelineCommand_DefineOutput_Details interface {
	isPipelineCommand_DefineOutput_Details()
}

type PipelineCommand_DefineOutput_TableDetails_ struct {
	TableDetails *PipelineCommand_DefineOutput_TableDetails `protobuf:"bytes,6,opt,name=table_details,json=tableDetails,proto3,oneof"`
}

type PipelineCommand_DefineOutput_SinkDetails_ struct {
	SinkDetails *PipelineCommand_DefineOutput_SinkDetails `protobuf:"bytes,7,opt,name=sink_details,json=sinkDetails,proto3,oneof"`
}

type PipelineCommand_DefineOutput_Extension struct {
	Extension *anypb.Any `protobuf:"bytes,999,opt,name=extension,proto3,oneof"`
}

func (*PipelineCommand_DefineOutput_TableDetails_) isPipelineCommand_DefineOutput_Details() {}

func (*PipelineCommand_DefineOutput_SinkDetails_) isPipelineCommand_DefineOutput_Details() {}

func (*PipelineCommand_DefineOutput_Extension) isPipelineCommand_DefineOutput_Details() {}

// Request to define a flow targeting a dataset.
type PipelineCommand_DefineFlow struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The graph to attach this flow to.
	DataflowGraphId *string `protobuf:"bytes,1,opt,name=dataflow_graph_id,json=dataflowGraphId,proto3,oneof" json:"dataflow_graph_id,omitempty"`
	// Name of the flow. For standalone flows, this must be a single-part name.
	FlowName *string `protobuf:"bytes,2,opt,name=flow_name,json=flowName,proto3,oneof" json:"flow_name,omitempty"`
	// Name of the dataset this flow writes to. Can be partially or fully qualified.
	TargetDatasetName *string `protobuf:"bytes,3,opt,name=target_dataset_name,json=targetDatasetName,proto3,oneof" json:"target_dataset_name,omitempty"`
	// SQL configurations set when running this flow.
	SqlConf map[string]string `protobuf:"bytes,4,rep,name=sql_conf,json=sqlConf,proto3" json:"sql_conf,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Identifier for the client making the request. The server uses this to determine what flow
	// evaluation request stream to dispatch evaluation requests to for this flow.
	ClientId *string `protobuf:"bytes,5,opt,name=client_id,json=clientId,proto3,oneof" json:"client_id,omitempty"`
	// The location in source code that this flow was defined.
	SourceCodeLocation *SourceCodeLocation `protobuf:"bytes,6,opt,name=source_code_location,json=sourceCodeLocation,proto3,oneof" json:"source_code_location,omitempty"`
	// Types that are valid to be assigned to Details:
	//
	//	*PipelineCommand_DefineFlow_RelationFlowDetails
	//	*PipelineCommand_DefineFlow_Extension
	Details isPipelineCommand_DefineFlow_Details `protobuf_oneof:"details"`
	// If true, define the flow as a one-time flow, such as for backfill.
	// Set to true changes the flow in two ways:
	//   - The flow is run one time by default. If the pipeline is ran with a full refresh,
	//     the flow will run again.
	//   - The flow function must be a batch DataFrame, not a streaming DataFrame.
	Once          *bool `protobuf:"varint,8,opt,name=once,proto3,oneof" json:"once,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PipelineCommand_DefineFlow) Reset() {
	*x = PipelineCommand_DefineFlow{}
	mi := &file_spark_connect_pipelines_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PipelineCommand_DefineFlow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PipelineCommand_DefineFlow) ProtoMessage() {}

func (x *PipelineCommand_DefineFlow) ProtoReflect() protoreflect.Message {
	mi := &file_spark_connect_pipelines_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PipelineCommand_DefineFlow.ProtoReflect.Descriptor instead.
func (*PipelineCommand_DefineFlow) Descriptor() ([]byte, []int) {
	return file_spark_connect_pipelines_proto_rawDescGZIP(), []int{0, 3}
}

func (x *PipelineCommand_DefineFlow) GetDataflowGraphId() string {
	if x != nil && x.DataflowGraphId != nil {
		return *x.DataflowGraphId
	}
	return ""
}

func (x *PipelineCommand_DefineFlow) GetFlowName() string {
	if x != nil && x.FlowName != nil {
		return *x.FlowName
	}
	return ""
}

func (x *PipelineCommand_DefineFlow) GetTargetDatasetName() string {
	if x != nil && x.TargetDatasetName != nil {
		return *x.TargetDatasetName
	}
	return ""
}

func (x *PipelineCommand_DefineFlow) GetSqlConf() map[string]string {
	if x != nil {
		return x.SqlConf
	}
	return nil
}

func (x *PipelineCommand_DefineFlow) GetClientId() string {
	if x != nil && x.ClientId != nil {
		return *x.ClientId
	}
	return ""
}

func (x *PipelineCommand_DefineFlow) GetSourceCodeLocation() *SourceCodeLocation {
	if x != nil {
		return x.SourceCodeLocation
	}
	return nil
}

func (x *PipelineCommand_DefineFlow) GetDetails() isPipelineCommand_DefineFlow_Details {
	if x != nil {
		return x.Details
	}
	return nil
}

func (x *PipelineCommand_DefineFlow) GetRelationFlowDetails() *PipelineCommand_DefineFlow_WriteRelationFlowDetails {
	if x != nil {
		if x, ok := x.Details.(*PipelineCommand_DefineFlow_RelationFlowDetails); ok {
			return x.RelationFlowDetails
		}
	}
	return nil
}

func (x *PipelineCommand_DefineFlow) GetExtension() *anypb.Any {
	if x != nil {
		if x, ok := x.Details.(*PipelineCommand_DefineFlow_Extension); ok {
			return x.Extension
		}
	}
	return nil
}

func (x *PipelineCommand_DefineFlow) GetOnce() bool {
	if x != nil && x.Once != nil {
		return *x.Once
	}
	return false
}

type isPipelineCommand_DefineFlow_Details interface {
	isPipelineCommand_DefineFlow_Details()
}

type PipelineCommand_DefineFlow_RelationFlowDetails struct {
	RelationFlowDetails *PipelineCommand_DefineFlow_WriteRelationFlowDetails `protobuf:"bytes,7,opt,name=relation_flow_details,json=relationFlowDetails,proto3,oneof"`
}

type PipelineCommand_DefineFlow_Extension struct {
	Extension *anypb.Any `protobuf:"bytes,999,opt,name=extension,proto3,oneof"`
}

func (*PipelineCommand_DefineFlow_RelationFlowDetails) isPipelineCommand_DefineFlow_Details() {}

func (*PipelineCommand_DefineFlow_Extension) isPipelineCommand_DefineFlow_Details() {}

// Request to execute all flows for a single output (dataset or sink) remotely.
type PipelineCommand_ExecuteOutputFlows struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The output (table or materialized view or sink) definition.
	DefineOutput *PipelineCommand_DefineOutput `protobuf:"bytes,1,opt,name=define_output,json=defineOutput,proto3,oneof" json:"define_output,omitempty"`
	// The flows to execute for this table.
	DefineFlows []*PipelineCommand_DefineFlow `protobuf:"bytes,2,rep,name=define_flows,json=defineFlows,proto3" json:"define_flows,omitempty"`
	// Whether to perform a full refresh instead of an incremental update.
	FullRefresh *bool `protobuf:"varint,3,opt,name=full_refresh,json=fullRefresh,proto3,oneof" json:"full_refresh,omitempty"`
	// Storage location for pipeline checkpoints and metadata.
	Storage *string `protobuf:"bytes,4,opt,name=storage,proto3,oneof" json:"storage,omitempty"`
	// Reserved field for protocol extensions.
	Extension     []*anypb.Any `protobuf:"bytes,999,rep,name=extension,proto3" json:"extension,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PipelineCommand_ExecuteOutputFlows) Reset() {
	*x = PipelineCommand_ExecuteOutputFlows{}
	mi := &file_spark_connect_pipelines_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PipelineCommand_ExecuteOutputFlows) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PipelineCommand_ExecuteOutputFlows) ProtoMessage() {}

func (x *PipelineCommand_ExecuteOutputFlows) ProtoReflect() protoreflect.Message {
	mi := &file_spark_connect_pipelines_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PipelineCommand_ExecuteOutputFlows.ProtoReflect.Descriptor instead.
func (*PipelineCommand_ExecuteOutputFlows) Descriptor() ([]byte, []int) {
	return file_spark_connect_pipelines_proto_rawDescGZIP(), []int{0, 4}
}

func (x *PipelineCommand_ExecuteOutputFlows) GetDefineOutput() *PipelineCommand_DefineOutput {
	if x != nil {
		return x.DefineOutput
	}
	return nil
}

func (x *PipelineCommand_ExecuteOutputFlows) GetDefineFlows() []*PipelineCommand_DefineFlow {
	if x != nil {
		return x.DefineFlows
	}
	return nil
}

func (x *PipelineCommand_ExecuteOutputFlows) GetFullRefresh() bool {
	if x != nil && x.FullRefresh != nil {
		return *x.FullRefresh
	}
	return false
}

func (x *PipelineCommand_ExecuteOutputFlows) GetStorage() string {
	if x != nil && x.Storage != nil {
		return *x.Storage
	}
	return ""
}

func (x *PipelineCommand_ExecuteOutputFlows) GetExtension() []*anypb.Any {
	if x != nil {
		return x.Extension
	}
	return nil
}

// Resolves all datasets and flows and start a pipeline update. Should be called after all
// graph elements are registered.
type PipelineCommand_StartRun struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The graph to start.
	DataflowGraphId *string `protobuf:"bytes,1,opt,name=dataflow_graph_id,json=dataflowGraphId,proto3,oneof" json:"dataflow_graph_id,omitempty"`
	// List of dataset to reset and recompute.
	FullRefreshSelection []string `protobuf:"bytes,2,rep,name=full_refresh_selection,json=fullRefreshSelection,proto3" json:"full_refresh_selection,omitempty"`
	// Perform a full graph reset and recompute.
	FullRefreshAll *bool `protobuf:"varint,3,opt,name=full_refresh_all,json=fullRefreshAll,proto3,oneof" json:"full_refresh_all,omitempty"`
	// List of dataset to update.
	RefreshSelection []string `protobuf:"bytes,4,rep,name=refresh_selection,json=refreshSelection,proto3" json:"refresh_selection,omitempty"`
	// If true, the run will not actually execute any flows, but will only validate the graph and
	// check for any errors. This is useful for testing and validation purposes.
	Dry *bool `protobuf:"varint,5,opt,name=dry,proto3,oneof" json:"dry,omitempty"`
	// storage location for pipeline checkpoints and metadata.
	Storage       *string `protobuf:"bytes,6,opt,name=storage,proto3,oneof" json:"storage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PipelineCommand_StartRun) Reset() {
	*x = PipelineCommand_StartRun{}
	mi := &file_spark_connect_pipelines_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PipelineCommand_StartRun) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PipelineCommand_StartRun) ProtoMessage() {}

func (x *PipelineCommand_StartRun) ProtoReflect() protoreflect.Message {
	mi := &file_spark_connect_pipelines_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PipelineCommand_StartRun.ProtoReflect.Descriptor instead.
func (*PipelineCommand_StartRun) Descriptor() ([]byte, []int) {
	return file_spark_connect_pipelines_proto_rawDescGZIP(), []int{0, 5}
}

func (x *PipelineCommand_StartRun) GetDataflowGraphId() string {
	if x != nil && x.DataflowGraphId != nil {
		return *x.DataflowGraphId
	}
	return ""
}

func (x *PipelineCommand_StartRun) GetFullRefreshSelection() []string {
	if x != nil {
		return x.FullRefreshSelection
	}
	return nil
}

func (x *PipelineCommand_StartRun) GetFullRefreshAll() bool {
	if x != nil && x.FullRefreshAll != nil {
		return *x.FullRefreshAll
	}
	return false
}

func (x *PipelineCommand_StartRun) GetRefreshSelection() []string {
	if x != nil {
		return x.RefreshSelection
	}
	return nil
}

func (x *PipelineCommand_StartRun) GetDry() bool {
	if x != nil && x.Dry != nil {
		return *x.Dry
	}
	return false
}

func (x *PipelineCommand_StartRun) GetStorage() string {
	if x != nil && x.Storage != nil {
		return *x.Storage
	}
	return ""
}

// Parses the SQL file and registers all datasets and flows.
type PipelineCommand_DefineSqlGraphElements struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The graph to attach this dataset to.
	DataflowGraphId *string `protobuf:"bytes,1,opt,name=dataflow_graph_id,json=dataflowGraphId,proto3,oneof" json:"dataflow_graph_id,omitempty"`
	// The full path to the SQL file. Can be relative or absolute.
	SqlFilePath *string `protobuf:"bytes,2,opt,name=sql_file_path,json=sqlFilePath,proto3,oneof" json:"sql_file_path,omitempty"`
	// The contents of the SQL file.
	SqlText       *string `protobuf:"bytes,3,opt,name=sql_text,json=sqlText,proto3,oneof" json:"sql_text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PipelineCommand_DefineSqlGraphElements) Reset() {
	*x = PipelineCommand_DefineSqlGraphElements{}
	mi := &file_spark_connect_pipelines_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PipelineCommand_DefineSqlGraphElements) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PipelineCommand_DefineSqlGraphElements) ProtoMessage() {}

func (x *PipelineCommand_DefineSqlGraphElements) ProtoReflect() protoreflect.Message {
	mi := &file_spark_connect_pipelines_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PipelineCommand_DefineSqlGraphElements.ProtoReflect.Descriptor instead.
func (*PipelineCommand_DefineSqlGraphElements) Descriptor() ([]byte, []int) {
	return file_spark_connect_pipelines_proto_rawDescGZIP(), []int{0, 6}
}

func (x *PipelineCommand_DefineSqlGraphElements) GetDataflowGraphId() string {
	if x != nil && x.DataflowGraphId != nil {
		return *x.DataflowGraphId
	}
	return ""
}

func (x *PipelineCommand_DefineSqlGraphElements) GetSqlFilePath() string {
	if x != nil && x.SqlFilePath != nil {
		return *x.SqlFilePath
	}
	return ""
}

func (x *PipelineCommand_DefineSqlGraphElements) GetSqlText() string {
	if x != nil && x.SqlText != nil {
		return *x.SqlText
	}
	return ""
}

// Request to get the stream of query function execution signals for a graph. Responses should
// be a stream of PipelineQueryFunctionExecutionSignal messages.
type PipelineCommand_GetQueryFunctionExecutionSignalStream struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The graph to get the query function execution signal stream for.
	DataflowGraphId *string `protobuf:"bytes,1,opt,name=dataflow_graph_id,json=dataflowGraphId,proto3,oneof" json:"dataflow_graph_id,omitempty"`
	// Identifier for the client that is requesting the stream.
	ClientId      *string `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3,oneof" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PipelineCommand_GetQueryFunctionExecutionSignalStream) Reset() {
	*x = PipelineCommand_GetQueryFunctionExecutionSignalStream{}
	mi := &file_spark_connect_pipelines_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PipelineCommand_GetQueryFunctionExecutionSignalStream) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PipelineCommand_GetQueryFunctionExecutionSignalStream) ProtoMessage() {}

func (x *PipelineCommand_GetQueryFunctionExecutionSignalStream) ProtoReflect() protoreflect.Message {
	mi := &file_spark_connect_pipelines_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PipelineCommand_GetQueryFunctionExecutionSignalStream.ProtoReflect.Descriptor instead.
func (*PipelineCommand_GetQueryFunctionExecutionSignalStream) Descriptor() ([]byte, []int) {
	return file_spark_connect_pipelines_proto_rawDescGZIP(), []int{0, 7}
}

func (x *PipelineCommand_GetQueryFunctionExecutionSignalStream) GetDataflowGraphId() string {
	if x != nil && x.DataflowGraphId != nil {
		return *x.DataflowGraphId
	}
	return ""
}

func (x *PipelineCommand_GetQueryFunctionExecutionSignalStream) GetClientId() string {
	if x != nil && x.ClientId != nil {
		return *x.ClientId
	}
	return ""
}

// Request from the client to update the flow function evaluation result
// for a previously un-analyzed flow.
type PipelineCommand_DefineFlowQueryFunctionResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// (Deprecated) The fully qualified name of the flow being updated.
	//
	// This field is deprecated since Spark 4.2+. Use flow_identifier field instead.
	//
	// Deprecated: Marked as deprecated in spark/connect/pipelines.proto.
	FlowName *string `protobuf:"bytes,1,opt,name=flow_name,json=flowName,proto3,oneof" json:"flow_name,omitempty"`
	// The fully qualified identifier of the flow being updated.
	FlowIdentifier *ResolvedIdentifier `protobuf:"bytes,4,opt,name=flow_identifier,json=flowIdentifier,proto3,oneof" json:"flow_identifier,omitempty"`
	// The ID of the graph this flow belongs to.
	DataflowGraphId *string `protobuf:"bytes,2,opt,name=dataflow_graph_id,json=dataflowGraphId,proto3,oneof" json:"dataflow_graph_id,omitempty"`
	// An unresolved relation that defines the dataset's flow.
	Relation      *Relation `protobuf:"bytes,3,opt,name=relation,proto3,oneof" json:"relation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PipelineCommand_DefineFlowQueryFunctionResult) Reset() {
	*x = PipelineCommand_DefineFlowQueryFunctionResult{}
	mi := &file_spark_connect_pipelines_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PipelineCommand_DefineFlowQueryFunctionResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PipelineCommand_DefineFlowQueryFunctionResult) ProtoMessage() {}

func (x *PipelineCommand_DefineFlowQueryFunctionResult) ProtoReflect() protoreflect.Message {
	mi := &file_spark_connect_pipelines_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PipelineCommand_DefineFlowQueryFunctionResult.ProtoReflect.Descriptor instead.
func (*PipelineCommand_DefineFlowQueryFunctionResult) Descriptor() ([]byte, []int) {
	return file_spark_connect_pipelines_proto_rawDescGZIP(), []int{0, 8}
}

// Deprecated: Marked as deprecated in spark/connect/pipelines.proto.
func (x *PipelineCommand_DefineFlowQueryFunctionResult) GetFlowName() string {
	if x != nil && x.FlowName != nil {
		return *x.FlowName
	}
	return ""
}

func (x *PipelineCommand_DefineFlowQueryFunctionResult) GetFlowIdentifier() *ResolvedIdentifier {
	if x != nil {
		return x.FlowIdentifier
	}
	return nil
}

func (x *PipelineCommand_DefineFlowQueryFunctionResult) GetDataflowGraphId() string {
	if x != nil && x.DataflowGraphId != nil {
		return *x.DataflowGraphId
	}
	return ""
}

func (x *PipelineCommand_DefineFlowQueryFunctionResult) GetRelation() *Relation {
	if x != nil {
		return x.Relation
	}
	return nil
}

// Metadata that's only applicable to tables and materialized views.
type PipelineCommand_DefineOutput_TableDetails struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional table properties.
	TableProperties map[string]string `protobuf:"bytes,1,rep,name=table_properties,json=tableProperties,proto3" json:"table_properties,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Optional partition columns for the table.
	PartitionCols []string `protobuf:"bytes,2,rep,name=partition_cols,json=partitionCols,proto3" json:"partition_cols,omitempty"`
	// The output table format for the table.
	Format *string `protobuf:"bytes,3,opt,name=format,proto3,oneof" json:"format,omitempty"`
	// Schema for the table. If unset, this will be inferred from incoming flows.
	//
	// Types that are valid to be assigned to Schema:
	//
	//	*PipelineCommand_DefineOutput_TableDetails_SchemaDataType
	//	*PipelineCommand_DefineOutput_TableDetails_SchemaString
	Schema isPipelineCommand_DefineOutput_TableDetails_Schema `protobuf_oneof:"schema"`
	// Optional cluster columns for the table.
	ClusteringColumns []string `protobuf:"bytes,6,rep,name=clustering_columns,json=clusteringColumns,proto3" json:"clustering_columns,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PipelineCommand_DefineOutput_TableDetails) Reset() {
	*x = PipelineCommand_DefineOutput_TableDetails{}
	mi := &file_spark_connect_pipelines_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PipelineCommand_DefineOutput_TableDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PipelineCommand_DefineOutput_TableDetails) ProtoMessage() {}

func (x *PipelineCommand_DefineOutput_TableDetails) ProtoReflect() protoreflect.Message {
	mi := &file_spark_connect_pipelines_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PipelineCommand_DefineOutput_TableDetails.ProtoReflect.Descriptor instead.
func (*PipelineCommand_DefineOutput_TableDetails) Descriptor() ([]byte, []int) {
	return file_spark_connect_pipelines_proto_rawDescGZIP(), []int{0, 2, 0}
}

func (x *PipelineCommand_DefineOutput_TableDetails) GetTableProperties() map[string]string {
	if x != nil {
		return x.TableProperties
	}
	return nil
}

func (x *PipelineCommand_DefineOutput_TableDetails) GetPartitionCols() []string {
	if x != nil {
		return x.PartitionCols
	}
	return nil
}

func (x *PipelineCommand_DefineOutput_TableDetails) GetFormat() string {
	if x != nil && x.Format != nil {
		return *x.Format
	}
	return ""
}

func (x *PipelineCommand_DefineOutput_TableDetails) GetSchema() isPipelineCommand_DefineOutput_TableDetails_Schema {
	if x != nil {
		return x.Schema
	}
	return nil
}

func (x *PipelineCommand_DefineOutput_TableDetails) GetSchemaDataType() *DataType {
	if x != nil {
		if x, ok := x.Schema.(*PipelineCommand_DefineOutput_TableDetails_SchemaDataType); ok {
			return x.SchemaDataType
		}
	}
	return nil
}

func (x *PipelineCommand_DefineOutput_TableDetails) GetSchemaString() string {
	if x != nil {
		if x, ok := x.Schema.(*PipelineCommand_DefineOutput_TableDetails_SchemaString); ok {
			return x.SchemaString
		}
	}
	return ""
}

func (x *PipelineCommand_DefineOutput_TableDetails) GetClusteringColumns() []string {
	if x != nil {
		return x.ClusteringColumns
	}
	return nil
}

type isPipelineCommand_DefineOutput_TableDetails_Schema interface {
	isPipelineCommand_DefineOutput_TableDetails_Schema()
}

type PipelineCommand_DefineOutput_TableDetails_SchemaDataType struct {
	SchemaDataType *DataType `protobuf:"bytes,4,opt,name=schema_data_type,json=schemaDataType,proto3,oneof"`
}

type PipelineCommand_DefineOutput_TableDetails_SchemaString struct {
	SchemaString string `protobuf:"bytes,5,opt,name=schema_string,json=schemaString,proto3,oneof"`
}

func (*PipelineCommand_DefineOutput_TableDetails_SchemaDataType) isPipelineCommand_DefineOutput_TableDetails_Schema() {
}

func (*PipelineCommand_DefineOutput_TableDetails_SchemaString) isPipelineCommand_DefineOutput_TableDetails_Schema() {
}

// Metadata that's only applicable to sinks.
type PipelineCommand_DefineOutput_SinkDetails struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Streaming write options
	Options map[string]string `protobuf:"bytes,1,rep,name=options,proto3" json:"options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Streaming write format
	Format        *string `protobuf:"bytes,2,opt,name=format,proto3,oneof" json:"format,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PipelineCommand_DefineOutput_SinkDetails) Reset() {
	*x = PipelineCommand_DefineOutput_SinkDetails{}
	mi := &file_spark_connect_pipelines_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PipelineCommand_DefineOutput_SinkDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PipelineCommand_DefineOutput_SinkDetails) ProtoMessage() {}

func (x *PipelineCommand_DefineOutput_SinkDetails) ProtoReflect() protoreflect.Message {
	mi := &file_spark_connect_pipelines_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PipelineCommand_DefineOutput_SinkDetails.ProtoReflect.Descriptor instead.
func (*PipelineCommand_DefineOutput_SinkDetails) Descriptor() ([]byte, []int) {
	return file_spark_connect_pipelines_proto_rawDescGZIP(), []int{0, 2, 1}
}

func (x *PipelineCommand_DefineOutput_SinkDetails) GetOptions() map[string]string {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *PipelineCommand_DefineOutput_SinkDetails) GetFormat() string {
	if x != nil && x.Format != nil {
		return *x.Format
	}
	return ""
}

// A flow that is that takes the contents of a relation and writes it to the target dataset.
type PipelineCommand_DefineFlow_WriteRelationFlowDetails struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// An unresolved relation that defines the dataset's flow. Empty if the query function
	// that defines the flow cannot be analyzed at the time of flow definition.
	Relation      *Relation `protobuf:"bytes,1,opt,name=relation,proto3,oneof" json:"relation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PipelineCommand_DefineFlow_WriteRelationFlowDetails) Reset() {
	*x = PipelineCommand_DefineFlow_WriteRelationFlowDetails{}
	mi := &file_spark_connect_pipelines_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PipelineCommand_DefineFlow_WriteRelationFlowDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PipelineCommand_DefineFlow_WriteRelationFlowDetails) ProtoMessage() {}

func (x *PipelineCommand_DefineFlow_WriteRelationFlowDetails) ProtoReflect() protoreflect.Message {
	mi := &file_spark_connect_pipelines_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PipelineCommand_DefineFlow_WriteRelationFlowDetails.ProtoReflect.Descriptor instead.
func (*PipelineCommand_DefineFlow_WriteRelationFlowDetails) Descriptor() ([]byte, []int) {
	return file_spark_connect_pipelines_proto_rawDescGZIP(), []int{0, 3, 1}
}

func (x *PipelineCommand_DefineFlow_WriteRelationFlowDetails) GetRelation() *Relation {
	if x != nil {
		return x.Relation
	}
	return nil
}

type PipelineCommand_DefineFlow_Response struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Fully qualified flow name that uniquely identify a flow in the Dataflow graph.
	FlowName      *string `protobuf:"bytes,1,opt,name=flow_name,json=flowName,proto3,oneof" json:"flow_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PipelineCommand_DefineFlow_Response) Reset() {
	*x = PipelineCommand_DefineFlow_Response{}
	mi := &file_spark_connect_pipelines_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PipelineCommand_DefineFlow_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PipelineCommand_DefineFlow_Response) ProtoMessage() {}

func (x *PipelineCommand_DefineFlow_Response) ProtoReflect() protoreflect.Message {
	mi := &file_spark_connect_pipelines_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PipelineCommand_DefineFlow_Response.ProtoReflect.Descriptor instead.
func (*PipelineCommand_DefineFlow_Response) Descriptor() ([]byte, []int) {
	return file_spark_connect_pipelines_proto_rawDescGZIP(), []int{0, 3, 2}
}

func (x *PipelineCommand_DefineFlow_Response) GetFlowName() string {
	if x != nil && x.FlowName != nil {
		return *x.FlowName
	}
	return ""
}

type PipelineCommandResult_CreateDataflowGraphResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The ID of the created graph.
	DataflowGraphId *string `protobuf:"bytes,1,opt,name=dataflow_graph_id,json=dataflowGraphId,proto3,oneof" json:"dataflow_graph_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PipelineCommandResult_CreateDataflowGraphResult) Reset() {
	*x = PipelineCommandResult_CreateDataflowGraphResult{}
	mi := &file_spark_connect_pipelines_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PipelineCommandResult_CreateDataflowGraphResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PipelineCommandResult_CreateDataflowGraphResult) ProtoMessage() {}

func (x *PipelineCommandResult_CreateDataflowGraphResult) ProtoReflect() protoreflect.Message {
	mi := &file_spark_connect_pipelines_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PipelineCommandResult_CreateDataflowGraphResult.ProtoReflect.Descriptor instead.
func (*PipelineCommandResult_CreateDataflowGraphResult) Descriptor() ([]byte, []int) {
	return file_spark_connect_pipelines_proto_rawDescGZIP(), []int{1, 0}
}

func (x *PipelineCommandResult_CreateDataflowGraphResult) GetDataflowGraphId() string {
	if x != nil && x.DataflowGraphId != nil {
		return *x.DataflowGraphId
	}
	return ""
}

type PipelineCommandResult_DefineOutputResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Resolved identifier of the output
	ResolvedIdentifier *ResolvedIdentifier `protobuf:"bytes,1,opt,name=resolved_identifier,json=resolvedIdentifier,proto3,oneof" json:"resolved_identifier,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *PipelineCommandResult_DefineOutputResult) Reset() {
	*x = PipelineCommandResult_DefineOutputResult{}
	mi := &file_spark_connect_pipelines_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PipelineCommandResult_DefineOutputResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PipelineCommandResult_DefineOutputResult) ProtoMessage() {}

func (x *PipelineCommandResult_DefineOutputResult) ProtoReflect() protoreflect.Message {
	mi := &file_spark_connect_pipelines_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PipelineCommandResult_DefineOutputResult.ProtoReflect.Descriptor instead.
func (*PipelineCommandResult_DefineOutputResult) Descriptor() ([]byte, []int) {
	return file_spark_connect_pipelines_proto_rawDescGZIP(), []int{1, 1}
}

func (x *PipelineCommandResult_DefineOutputResult) GetResolvedIdentifier() *ResolvedIdentifier {
	if x != nil {
		return x.ResolvedIdentifier
	}
	return nil
}

type PipelineCommandResult_DefineFlowResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Resolved identifier of the flow
	ResolvedIdentifier *ResolvedIdentifier `protobuf:"bytes,1,opt,name=resolved_identifier,json=resolvedIdentifier,proto3,oneof" json:"resolved_identifier,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *PipelineCommandResult_DefineFlowResult) Reset() {
	*x = PipelineCommandResult_DefineFlowResult{}
	mi := &file_spark_connect_pipelines_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PipelineCommandResult_DefineFlowResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PipelineCommandResult_DefineFlowResult) ProtoMessage() {}

func (x *PipelineCommandResult_DefineFlowResult) ProtoReflect() protoreflect.Message {
	mi := &file_spark_connect_pipelines_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PipelineCommandResult_DefineFlowResult.ProtoReflect.Descriptor instead.
func (*PipelineCommandResult_DefineFlowResult) Descriptor() ([]byte, []int) {
	return file_spark_connect_pipelines_proto_rawDescGZIP(), []int{1, 2}
}

func (x *PipelineCommandResult_DefineFlowResult) GetResolvedIdentifier() *ResolvedIdentifier {
	if x != nil {
		return x.ResolvedIdentifier
	}
	return nil
}

var File_spark_connect_pipelines_proto protoreflect.FileDescriptor

const file_spark_connect_pipelines_proto_rawDesc = "" +
	"\n" +
	"\x1dspark/connect/pipelines.proto\x12\rspark.connect\x1a\x19google/protobuf/any.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1aspark/connect/common.proto\x1a\x1dspark/connect/relations.proto\x1a\x19spark/connect/types.proto\"\xa4'\n" +
	"\x0fPipelineCommand\x12h\n" +
	"\x15create_dataflow_graph\x18\x01 \x01(\v22.spark.connect.PipelineCommand.CreateDataflowGraphH\x00R\x13createDataflowGraph\x12R\n" +
	"\rdefine_output\x18\x02 \x01(\v2+.spark.connect.PipelineCommand.DefineOutputH\x00R\fdefineOutput\x12L\n" +
	"\vdefine_flow\x18\x03 \x01(\v2).spark.connect.PipelineCommand.DefineFlowH\x00R\n" +
	"defineFlow\x12b\n" +
	"\x13drop_dataflow_graph\x18\x04 \x01(\v20.spark.connect.PipelineCommand.DropDataflowGraphH\x00R\x11dropDataflowGraph\x12F\n" +
	"\tstart_run\x18\x05 \x01(\v2'.spark.connect.PipelineCommand.StartRunH\x00R\bstartRun\x12r\n" +
	"\x19define_sql_graph_elements\x18\x06 \x01(\v25.spark.connect.PipelineCommand.DefineSqlGraphElementsH\x00R\x16defineSqlGraphElements\x12\xa1\x01\n" +
	"*get_query_function_execution_signal_stream\x18\a \x01(\v2D.spark.connect.PipelineCommand.GetQueryFunctionExecutionSignalStreamH\x00R%getQueryFunctionExecutionSignalStream\x12\x88\x01\n" +
	"!define_flow_query_function_result\x18\b \x01(\v2<.spark.connect.PipelineCommand.DefineFlowQueryFunctionResultH\x00R\x1ddefineFlowQueryFunctionResult\x12e\n" +
	"\x14execute_output_flows\x18\t \x01(\v21.spark.connect.PipelineCommand.ExecuteOutputFlowsH\x00R\x12executeOutputFlows\x125\n" +
	"\textension\x18\xe7\a \x01(\v2\x14.google.protobuf.AnyH\x00R\textension\x1a\xb4\x02\n" +
	"\x13CreateDataflowGraph\x12,\n" +
	"\x0fdefault_catalog\x18\x01 \x01(\tH\x00R\x0edefaultCatalog\x88\x01\x01\x12.\n" +
	"\x10default_database\x18\x02 \x01(\tH\x01R\x0fdefaultDatabase\x88\x01\x01\x12Z\n" +
	"\bsql_conf\x18\x05 \x03(\v2?.spark.connect.PipelineCommand.CreateDataflowGraph.SqlConfEntryR\asqlConf\x1a:\n" +
	"\fSqlConfEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x12\n" +
	"\x10_default_catalogB\x13\n" +
	"\x11_default_database\x1aZ\n" +
	"\x11DropDataflowGraph\x12/\n" +
	"\x11dataflow_graph_id\x18\x01 \x01(\tH\x00R\x0fdataflowGraphId\x88\x01\x01B\x14\n" +
	"\x12_dataflow_graph_id\x1a\x92\n" +
	"\n" +
	"\fDefineOutput\x12/\n" +
	"\x11dataflow_graph_id\x18\x01 \x01(\tH\x01R\x0fdataflowGraphId\x88\x01\x01\x12$\n" +
	"\voutput_name\x18\x02 \x01(\tH\x02R\n" +
	"outputName\x88\x01\x01\x12?\n" +
	"\voutput_type\x18\x03 \x01(\x0e2\x19.spark.connect.OutputTypeH\x03R\n" +
	"outputType\x88\x01\x01\x12\x1d\n" +
	"\acomment\x18\x04 \x01(\tH\x04R\acomment\x88\x01\x01\x12X\n" +
	"\x14source_code_location\x18\x05 \x01(\v2!.spark.connect.SourceCodeLocationH\x05R\x12sourceCodeLocation\x88\x01\x01\x12_\n" +
	"\rtable_details\x18\x06 \x01(\v28.spark.connect.PipelineCommand.DefineOutput.TableDetailsH\x00R\ftableDetails\x12\\\n" +
	"\fsink_details\x18\a \x01(\v27.spark.connect.PipelineCommand.DefineOutput.SinkDetailsH\x00R\vsinkDetails\x125\n" +
	"\textension\x18\xe7\a \x01(\v2\x14.google.protobuf.AnyH\x00R\textension\x1a\xc0\x03\n" +
	"\fTableDetails\x12x\n" +
	"\x10table_properties\x18\x01 \x03(\v2M.spark.connect.PipelineCommand.DefineOutput.TableDetails.TablePropertiesEntryR\x0ftableProperties\x12%\n" +
	"\x0epartition_cols\x18\x02 \x03(\tR\rpartitionCols\x12\x1b\n" +
	"\x06format\x18\x03 \x01(\tH\x01R\x06format\x88\x01\x01\x12C\n" +
	"\x10schema_data_type\x18\x04 \x01(\v2\x17.spark.connect.DataTypeH\x00R\x0eschemaDataType\x12%\n" +
	"\rschema_string\x18\x05 \x01(\tH\x00R\fschemaString\x12-\n" +
	"\x12clustering_columns\x18\x06 \x03(\tR\x11clusteringColumns\x1aB\n" +
	"\x14TablePropertiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\b\n" +
	"\x06schemaB\t\n" +
	"\a_format\x1a\xd1\x01\n" +
	"\vSinkDetails\x12^\n" +
	"\aoptions\x18\x01 \x03(\v2D.spark.connect.PipelineCommand.DefineOutput.SinkDetails.OptionsEntryR\aoptions\x12\x1b\n" +
	"\x06format\x18\x02 \x01(\tH\x00R\x06format\x88\x01\x01\x1a:\n" +
	"\fOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\t\n" +
	"\a_formatB\t\n" +
	"\adetailsB\x14\n" +
	"\x12_dataflow_graph_idB\x0e\n" +
	"\f_output_nameB\x0e\n" +
	"\f_output_typeB\n" +
	"\n" +
	"\b_commentB\x17\n" +
	"\x15_source_code_location\x1a\xff\x06\n" +
	"\n" +
	"DefineFlow\x12/\n" +
	"\x11dataflow_graph_id\x18\x01 \x01(\tH\x01R\x0fdataflowGraphId\x88\x01\x01\x12 \n" +
	"\tflow_name\x18\x02 \x01(\tH\x02R\bflowName\x88\x01\x01\x123\n" +
	"\x13target_dataset_name\x18\x03 \x01(\tH\x03R\x11targetDatasetName\x88\x01\x01\x12Q\n" +
	"\bsql_conf\x18\x04 \x03(\v26.spark.connect.PipelineCommand.DefineFlow.SqlConfEntryR\asqlConf\x12 \n" +
	"\tclient_id\x18\x05 \x01(\tH\x04R\bclientId\x88\x01\x01\x12X\n" +
	"\x14source_code_location\x18\x06 \x01(\v2!.spark.connect.SourceCodeLocationH\x05R\x12sourceCodeLocation\x88\x01\x01\x12x\n" +
	"\x15relation_flow_details\x18\a \x01(\v2B.spark.connect.PipelineCommand.DefineFlow.WriteRelationFlowDetailsH\x00R\x13relationFlowDetails\x125\n" +
	"\textension\x18\xe7\a \x01(\v2\x14.google.protobuf.AnyH\x00R\textension\x12\x17\n" +
	"\x04once\x18\b \x01(\bH\x06R\x04once\x88\x01\x01\x1a:\n" +
	"\fSqlConfEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aa\n" +
	"\x18WriteRelationFlowDetails\x128\n" +
	"\brelation\x18\x01 \x01(\v2\x17.spark.connect.RelationH\x00R\brelation\x88\x01\x01B\v\n" +
	"\t_relation\x1a:\n" +
	"\bResponse\x12 \n" +
	"\tflow_name\x18\x01 \x01(\tH\x00R\bflowName\x88\x01\x01B\f\n" +
	"\n" +
	"_flow_nameB\t\n" +
	"\adetailsB\x14\n" +
	"\x12_dataflow_graph_idB\f\n" +
	"\n" +
	"_flow_nameB\x16\n" +
	"\x14_target_dataset_nameB\f\n" +
	"\n" +
	"_client_idB\x17\n" +
	"\x15_source_code_locationB\a\n" +
	"\x05_once\x1a\xe4\x02\n" +
	"\x12ExecuteOutputFlows\x12U\n" +
	"\rdefine_output\x18\x01 \x01(\v2+.spark.connect.PipelineCommand.DefineOutputH\x00R\fdefineOutput\x88\x01\x01\x12L\n" +
	"\fdefine_flows\x18\x02 \x03(\v2).spark.connect.PipelineCommand.DefineFlowR\vdefineFlows\x12&\n" +
	"\ffull_refresh\x18\x03 \x01(\bH\x01R\vfullRefresh\x88\x01\x01\x12\x1d\n" +
	"\astorage\x18\x04 \x01(\tH\x02R\astorage\x88\x01\x01\x123\n" +
	"\textension\x18\xe7\a \x03(\v2\x14.google.protobuf.AnyR\textensionB\x10\n" +
	"\x0e_define_outputB\x0f\n" +
	"\r_full_refreshB\n" +
	"\n" +
	"\b_storage\x1a\xc2\x02\n" +
	"\bStartRun\x12/\n" +
	"\x11dataflow_graph_id\x18\x01 \x01(\tH\x00R\x0fdataflowGraphId\x88\x01\x01\x124\n" +
	"\x16full_refresh_selection\x18\x02 \x03(\tR\x14fullRefreshSelection\x12-\n" +
	"\x10full_refresh_all\x18\x03 \x01(\bH\x01R\x0efullRefreshAll\x88\x01\x01\x12+\n" +
	"\x11refresh_selection\x18\x04 \x03(\tR\x10refreshSelection\x12\x15\n" +
	"\x03dry\x18\x05 \x01(\bH\x02R\x03dry\x88\x01\x01\x12\x1d\n" +
	"\astorage\x18\x06 \x01(\tH\x03R\astorage\x88\x01\x01B\x14\n" +
	"\x12_dataflow_graph_idB\x13\n" +
	"\x11_full_refresh_allB\x06\n" +
	"\x04_dryB\n" +
	"\n" +
	"\b_storage\x1a\xc7\x01\n" +
	"\x16DefineSqlGraphElements\x12/\n" +
	"\x11dataflow_graph_id\x18\x01 \x01(\tH\x00R\x0fdataflowGraphId\x88\x01\x01\x12'\n" +
	"\rsql_file_path\x18\x02 \x01(\tH\x01R\vsqlFilePath\x88\x01\x01\x12\x1e\n" +
	"\bsql_text\x18\x03 \x01(\tH\x02R\asqlText\x88\x01\x01B\x14\n" +
	"\x12_dataflow_graph_idB\x10\n" +
	"\x0e_sql_file_pathB\v\n" +
	"\t_sql_text\x1a\x9e\x01\n" +
	"%GetQueryFunctionExecutionSignalStream\x12/\n" +
	"\x11dataflow_graph_id\x18\x01 \x01(\tH\x00R\x0fdataflowGraphId\x88\x01\x01\x12 \n" +
	"\tclient_id\x18\x02 \x01(\tH\x01R\bclientId\x88\x01\x01B\x14\n" +
	"\x12_dataflow_graph_idB\f\n" +
	"\n" +
	"_client_id\x1a\xc6\x02\n" +
	"\x1dDefineFlowQueryFunctionResult\x12$\n" +
	"\tflow_name\x18\x01 \x01(\tB\x02\x18\x01H\x00R\bflowName\x88\x01\x01\x12O\n" +
	"\x0fflow_identifier\x18\x04 \x01(\v2!.spark.connect.ResolvedIdentifierH\x01R\x0eflowIdentifier\x88\x01\x01\x12/\n" +
	"\x11dataflow_graph_id\x18\x02 \x01(\tH\x02R\x0fdataflowGraphId\x88\x01\x01\x128\n" +
	"\brelation\x18\x03 \x01(\v2\x17.spark.connect.RelationH\x03R\brelation\x88\x01\x01B\f\n" +
	"\n" +
	"_flow_nameB\x12\n" +
	"\x10_flow_identifierB\x14\n" +
	"\x12_dataflow_graph_idB\v\n" +
	"\t_relationB\x0e\n" +
	"\fcommand_type\"\xf0\x05\n" +
	"\x15PipelineCommandResult\x12\x81\x01\n" +
	"\x1ccreate_dataflow_graph_result\x18\x01 \x01(\v2>.spark.connect.PipelineCommandResult.CreateDataflowGraphResultH\x00R\x19createDataflowGraphResult\x12k\n" +
	"\x14define_output_result\x18\x02 \x01(\v27.spark.connect.PipelineCommandResult.DefineOutputResultH\x00R\x12defineOutputResult\x12e\n" +
	"\x12define_flow_result\x18\x03 \x01(\v25.spark.connect.PipelineCommandResult.DefineFlowResultH\x00R\x10defineFlowResult\x1ab\n" +
	"\x19CreateDataflowGraphResult\x12/\n" +
	"\x11dataflow_graph_id\x18\x01 \x01(\tH\x00R\x0fdataflowGraphId\x88\x01\x01B\x14\n" +
	"\x12_dataflow_graph_id\x1a\x85\x01\n" +
	"\x12DefineOutputResult\x12W\n" +
	"\x13resolved_identifier\x18\x01 \x01(\v2!.spark.connect.ResolvedIdentifierH\x00R\x12resolvedIdentifier\x88\x01\x01B\x16\n" +
	"\x14_resolved_identifier\x1a\x83\x01\n" +
	"\x10DefineFlowResult\x12W\n" +
	"\x13resolved_identifier\x18\x01 \x01(\v2!.spark.connect.ResolvedIdentifierH\x00R\x12resolvedIdentifier\x88\x01\x01B\x16\n" +
	"\x14_resolved_identifierB\r\n" +
	"\vresult_type\"I\n" +
	"\x13PipelineEventResult\x122\n" +
	"\x05event\x18\x01 \x01(\v2\x1c.spark.connect.PipelineEventR\x05event\"t\n" +
	"\rPipelineEvent\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x1d\n" +
	"\amessage\x18\x02 \x01(\tH\x00R\amessage\x88\x01\x01B\n" +
	"\n" +
	"\b_message\"\xf1\x01\n" +
	"\x12SourceCodeLocation\x12 \n" +
	"\tfile_name\x18\x01 \x01(\tH\x00R\bfileName\x88\x01\x01\x12$\n" +
	"\vline_number\x18\x02 \x01(\x05H\x01R\n" +
	"lineNumber\x88\x01\x01\x12,\n" +
	"\x0fdefinition_path\x18\x03 \x01(\tH\x02R\x0edefinitionPath\x88\x01\x01\x123\n" +
	"\textension\x18\xe7\a \x03(\v2\x14.google.protobuf.AnyR\textensionB\f\n" +
	"\n" +
	"_file_nameB\x0e\n" +
	"\f_line_numberB\x12\n" +
	"\x10_definition_path\"\x97\x01\n" +
	"$PipelineQueryFunctionExecutionSignal\x12!\n" +
	"\n" +
	"flow_names\x18\x01 \x03(\tB\x02\x18\x01R\tflowNames\x12L\n" +
	"\x10flow_identifiers\x18\x02 \x03(\v2!.spark.connect.ResolvedIdentifierR\x0fflowIdentifiers\"\xf0\x02\n" +
	"\x17PipelineAnalysisContext\x12/\n" +
	"\x11dataflow_graph_id\x18\x01 \x01(\tH\x00R\x0fdataflowGraphId\x88\x01\x01\x12,\n" +
	"\x0fdefinition_path\x18\x02 \x01(\tH\x01R\x0edefinitionPath\x88\x01\x01\x12$\n" +
	"\tflow_name\x18\x03 \x01(\tB\x02\x18\x01H\x02R\bflowName\x88\x01\x01\x12O\n" +
	"\x0fflow_identifier\x18\x04 \x01(\v2!.spark.connect.ResolvedIdentifierH\x03R\x0eflowIdentifier\x88\x01\x01\x123\n" +
	"\textension\x18\xe7\a \x03(\v2\x14.google.protobuf.AnyR\textensionB\x14\n" +
	"\x12_dataflow_graph_idB\x12\n" +
	"\x10_definition_pathB\f\n" +
	"\n" +
	"_flow_nameB\x12\n" +
	"\x10_flow_identifier*i\n" +
	"\n" +
	"OutputType\x12\x1b\n" +
	"\x17OUTPUT_TYPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11MATERIALIZED_VIEW\x10\x01\x12\t\n" +
	"\x05TABLE\x10\x02\x12\x12\n" +
	"\x0eTEMPORARY_VIEW\x10\x03\x12\b\n" +
	"\x04SINK\x10\x04B6\n" +
	"\x1eorg.apache.spark.connect.protoP\x01Z\x12internal/generatedb\x06proto3"

var (
	file_spark_connect_pipelines_proto_rawDescOnce sync.Once
	file_spark_connect_pipelines_proto_rawDescData []byte
)

func file_spark_connect_pipelines_proto_rawDescGZIP() []byte {
	file_spark_connect_pipelines_proto_rawDescOnce.Do(func() {
		file_spark_connect_pipelines_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_spark_connect_pipelines_proto_rawDesc), len(file_spark_connect_pipelines_proto_rawDesc)))
	})
	return file_spark_connect_pipelines_proto_rawDescData
}

var file_spark_connect_pipelines_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_spark_connect_pipelines_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_spark_connect_pipelines_proto_goTypes = []any{
	(OutputType)(0),                                               // 0: spark.connect.OutputType
	(*PipelineCommand)(nil),                                       // 1: spark.connect.PipelineCommand
	(*PipelineCommandResult)(nil),                                 // 2: spark.connect.PipelineCommandResult
	(*PipelineEventResult)(nil),                                   // 3: spark.connect.PipelineEventResult
	(*PipelineEvent)(nil),                                         // 4: spark.connect.PipelineEvent
	(*SourceCodeLocation)(nil),                                    // 5: spark.connect.SourceCodeLocation
	(*PipelineQueryFunctionExecutionSignal)(nil),                  // 6: spark.connect.PipelineQueryFunctionExecutionSignal
	(*PipelineAnalysisContext)(nil),                               // 7: spark.connect.PipelineAnalysisContext
	(*PipelineCommand_CreateDataflowGraph)(nil),                   // 8: spark.connect.PipelineCommand.CreateDataflowGraph
	(*PipelineCommand_DropDataflowGraph)(nil),                     // 9: spark.connect.PipelineCommand.DropDataflowGraph
	(*PipelineCommand_DefineOutput)(nil),                          // 10: spark.connect.PipelineCommand.DefineOutput
	(*PipelineCommand_DefineFlow)(nil),                            // 11: spark.connect.PipelineCommand.DefineFlow
	(*PipelineCommand_ExecuteOutputFlows)(nil),                    // 12: spark.connect.PipelineCommand.ExecuteOutputFlows
	(*PipelineCommand_StartRun)(nil),                              // 13: spark.connect.PipelineCommand.StartRun
	(*PipelineCommand_DefineSqlGraphElements)(nil),                // 14: spark.connect.PipelineCommand.DefineSqlGraphElements
	(*PipelineCommand_GetQueryFunctionExecutionSignalStream)(nil), // 15: spark.connect.PipelineCommand.GetQueryFunctionExecutionSignalStream
	(*PipelineCommand_DefineFlowQueryFunctionResult)(nil),         // 16: spark.connect.PipelineCommand.DefineFlowQueryFunctionResult
	nil, // 17: spark.connect.PipelineCommand.CreateDataflowGraph.SqlConfEntry
	(*PipelineCommand_DefineOutput_TableDetails)(nil), // 18: spark.connect.PipelineCommand.DefineOutput.TableDetails
	(*PipelineCommand_DefineOutput_SinkDetails)(nil),  // 19: spark.connect.PipelineCommand.DefineOutput.SinkDetails
	nil, // 20: spark.connect.PipelineCommand.DefineOutput.TableDetails.TablePropertiesEntry
	nil, // 21: spark.connect.PipelineCommand.DefineOutput.SinkDetails.OptionsEntry
	nil, // 22: spark.connect.PipelineCommand.DefineFlow.SqlConfEntry
	(*PipelineCommand_DefineFlow_WriteRelationFlowDetails)(nil), // 23: spark.connect.PipelineCommand.DefineFlow.WriteRelationFlowDetails
	(*PipelineCommand_DefineFlow_Response)(nil),                 // 24: spark.connect.PipelineCommand.DefineFlow.Response
	(*PipelineCommandResult_CreateDataflowGraphResult)(nil),     // 25: spark.connect.PipelineCommandResult.CreateDataflowGraphResult
	(*PipelineCommandResult_DefineOutputResult)(nil),            // 26: spark.connect.PipelineCommandResult.DefineOutputResult
	(*PipelineCommandResult_DefineFlowResult)(nil),              // 27: spark.connect.PipelineCommandResult.DefineFlowResult
	(*anypb.Any)(nil),             // 28: google.protobuf.Any
	(*timestamppb.Timestamp)(nil), // 29: google.protobuf.Timestamp
	(*ResolvedIdentifier)(nil),    // 30: spark.connect.ResolvedIdentifier
	(*Relation)(nil),              // 31: spark.connect.Relation
	(*DataType)(nil),              // 32: spark.connect.DataType
}
var file_spark_connect_pipelines_proto_depIdxs = []int32{
	8,  // 0: spark.connect.PipelineCommand.create_dataflow_graph:type_name -> spark.connect.PipelineCommand.CreateDataflowGraph
	10, // 1: spark.connect.PipelineCommand.define_output:type_name -> spark.connect.PipelineCommand.DefineOutput
	11, // 2: spark.connect.PipelineCommand.define_flow:type_name -> spark.connect.PipelineCommand.DefineFlow
	9,  // 3: spark.connect.PipelineCommand.drop_dataflow_graph:type_name -> spark.connect.PipelineCommand.DropDataflowGraph
	13, // 4: spark.connect.PipelineCommand.start_run:type_name -> spark.connect.PipelineCommand.StartRun
	14, // 5: spark.connect.PipelineCommand.define_sql_graph_elements:type_name -> spark.connect.PipelineCommand.DefineSqlGraphElements
	15, // 6: spark.connect.PipelineCommand.get_query_function_execution_signal_stream:type_name -> spark.connect.PipelineCommand.GetQueryFunctionExecutionSignalStream
	16, // 7: spark.connect.PipelineCommand.define_flow_query_function_result:type_name -> spark.connect.PipelineCommand.DefineFlowQueryFunctionResult
	12, // 8: spark.connect.PipelineCommand.execute_output_flows:type_name -> spark.connect.PipelineCommand.ExecuteOutputFlows
	28, // 9: spark.connect.PipelineCommand.extension:type_name -> google.protobuf.Any
	25, // 10: spark.connect.PipelineCommandResult.create_dataflow_graph_result:type_name -> spark.connect.PipelineCommandResult.CreateDataflowGraphResult
	26, // 11: spark.connect.PipelineCommandResult.define_output_result:type_name -> spark.connect.PipelineCommandResult.DefineOutputResult
	27, // 12: spark.connect.PipelineCommandResult.define_flow_result:type_name -> spark.connect.PipelineCommandResult.DefineFlowResult
	4,  // 13: spark.connect.PipelineEventResult.event:type_name -> spark.connect.PipelineEvent
	29, // 14: spark.connect.PipelineEvent.timestamp:type_name -> google.protobuf.Timestamp
	28, // 15: spark.connect.SourceCodeLocation.extension:type_name -> google.protobuf.Any
	30, // 16: spark.connect.PipelineQueryFunctionExecutionSignal.flow_identifiers:type_name -> spark.connect.ResolvedIdentifier
	30, // 17: spark.connect.PipelineAnalysisContext.flow_identifier:type_name -> spark.connect.ResolvedIdentifier
	28, // 18: spark.connect.PipelineAnalysisContext.extension:type_name -> google.protobuf.Any
	17, // 19: spark.connect.PipelineCommand.CreateDataflowGraph.sql_conf:type_name -> spark.connect.PipelineCommand.CreateDataflowGraph.SqlConfEntry
	0,  // 20: spark.connect.PipelineCommand.DefineOutput.output_type:type_name -> spark.connect.OutputType
	5,  // 21: spark.connect.PipelineCommand.DefineOutput.source_code_location:type_name -> spark.connect.SourceCodeLocation
	18, // 22: spark.connect.PipelineCommand.DefineOutput.table_details:type_name -> spark.connect.PipelineCommand.DefineOutput.TableDetails
	19, // 23: spark.connect.PipelineCommand.DefineOutput.sink_details:type_name -> spark.connect.PipelineCommand.DefineOutput.SinkDetails
	28, // 24: spark.connect.PipelineCommand.DefineOutput.extension:type_name -> google.protobuf.Any
	22, // 25: spark.connect.PipelineCommand.DefineFlow.sql_conf:type_name -> spark.connect.PipelineCommand.DefineFlow.SqlConfEntry
	5,  // 26: spark.connect.PipelineCommand.DefineFlow.source_code_location:type_name -> spark.connect.SourceCodeLocation
	23, // 27: spark.connect.PipelineCommand.DefineFlow.relation_flow_details:type_name -> spark.connect.PipelineCommand.DefineFlow.WriteRelationFlowDetails
	28, // 28: spark.connect.PipelineCommand.DefineFlow.extension:type_name -> google.protobuf.Any
	10, // 29: spark.connect.PipelineCommand.ExecuteOutputFlows.define_output:type_name -> spark.connect.PipelineCommand.DefineOutput
	11, // 30: spark.connect.PipelineCommand.ExecuteOutputFlows.define_flows:type_name -> spark.connect.PipelineCommand.DefineFlow
	28, // 31: spark.connect.PipelineCommand.ExecuteOutputFlows.extension:type_name -> google.protobuf.Any
	30, // 32: spark.connect.PipelineCommand.DefineFlowQueryFunctionResult.flow_identifier:type_name -> spark.connect.ResolvedIdentifier
	31, // 33: spark.connect.PipelineCommand.DefineFlowQueryFunctionResult.relation:type_name -> spark.connect.Relation
	20, // 34: spark.connect.PipelineCommand.DefineOutput.TableDetails.table_properties:type_name -> spark.connect.PipelineCommand.DefineOutput.TableDetails.TablePropertiesEntry
	32, // 35: spark.connect.PipelineCommand.DefineOutput.TableDetails.schema_data_type:type_name -> spark.connect.DataType
	21, // 36: spark.connect.PipelineCommand.DefineOutput.SinkDetails.options:type_name -> spark.connect.PipelineCommand.DefineOutput.SinkDetails.OptionsEntry
	31, // 37: spark.connect.PipelineCommand.DefineFlow.WriteRelationFlowDetails.relation:type_name -> spark.connect.Relation
	30, // 38: spark.connect.PipelineCommandResult.DefineOutputResult.resolved_identifier:type_name -> spark.connect.ResolvedIdentifier
	30, // 39: spark.connect.PipelineCommandResult.DefineFlowResult.resolved_identifier:type_name -> spark.connect.ResolvedIdentifier
	40, // [40:40] is the sub-list for method output_type
	40, // [40:40] is the sub-list for method input_type
	40, // [40:40] is the sub-list for extension type_name
	40, // [40:40] is the sub-list for extension extendee
	0,  // [0:40] is the sub-list for field type_name
}

func init() { file_spark_connect_pipelines_proto_init() }
func file_spark_connect_pipelines_proto_init() {
	if File_spark_connect_pipelines_proto != nil {
		return
	}
	file_spark_connect_common_proto_init()
	file_spark_connect_relations_proto_init()
	file_spark_connect_types_proto_init()
	file_spark_connect_pipelines_proto_msgTypes[0].OneofWrappers = []any{
		(*PipelineCommand_CreateDataflowGraph_)(nil),
		(*PipelineCommand_DefineOutput_)(nil),
		(*PipelineCommand_DefineFlow_)(nil),
		(*PipelineCommand_DropDataflowGraph_)(nil),
		(*PipelineCommand_StartRun_)(nil),
		(*PipelineCommand_DefineSqlGraphElements_)(nil),
		(*PipelineCommand_GetQueryFunctionExecutionSignalStream_)(nil),
		(*PipelineCommand_DefineFlowQueryFunctionResult_)(nil),
		(*PipelineCommand_ExecuteOutputFlows_)(nil),
		(*PipelineCommand_Extension)(nil),
	}
	file_spark_connect_pipelines_proto_msgTypes[1].OneofWrappers = []any{
		(*PipelineCommandResult_CreateDataflowGraphResult_)(nil),
		(*PipelineCommandResult_DefineOutputResult_)(nil),
		(*PipelineCommandResult_DefineFlowResult_)(nil),
	}
	file_spark_connect_pipelines_proto_msgTypes[3].OneofWrappers = []any{}
	file_spark_connect_pipelines_proto_msgTypes[4].OneofWrappers = []any{}
	file_spark_connect_pipelines_proto_msgTypes[6].OneofWrappers = []any{}
	file_spark_connect_pipelines_proto_msgTypes[7].OneofWrappers = []any{}
	file_spark_connect_pipelines_proto_msgTypes[8].OneofWrappers = []any{}
	file_spark_connect_pipelines_proto_msgTypes[9].OneofWrappers = []any{
		(*PipelineCommand_DefineOutput_TableDetails_)(nil),
		(*PipelineCommand_DefineOutput_SinkDetails_)(nil),
		(*PipelineCommand_DefineOutput_Extension)(nil),
	}
	file_spark_connect_pipelines_proto_msgTypes[10].OneofWrappers = []any{
		(*PipelineCommand_DefineFlow_RelationFlowDetails)(nil),
		(*PipelineCommand_DefineFlow_Extension)(nil),
	}
	file_spark_connect_pipelines_proto_msgTypes[11].OneofWrappers = []any{}
	file_spark_connect_pipelines_proto_msgTypes[12].OneofWrappers = []any{}
	file_spark_connect_pipelines_proto_msgTypes[13].OneofWrappers = []any{}
	file_spark_connect_pipelines_proto_msgTypes[14].OneofWrappers = []any{}
	file_spark_connect_pipelines_proto_msgTypes[15].OneofWrappers = []any{}
	file_spark_connect_pipelines_proto_msgTypes[17].OneofWrappers = []any{
		(*PipelineCommand_DefineOutput_TableDetails_SchemaDataType)(nil),
		(*PipelineCommand_DefineOutput_TableDetails_SchemaString)(nil),
	}
	file_spark_connect_pipelines_proto_msgTypes[18].OneofWrappers = []any{}
	file_spark_connect_pipelines_proto_msgTypes[22].OneofWrappers = []any{}
	file_spark_connect_pipelines_proto_msgTypes[23].OneofWrappers = []any{}
	file_spark_connect_pipelines_proto_msgTypes[24].OneofWrappers = []any{}
	file_spark_connect_pipelines_proto_msgTypes[25].OneofWrappers = []any{}
	file_spark_connect_pipelines_proto_msgTypes[26].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_spark_connect_pipelines_proto_rawDesc), len(file_spark_connect_pipelines_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_spark_connect_pipelines_proto_goTypes,
		DependencyIndexes: file_spark_connect_pipelines_proto_depIdxs,
		EnumInfos:         file_spark_connect_pipelines_proto_enumTypes,
		MessageInfos:      file_spark_connect_pipelines_proto_msgTypes,
	}.Build()
	File_spark_connect_pipelines_proto = out.File
	file_spark_connect_pipelines_proto_goTypes = nil
	file_spark_connect_pipelines_proto_depIdxs = nil
}
