//
// Licensed to the Apache Software Foundation (ASF) under one or more
// contributor license agreements.  See the NOTICE file distributed with
// this work for additional information regarding copyright ownership.
// The ASF licenses this file to You under the Apache License, Version 2.0
// (the "License"); you may not use this file except in compliance with
// the License.  You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: spark/connect/types.proto

package generated

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This message describes the logical [[DataType]] of something. It does not carry the value
// itself but only describes it.
type DataType struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*DataType_Null
	//	*DataType_Binary_
	//	*DataType_Boolean_
	//	*DataType_Byte_
	//	*DataType_Short_
	//	*DataType_Integer_
	//	*DataType_Long_
	//	*DataType_Float_
	//	*DataType_Double_
	//	*DataType_Decimal_
	//	*DataType_String_
	//	*DataType_Char_
	//	*DataType_VarChar_
	//	*DataType_Date_
	//	*DataType_Timestamp_
	//	*DataType_TimestampNtz
	//	*DataType_CalendarInterval_
	//	*DataType_YearMonthInterval_
	//	*DataType_DayTimeInterval_
	//	*DataType_Array_
	//	*DataType_Struct_
	//	*DataType_Map_
	//	*DataType_Variant_
	//	*DataType_Udt
	//	*DataType_Geometry_
	//	*DataType_Geography_
	//	*DataType_Unparsed_
	//	*DataType_Time_
	Kind          isDataType_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataType) Reset() {
	*x = DataType{}
	mi := &file_spark_connect_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataType) ProtoMessage() {}

func (x *DataType) ProtoReflect() protoreflect.Message {
	mi := &file_spark_connect_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataType.ProtoReflect.Descriptor instead.
func (*DataType) Descriptor() ([]byte, []int) {
	return file_spark_connect_types_proto_rawDescGZIP(), []int{0}
}

func (x *DataType) GetKind() isDataType_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *DataType) GetNull() *DataType_NULL {
	if x != nil {
		if x, ok := x.Kind.(*DataType_Null); ok {
			return x.Null
		}
	}
	return nil
}

func (x *DataType) GetBinary() *DataType_Binary {
	if x != nil {
		if x, ok := x.Kind.(*DataType_Binary_); ok {
			return x.Binary
		}
	}
	return nil
}

func (x *DataType) GetBoolean() *DataType_Boolean {
	if x != nil {
		if x, ok := x.Kind.(*DataType_Boolean_); ok {
			return x.Boolean
		}
	}
	return nil
}

func (x *DataType) GetByte() *DataType_Byte {
	if x != nil {
		if x, ok := x.Kind.(*DataType_Byte_); ok {
			return x.Byte
		}
	}
	return nil
}

func (x *DataType) GetShort() *DataType_Short {
	if x != nil {
		if x, ok := x.Kind.(*DataType_Short_); ok {
			return x.Short
		}
	}
	return nil
}

func (x *DataType) GetInteger() *DataType_Integer {
	if x != nil {
		if x, ok := x.Kind.(*DataType_Integer_); ok {
			return x.Integer
		}
	}
	return nil
}

func (x *DataType) GetLong() *DataType_Long {
	if x != nil {
		if x, ok := x.Kind.(*DataType_Long_); ok {
			return x.Long
		}
	}
	return nil
}

func (x *DataType) GetFloat() *DataType_Float {
	if x != nil {
		if x, ok := x.Kind.(*DataType_Float_); ok {
			return x.Float
		}
	}
	return nil
}

func (x *DataType) GetDouble() *DataType_Double {
	if x != nil {
		if x, ok := x.Kind.(*DataType_Double_); ok {
			return x.Double
		}
	}
	return nil
}

func (x *DataType) GetDecimal() *DataType_Decimal {
	if x != nil {
		if x, ok := x.Kind.(*DataType_Decimal_); ok {
			return x.Decimal
		}
	}
	return nil
}

func (x *DataType) GetString_() *DataType_String {
	if x != nil {
		if x, ok := x.Kind.(*DataType_String_); ok {
			return x.String_
		}
	}
	return nil
}

func (x *DataType) GetChar() *DataType_Char {
	if x != nil {
		if x, ok := x.Kind.(*DataType_Char_); ok {
			return x.Char
		}
	}
	return nil
}

func (x *DataType) GetVarChar() *DataType_VarChar {
	if x != nil {
		if x, ok := x.Kind.(*DataType_VarChar_); ok {
			return x.VarChar
		}
	}
	return nil
}

func (x *DataType) GetDate() *DataType_Date {
	if x != nil {
		if x, ok := x.Kind.(*DataType_Date_); ok {
			return x.Date
		}
	}
	return nil
}

func (x *DataType) GetTimestamp() *DataType_Timestamp {
	if x != nil {
		if x, ok := x.Kind.(*DataType_Timestamp_); ok {
			return x.Timestamp
		}
	}
	return nil
}

func (x *DataType) GetTimestampNtz() *DataType_TimestampNTZ {
	if x != nil {
		if x, ok := x.Kind.(*DataType_TimestampNtz); ok {
			return x.TimestampNtz
		}
	}
	return nil
}

func (x *DataType) GetCalendarInterval() *DataType_CalendarInterval {
	if x != nil {
		if x, ok := x.Kind.(*DataType_CalendarInterval_); ok {
			return x.CalendarInterval
		}
	}
	return nil
}

func (x *DataType) GetYearMonthInterval() *DataType_YearMonthInterval {
	if x != nil {
		if x, ok := x.Kind.(*DataType_YearMonthInterval_); ok {
			return x.YearMonthInterval
		}
	}
	return nil
}

func (x *DataType) GetDayTimeInterval() *DataType_DayTimeInterval {
	if x != nil {
		if x, ok := x.Kind.(*DataType_DayTimeInterval_); ok {
			return x.DayTimeInterval
		}
	}
	return nil
}

func (x *DataType) GetArray() *DataType_Array {
	if x != nil {
		if x, ok := x.Kind.(*DataType_Array_); ok {
			return x.Array
		}
	}
	return nil
}

func (x *DataType) GetStruct() *DataType_Struct {
	if x != nil {
		if x, ok := x.Kind.(*DataType_Struct_); ok {
			return x.Struct
		}
	}
	return nil
}

func (x *DataType) GetMap() *DataType_Map {
	if x != nil {
		if x, ok := x.Kind.(*DataType_Map_); ok {
			return x.Map
		}
	}
	return nil
}

func (x *DataType) GetVariant() *DataType_Variant {
	if x != nil {
		if x, ok := x.Kind.(*DataType_Variant_); ok {
			return x.Variant
		}
	}
	return nil
}

func (x *DataType) GetUdt() *DataType_UDT {
	if x != nil {
		if x, ok := x.Kind.(*DataType_Udt); ok {
			return x.Udt
		}
	}
	return nil
}

func (x *DataType) GetGeometry() *DataType_Geometry {
	if x != nil {
		if x, ok := x.Kind.(*DataType_Geometry_); ok {
			return x.Geometry
		}
	}
	return nil
}

func (x *DataType) GetGeography() *DataType_Geography {
	if x != nil {
		if x, ok := x.Kind.(*DataType_Geography_); ok {
			return x.Geography
		}
	}
	return nil
}

func (x *DataType) GetUnparsed() *DataType_Unparsed {
	if x != nil {
		if x, ok := x.Kind.(*DataType_Unparsed_); ok {
			return x.Unparsed
		}
	}
	return nil
}

func (x *DataType) GetTime() *DataType_Time {
	if x != nil {
		if x, ok := x.Kind.(*DataType_Time_); ok {
			return x.Time
		}
	}
	return nil
}

type isDataType_Kind interface {
	isDataType_Kind()
}

type DataType_Null struct {
	Null *DataType_NULL `protobuf:"bytes,1,opt,name=null,proto3,oneof"`
}

type DataType_Binary_ struct {
	Binary *DataType_Binary `protobuf:"bytes,2,opt,name=binary,proto3,oneof"`
}

type DataType_Boolean_ struct {
	Boolean *DataType_Boolean `protobuf:"bytes,3,opt,name=boolean,proto3,oneof"`
}

type DataType_Byte_ struct {
	// Numeric types
	Byte *DataType_Byte `protobuf:"bytes,4,opt,name=byte,proto3,oneof"`
}

type DataType_Short_ struct {
	Short *DataType_Short `protobuf:"bytes,5,opt,name=short,proto3,oneof"`
}

type DataType_Integer_ struct {
	Integer *DataType_Integer `protobuf:"bytes,6,opt,name=integer,proto3,oneof"`
}

type DataType_Long_ struct {
	Long *DataType_Long `protobuf:"bytes,7,opt,name=long,proto3,oneof"`
}

type DataType_Float_ struct {
	Float *DataType_Float `protobuf:"bytes,8,opt,name=float,proto3,oneof"`
}

type DataType_Double_ struct {
	Double *DataType_Double `protobuf:"bytes,9,opt,name=double,proto3,oneof"`
}

type DataType_Decimal_ struct {
	Decimal *DataType_Decimal `protobuf:"bytes,10,opt,name=decimal,proto3,oneof"`
}

type DataType_String_ struct {
	// String types
	String_ *DataType_String `protobuf:"bytes,11,opt,name=string,proto3,oneof"`
}

type DataType_Char_ struct {
	Char *DataType_Char `protobuf:"bytes,12,opt,name=char,proto3,oneof"`
}

type DataType_VarChar_ struct {
	VarChar *DataType_VarChar `protobuf:"bytes,13,opt,name=var_char,json=varChar,proto3,oneof"`
}

type DataType_Date_ struct {
	// Datatime types
	Date *DataType_Date `protobuf:"bytes,14,opt,name=date,proto3,oneof"`
}

type DataType_Timestamp_ struct {
	Timestamp *DataType_Timestamp `protobuf:"bytes,15,opt,name=timestamp,proto3,oneof"`
}

type DataType_TimestampNtz struct {
	TimestampNtz *DataType_TimestampNTZ `protobuf:"bytes,16,opt,name=timestamp_ntz,json=timestampNtz,proto3,oneof"`
}

type DataType_CalendarInterval_ struct {
	// Interval types
	CalendarInterval *DataType_CalendarInterval `protobuf:"bytes,17,opt,name=calendar_interval,json=calendarInterval,proto3,oneof"`
}

type DataType_YearMonthInterval_ struct {
	YearMonthInterval *DataType_YearMonthInterval `protobuf:"bytes,18,opt,name=year_month_interval,json=yearMonthInterval,proto3,oneof"`
}

type DataType_DayTimeInterval_ struct {
	DayTimeInterval *DataType_DayTimeInterval `protobuf:"bytes,19,opt,name=day_time_interval,json=dayTimeInterval,proto3,oneof"`
}

type DataType_Array_ struct {
	// Complex types
	Array *DataType_Array `protobuf:"bytes,20,opt,name=array,proto3,oneof"`
}

type DataType_Struct_ struct {
	Struct *DataType_Struct `protobuf:"bytes,21,opt,name=struct,proto3,oneof"`
}

type DataType_Map_ struct {
	Map *DataType_Map `protobuf:"bytes,22,opt,name=map,proto3,oneof"`
}

type DataType_Variant_ struct {
	Variant *DataType_Variant `protobuf:"bytes,25,opt,name=variant,proto3,oneof"`
}

type DataType_Udt struct {
	// UserDefinedType
	Udt *DataType_UDT `protobuf:"bytes,23,opt,name=udt,proto3,oneof"`
}

type DataType_Geometry_ struct {
	// Geospatial types
	Geometry *DataType_Geometry `protobuf:"bytes,26,opt,name=geometry,proto3,oneof"`
}

type DataType_Geography_ struct {
	Geography *DataType_Geography `protobuf:"bytes,27,opt,name=geography,proto3,oneof"`
}

type DataType_Unparsed_ struct {
	// UnparsedDataType
	Unparsed *DataType_Unparsed `protobuf:"bytes,24,opt,name=unparsed,proto3,oneof"`
}

type DataType_Time_ struct {
	Time *DataType_Time `protobuf:"bytes,28,opt,name=time,proto3,oneof"`
}

func (*DataType_Null) isDataType_Kind() {}

func (*DataType_Binary_) isDataType_Kind() {}

func (*DataType_Boolean_) isDataType_Kind() {}

func (*DataType_Byte_) isDataType_Kind() {}

func (*DataType_Short_) isDataType_Kind() {}

func (*DataType_Integer_) isDataType_Kind() {}

func (*DataType_Long_) isDataType_Kind() {}

func (*DataType_Float_) isDataType_Kind() {}

func (*DataType_Double_) isDataType_Kind() {}

func (*DataType_Decimal_) isDataType_Kind() {}

func (*DataType_String_) isDataType_Kind() {}

func (*DataType_Char_) isDataType_Kind() {}

func (*DataType_VarChar_) isDataType_Kind() {}

func (*DataType_Date_) isDataType_Kind() {}

func (*DataType_Timestamp_) isDataType_Kind() {}

func (*DataType_TimestampNtz) isDataType_Kind() {}

func (*DataType_CalendarInterval_) isDataType_Kind() {}

func (*DataType_YearMonthInterval_) isDataType_Kind() {}

func (*DataType_DayTimeInterval_) isDataType_Kind() {}

func (*DataType_Array_) isDataType_Kind() {}

func (*DataType_Struct_) isDataType_Kind() {}

func (*DataType_Map_) isDataType_Kind() {}

func (*DataType_Variant_) isDataType_Kind() {}

func (*DataType_Udt) isDataType_Kind() {}

func (*DataType_Geometry_) isDataType_Kind() {}

func (*DataType_Geography_) isDataType_Kind() {}

func (*DataType_Unparsed_) isDataType_Kind() {}

func (*DataType_Time_) isDataType_Kind() {}

type DataType_Boolean struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	TypeVariationReference uint32                 `protobuf:"varint,1,opt,name=type_variation_reference,json=typeVariationReference,proto3" json:"type_variation_reference,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *DataType_Boolean) Reset() {
	*x = DataType_Boolean{}
	mi := &file_spark_connect_types_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataType_Boolean) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataType_Boolean) ProtoMessage() {}

func (x *DataType_Boolean) ProtoReflect() protoreflect.Message {
	mi := &file_spark_connect_types_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataType_Boolean.ProtoReflect.Descriptor instead.
func (*DataType_Boolean) Descriptor() ([]byte, []int) {
	return file_spark_connect_types_proto_rawDescGZIP(), []int{0, 0}
}

func (x *DataType_Boolean) GetTypeVariationReference() uint32 {
	if x != nil {
		return x.TypeVariationReference
	}
	return 0
}

type DataType_Byte struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	TypeVariationReference uint32                 `protobuf:"varint,1,opt,name=type_variation_reference,json=typeVariationReference,proto3" json:"type_variation_reference,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *DataType_Byte) Reset() {
	*x = DataType_Byte{}
	mi := &file_spark_connect_types_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataType_Byte) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataType_Byte) ProtoMessage() {}

func (x *DataType_Byte) ProtoReflect() protoreflect.Message {
	mi := &file_spark_connect_types_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataType_Byte.ProtoReflect.Descriptor instead.
func (*DataType_Byte) Descriptor() ([]byte, []int) {
	return file_spark_connect_types_proto_rawDescGZIP(), []int{0, 1}
}

func (x *DataType_Byte) GetTypeVariationReference() uint32 {
	if x != nil {
		return x.TypeVariationReference
	}
	return 0
}

type DataType_Short struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	TypeVariationReference uint32                 `protobuf:"varint,1,opt,name=type_variation_reference,json=typeVariationReference,proto3" json:"type_variation_reference,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *DataType_Short) Reset() {
	*x = DataType_Short{}
	mi := &file_spark_connect_types_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataType_Short) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataType_Short) ProtoMessage() {}

func (x *DataType_Short) ProtoReflect() protoreflect.Message {
	mi := &file_spark_connect_types_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataType_Short.ProtoReflect.Descriptor instead.
func (*DataType_Short) Descriptor() ([]byte, []int) {
	return file_spark_connect_types_proto_rawDescGZIP(), []int{0, 2}
}

func (x *DataType_Short) GetTypeVariationReference() uint32 {
	if x != nil {
		return x.TypeVariationReference
	}
	return 0
}

type DataType_Integer struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	TypeVariationReference uint32                 `protobuf:"varint,1,opt,name=type_variation_reference,json=typeVariationReference,proto3" json:"type_variation_reference,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *DataType_Integer) Reset() {
	*x = DataType_Integer{}
	mi := &file_spark_connect_types_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataType_Integer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataType_Integer) ProtoMessage() {}

func (x *DataType_Integer) ProtoReflect() protoreflect.Message {
	mi := &file_spark_connect_types_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataType_Integer.ProtoReflect.Descriptor instead.
func (*DataType_Integer) Descriptor() ([]byte, []int) {
	return file_spark_connect_types_proto_rawDescGZIP(), []int{0, 3}
}

func (x *DataType_Integer) GetTypeVariationReference() uint32 {
	if x != nil {
		return x.TypeVariationReference
	}
	return 0
}

type DataType_Long struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	TypeVariationReference uint32                 `protobuf:"varint,1,opt,name=type_variation_reference,json=typeVariationReference,proto3" json:"type_variation_reference,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *DataType_Long) Reset() {
	*x = DataType_Long{}
	mi := &file_spark_connect_types_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataType_Long) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataType_Long) ProtoMessage() {}

func (x *DataType_Long) ProtoReflect() protoreflect.Message {
	mi := &file_spark_connect_types_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataType_Long.ProtoReflect.Descriptor instead.
func (*DataType_Long) Descriptor() ([]byte, []int) {
	return file_spark_connect_types_proto_rawDescGZIP(), []int{0, 4}
}

func (x *DataType_Long) GetTypeVariationReference() uint32 {
	if x != nil {
		return x.TypeVariationReference
	}
	return 0
}

type DataType_Float struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	TypeVariationReference uint32                 `protobuf:"varint,1,opt,name=type_variation_reference,json=typeVariationReference,proto3" json:"type_variation_reference,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *DataType_Float) Reset() {
	*x = DataType_Float{}
	mi := &file_spark_connect_types_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataType_Float) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataType_Float) ProtoMessage() {}

func (x *DataType_Float) ProtoReflect() protoreflect.Message {
	mi := &file_spark_connect_types_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataType_Float.ProtoReflect.Descriptor instead.
func (*DataType_Float) Descriptor() ([]byte, []int) {
	return file_spark_connect_types_proto_rawDescGZIP(), []int{0, 5}
}

func (x *DataType_Float) GetTypeVariationReference() uint32 {
	if x != nil {
		return x.TypeVariationReference
	}
	return 0
}

type DataType_Double struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	TypeVariationReference uint32                 `protobuf:"varint,1,opt,name=type_variation_reference,json=typeVariationReference,proto3" json:"type_variation_reference,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *DataType_Double) Reset() {
	*x = DataType_Double{}
	mi := &file_spark_connect_types_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataType_Double) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataType_Double) ProtoMessage() {}

func (x *DataType_Double) ProtoReflect() protoreflect.Message {
	mi := &file_spark_connect_types_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataType_Double.ProtoReflect.Descriptor instead.
func (*DataType_Double) Descriptor() ([]byte, []int) {
	return file_spark_connect_types_proto_rawDescGZIP(), []int{0, 6}
}

func (x *DataType_Double) GetTypeVariationReference() uint32 {
	if x != nil {
		return x.TypeVariationReference
	}
	return 0
}

type DataType_String struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	TypeVariationReference uint32                 `protobuf:"varint,1,opt,name=type_variation_reference,json=typeVariationReference,proto3" json:"type_variation_reference,omitempty"`
	Collation              string                 `protobuf:"bytes,2,opt,name=collation,proto3" json:"collation,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *DataType_String) Reset() {
	*x = DataType_String{}
	mi := &file_spark_connect_types_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataType_String) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataType_String) ProtoMessage() {}

func (x *DataType_String) ProtoReflect() protoreflect.Message {
	mi := &file_spark_connect_types_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataType_String.ProtoReflect.Descriptor instead.
func (*DataType_String) Descriptor() ([]byte, []int) {
	return file_spark_connect_types_proto_rawDescGZIP(), []int{0, 7}
}

func (x *DataType_String) GetTypeVariationReference() uint32 {
	if x != nil {
		return x.TypeVariationReference
	}
	return 0
}

func (x *DataType_String) GetCollation() string {
	if x != nil {
		return x.Collation
	}
	return ""
}

type DataType_Binary struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	TypeVariationReference uint32                 `protobuf:"varint,1,opt,name=type_variation_reference,json=typeVariationReference,proto3" json:"type_variation_reference,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *DataType_Binary) Reset() {
	*x = DataType_Binary{}
	mi := &file_spark_connect_types_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataType_Binary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataType_Binary) ProtoMessage() {}

func (x *DataType_Binary) ProtoReflect() protoreflect.Message {
	mi := &file_spark_connect_types_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataType_Binary.ProtoReflect.Descriptor instead.
func (*DataType_Binary) Descriptor() ([]byte, []int) {
	return file_spark_connect_types_proto_rawDescGZIP(), []int{0, 8}
}

func (x *DataType_Binary) GetTypeVariationReference() uint32 {
	if x != nil {
		return x.TypeVariationReference
	}
	return 0
}

type DataType_NULL struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	TypeVariationReference uint32                 `protobuf:"varint,1,opt,name=type_variation_reference,json=typeVariationReference,proto3" json:"type_variation_reference,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *DataType_NULL) Reset() {
	*x = DataType_NULL{}
	mi := &file_spark_connect_types_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataType_NULL) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataType_NULL) ProtoMessage() {}

func (x *DataType_NULL) ProtoReflect() protoreflect.Message {
	mi := &file_spark_connect_types_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataType_NULL.ProtoReflect.Descriptor instead.
func (*DataType_NULL) Descriptor() ([]byte, []int) {
	return file_spark_connect_types_proto_rawDescGZIP(), []int{0, 9}
}

func (x *DataType_NULL) GetTypeVariationReference() uint32 {
	if x != nil {
		return x.TypeVariationReference
	}
	return 0
}

type DataType_Timestamp struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	TypeVariationReference uint32                 `protobuf:"varint,1,opt,name=type_variation_reference,json=typeVariationReference,proto3" json:"type_variation_reference,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *DataType_Timestamp) Reset() {
	*x = DataType_Timestamp{}
	mi := &file_spark_connect_types_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataType_Timestamp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataType_Timestamp) ProtoMessage() {}

func (x *DataType_Timestamp) ProtoReflect() protoreflect.Message {
	mi := &file_spark_connect_types_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataType_Timestamp.ProtoReflect.Descriptor instead.
func (*DataType_Timestamp) Descriptor() ([]byte, []int) {
	return file_spark_connect_types_proto_rawDescGZIP(), []int{0, 10}
}

func (x *DataType_Timestamp) GetTypeVariationReference() uint32 {
	if x != nil {
		return x.TypeVariationReference
	}
	return 0
}

type DataType_Date struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	TypeVariationReference uint32                 `protobuf:"varint,1,opt,name=type_variation_reference,json=typeVariationReference,proto3" json:"type_variation_reference,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *DataType_Date) Reset() {
	*x = DataType_Date{}
	mi := &file_spark_connect_types_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataType_Date) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataType_Date) ProtoMessage() {}

func (x *DataType_Date) ProtoReflect() protoreflect.Message {
	mi := &file_spark_connect_types_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataType_Date.ProtoReflect.Descriptor instead.
func (*DataType_Date) Descriptor() ([]byte, []int) {
	return file_spark_connect_types_proto_rawDescGZIP(), []int{0, 11}
}

func (x *DataType_Date) GetTypeVariationReference() uint32 {
	if x != nil {
		return x.TypeVariationReference
	}
	return 0
}

type DataType_TimestampNTZ struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	TypeVariationReference uint32                 `protobuf:"varint,1,opt,name=type_variation_reference,json=typeVariationReference,proto3" json:"type_variation_reference,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *DataType_TimestampNTZ) Reset() {
	*x = DataType_TimestampNTZ{}
	mi := &file_spark_connect_types_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataType_TimestampNTZ) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataType_TimestampNTZ) ProtoMessage() {}

func (x *DataType_TimestampNTZ) ProtoReflect() protoreflect.Message {
	mi := &file_spark_connect_types_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataType_TimestampNTZ.ProtoReflect.Descriptor instead.
func (*DataType_TimestampNTZ) Descriptor() ([]byte, []int) {
	return file_spark_connect_types_proto_rawDescGZIP(), []int{0, 12}
}

func (x *DataType_TimestampNTZ) GetTypeVariationReference() uint32 {
	if x != nil {
		return x.TypeVariationReference
	}
	return 0
}

type DataType_Time struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Precision              *int32                 `protobuf:"varint,1,opt,name=precision,proto3,oneof" json:"precision,omitempty"`
	TypeVariationReference uint32                 `protobuf:"varint,2,opt,name=type_variation_reference,json=typeVariationReference,proto3" json:"type_variation_reference,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *DataType_Time) Reset() {
	*x = DataType_Time{}
	mi := &file_spark_connect_types_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataType_Time) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataType_Time) ProtoMessage() {}

func (x *DataType_Time) ProtoReflect() protoreflect.Message {
	mi := &file_spark_connect_types_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataType_Time.ProtoReflect.Descriptor instead.
func (*DataType_Time) Descriptor() ([]byte, []int) {
	return file_spark_connect_types_proto_rawDescGZIP(), []int{0, 13}
}

func (x *DataType_Time) GetPrecision() int32 {
	if x != nil && x.Precision != nil {
		return *x.Precision
	}
	return 0
}

func (x *DataType_Time) GetTypeVariationReference() uint32 {
	if x != nil {
		return x.TypeVariationReference
	}
	return 0
}

type DataType_CalendarInterval struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	TypeVariationReference uint32                 `protobuf:"varint,1,opt,name=type_variation_reference,json=typeVariationReference,proto3" json:"type_variation_reference,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *DataType_CalendarInterval) Reset() {
	*x = DataType_CalendarInterval{}
	mi := &file_spark_connect_types_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataType_CalendarInterval) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataType_CalendarInterval) ProtoMessage() {}

func (x *DataType_CalendarInterval) ProtoReflect() protoreflect.Message {
	mi := &file_spark_connect_types_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataType_CalendarInterval.ProtoReflect.Descriptor instead.
func (*DataType_CalendarInterval) Descriptor() ([]byte, []int) {
	return file_spark_connect_types_proto_rawDescGZIP(), []int{0, 14}
}

func (x *DataType_CalendarInterval) GetTypeVariationReference() uint32 {
	if x != nil {
		return x.TypeVariationReference
	}
	return 0
}

type DataType_YearMonthInterval struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	StartField             *int32                 `protobuf:"varint,1,opt,name=start_field,json=startField,proto3,oneof" json:"start_field,omitempty"`
	EndField               *int32                 `protobuf:"varint,2,opt,name=end_field,json=endField,proto3,oneof" json:"end_field,omitempty"`
	TypeVariationReference uint32                 `protobuf:"varint,3,opt,name=type_variation_reference,json=typeVariationReference,proto3" json:"type_variation_reference,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *DataType_YearMonthInterval) Reset() {
	*x = DataType_YearMonthInterval{}
	mi := &file_spark_connect_types_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataType_YearMonthInterval) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataType_YearMonthInterval) ProtoMessage() {}

func (x *DataType_YearMonthInterval) ProtoReflect() protoreflect.Message {
	mi := &file_spark_connect_types_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataType_YearMonthInterval.ProtoReflect.Descriptor instead.
func (*DataType_YearMonthInterval) Descriptor() ([]byte, []int) {
	return file_spark_connect_types_proto_rawDescGZIP(), []int{0, 15}
}

func (x *DataType_YearMonthInterval) GetStartField() int32 {
	if x != nil && x.StartField != nil {
		return *x.StartField
	}
	return 0
}

func (x *DataType_YearMonthInterval) GetEndField() int32 {
	if x != nil && x.EndField != nil {
		return *x.EndField
	}
	return 0
}

func (x *DataType_YearMonthInterval) GetTypeVariationReference() uint32 {
	if x != nil {
		return x.TypeVariationReference
	}
	return 0
}

type DataType_DayTimeInterval struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	StartField             *int32                 `protobuf:"varint,1,opt,name=start_field,json=startField,proto3,oneof" json:"start_field,omitempty"`
	EndField               *int32                 `protobuf:"varint,2,opt,name=end_field,json=endField,proto3,oneof" json:"end_field,omitempty"`
	TypeVariationReference uint32                 `protobuf:"varint,3,opt,name=type_variation_reference,json=typeVariationReference,proto3" json:"type_variation_reference,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *DataType_DayTimeInterval) Reset() {
	*x = DataType_DayTimeInterval{}
	mi := &file_spark_connect_types_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataType_DayTimeInterval) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataType_DayTimeInterval) ProtoMessage() {}

func (x *DataType_DayTimeInterval) ProtoReflect() protoreflect.Message {
	mi := &file_spark_connect_types_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataType_DayTimeInterval.ProtoReflect.Descriptor instead.
func (*DataType_DayTimeInterval) Descriptor() ([]byte, []int) {
	return file_spark_connect_types_proto_rawDescGZIP(), []int{0, 16}
}

func (x *DataType_DayTimeInterval) GetStartField() int32 {
	if x != nil && x.StartField != nil {
		return *x.StartField
	}
	return 0
}

func (x *DataType_DayTimeInterval) GetEndField() int32 {
	if x != nil && x.EndField != nil {
		return *x.EndField
	}
	return 0
}

func (x *DataType_DayTimeInterval) GetTypeVariationReference() uint32 {
	if x != nil {
		return x.TypeVariationReference
	}
	return 0
}

// Start compound types.
type DataType_Char struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Length                 int32                  `protobuf:"varint,1,opt,name=length,proto3" json:"length,omitempty"`
	TypeVariationReference uint32                 `protobuf:"varint,2,opt,name=type_variation_reference,json=typeVariationReference,proto3" json:"type_variation_reference,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *DataType_Char) Reset() {
	*x = DataType_Char{}
	mi := &file_spark_connect_types_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataType_Char) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataType_Char) ProtoMessage() {}

func (x *DataType_Char) ProtoReflect() protoreflect.Message {
	mi := &file_spark_connect_types_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataType_Char.ProtoReflect.Descriptor instead.
func (*DataType_Char) Descriptor() ([]byte, []int) {
	return file_spark_connect_types_proto_rawDescGZIP(), []int{0, 17}
}

func (x *DataType_Char) GetLength() int32 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *DataType_Char) GetTypeVariationReference() uint32 {
	if x != nil {
		return x.TypeVariationReference
	}
	return 0
}

type DataType_VarChar struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Length                 int32                  `protobuf:"varint,1,opt,name=length,proto3" json:"length,omitempty"`
	TypeVariationReference uint32                 `protobuf:"varint,2,opt,name=type_variation_reference,json=typeVariationReference,proto3" json:"type_variation_reference,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *DataType_VarChar) Reset() {
	*x = DataType_VarChar{}
	mi := &file_spark_connect_types_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataType_VarChar) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataType_VarChar) ProtoMessage() {}

func (x *DataType_VarChar) ProtoReflect() protoreflect.Message {
	mi := &file_spark_connect_types_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataType_VarChar.ProtoReflect.Descriptor instead.
func (*DataType_VarChar) Descriptor() ([]byte, []int) {
	return file_spark_connect_types_proto_rawDescGZIP(), []int{0, 18}
}

func (x *DataType_VarChar) GetLength() int32 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *DataType_VarChar) GetTypeVariationReference() uint32 {
	if x != nil {
		return x.TypeVariationReference
	}
	return 0
}

type DataType_Decimal struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Scale                  *int32                 `protobuf:"varint,1,opt,name=scale,proto3,oneof" json:"scale,omitempty"`
	Precision              *int32                 `protobuf:"varint,2,opt,name=precision,proto3,oneof" json:"precision,omitempty"`
	TypeVariationReference uint32                 `protobuf:"varint,3,opt,name=type_variation_reference,json=typeVariationReference,proto3" json:"type_variation_reference,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *DataType_Decimal) Reset() {
	*x = DataType_Decimal{}
	mi := &file_spark_connect_types_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataType_Decimal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataType_Decimal) ProtoMessage() {}

func (x *DataType_Decimal) ProtoReflect() protoreflect.Message {
	mi := &file_spark_connect_types_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataType_Decimal.ProtoReflect.Descriptor instead.
func (*DataType_Decimal) Descriptor() ([]byte, []int) {
	return file_spark_connect_types_proto_rawDescGZIP(), []int{0, 19}
}

func (x *DataType_Decimal) GetScale() int32 {
	if x != nil && x.Scale != nil {
		return *x.Scale
	}
	return 0
}

func (x *DataType_Decimal) GetPrecision() int32 {
	if x != nil && x.Precision != nil {
		return *x.Precision
	}
	return 0
}

func (x *DataType_Decimal) GetTypeVariationReference() uint32 {
	if x != nil {
		return x.TypeVariationReference
	}
	return 0
}

type DataType_StructField struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	DataType      *DataType              `protobuf:"bytes,2,opt,name=data_type,json=dataType,proto3" json:"data_type,omitempty"`
	Nullable      bool                   `protobuf:"varint,3,opt,name=nullable,proto3" json:"nullable,omitempty"`
	Metadata      *string                `protobuf:"bytes,4,opt,name=metadata,proto3,oneof" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataType_StructField) Reset() {
	*x = DataType_StructField{}
	mi := &file_spark_connect_types_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataType_StructField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataType_StructField) ProtoMessage() {}

func (x *DataType_StructField) ProtoReflect() protoreflect.Message {
	mi := &file_spark_connect_types_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataType_StructField.ProtoReflect.Descriptor instead.
func (*DataType_StructField) Descriptor() ([]byte, []int) {
	return file_spark_connect_types_proto_rawDescGZIP(), []int{0, 20}
}

func (x *DataType_StructField) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DataType_StructField) GetDataType() *DataType {
	if x != nil {
		return x.DataType
	}
	return nil
}

func (x *DataType_StructField) GetNullable() bool {
	if x != nil {
		return x.Nullable
	}
	return false
}

func (x *DataType_StructField) GetMetadata() string {
	if x != nil && x.Metadata != nil {
		return *x.Metadata
	}
	return ""
}

type DataType_Struct struct {
	state                  protoimpl.MessageState  `protogen:"open.v1"`
	Fields                 []*DataType_StructField `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty"`
	TypeVariationReference uint32                  `protobuf:"varint,2,opt,name=type_variation_reference,json=typeVariationReference,proto3" json:"type_variation_reference,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *DataType_Struct) Reset() {
	*x = DataType_Struct{}
	mi := &file_spark_connect_types_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataType_Struct) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataType_Struct) ProtoMessage() {}

func (x *DataType_Struct) ProtoReflect() protoreflect.Message {
	mi := &file_spark_connect_types_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataType_Struct.ProtoReflect.Descriptor instead.
func (*DataType_Struct) Descriptor() ([]byte, []int) {
	return file_spark_connect_types_proto_rawDescGZIP(), []int{0, 21}
}

func (x *DataType_Struct) GetFields() []*DataType_StructField {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *DataType_Struct) GetTypeVariationReference() uint32 {
	if x != nil {
		return x.TypeVariationReference
	}
	return 0
}

type DataType_Array struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	ElementType            *DataType              `protobuf:"bytes,1,opt,name=element_type,json=elementType,proto3" json:"element_type,omitempty"`
	ContainsNull           bool                   `protobuf:"varint,2,opt,name=contains_null,json=containsNull,proto3" json:"contains_null,omitempty"`
	TypeVariationReference uint32                 `protobuf:"varint,3,opt,name=type_variation_reference,json=typeVariationReference,proto3" json:"type_variation_reference,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *DataType_Array) Reset() {
	*x = DataType_Array{}
	mi := &file_spark_connect_types_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataType_Array) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataType_Array) ProtoMessage() {}

func (x *DataType_Array) ProtoReflect() protoreflect.Message {
	mi := &file_spark_connect_types_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataType_Array.ProtoReflect.Descriptor instead.
func (*DataType_Array) Descriptor() ([]byte, []int) {
	return file_spark_connect_types_proto_rawDescGZIP(), []int{0, 22}
}

func (x *DataType_Array) GetElementType() *DataType {
	if x != nil {
		return x.ElementType
	}
	return nil
}

func (x *DataType_Array) GetContainsNull() bool {
	if x != nil {
		return x.ContainsNull
	}
	return false
}

func (x *DataType_Array) GetTypeVariationReference() uint32 {
	if x != nil {
		return x.TypeVariationReference
	}
	return 0
}

type DataType_Map struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	KeyType                *DataType              `protobuf:"bytes,1,opt,name=key_type,json=keyType,proto3" json:"key_type,omitempty"`
	ValueType              *DataType              `protobuf:"bytes,2,opt,name=value_type,json=valueType,proto3" json:"value_type,omitempty"`
	ValueContainsNull      bool                   `protobuf:"varint,3,opt,name=value_contains_null,json=valueContainsNull,proto3" json:"value_contains_null,omitempty"`
	TypeVariationReference uint32                 `protobuf:"varint,4,opt,name=type_variation_reference,json=typeVariationReference,proto3" json:"type_variation_reference,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *DataType_Map) Reset() {
	*x = DataType_Map{}
	mi := &file_spark_connect_types_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataType_Map) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataType_Map) ProtoMessage() {}

func (x *DataType_Map) ProtoReflect() protoreflect.Message {
	mi := &file_spark_connect_types_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataType_Map.ProtoReflect.Descriptor instead.
func (*DataType_Map) Descriptor() ([]byte, []int) {
	return file_spark_connect_types_proto_rawDescGZIP(), []int{0, 23}
}

func (x *DataType_Map) GetKeyType() *DataType {
	if x != nil {
		return x.KeyType
	}
	return nil
}

func (x *DataType_Map) GetValueType() *DataType {
	if x != nil {
		return x.ValueType
	}
	return nil
}

func (x *DataType_Map) GetValueContainsNull() bool {
	if x != nil {
		return x.ValueContainsNull
	}
	return false
}

func (x *DataType_Map) GetTypeVariationReference() uint32 {
	if x != nil {
		return x.TypeVariationReference
	}
	return 0
}

type DataType_Geometry struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Srid                   int32                  `protobuf:"varint,1,opt,name=srid,proto3" json:"srid,omitempty"`
	TypeVariationReference uint32                 `protobuf:"varint,2,opt,name=type_variation_reference,json=typeVariationReference,proto3" json:"type_variation_reference,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *DataType_Geometry) Reset() {
	*x = DataType_Geometry{}
	mi := &file_spark_connect_types_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataType_Geometry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataType_Geometry) ProtoMessage() {}

func (x *DataType_Geometry) ProtoReflect() protoreflect.Message {
	mi := &file_spark_connect_types_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataType_Geometry.ProtoReflect.Descriptor instead.
func (*DataType_Geometry) Descriptor() ([]byte, []int) {
	return file_spark_connect_types_proto_rawDescGZIP(), []int{0, 24}
}

func (x *DataType_Geometry) GetSrid() int32 {
	if x != nil {
		return x.Srid
	}
	return 0
}

func (x *DataType_Geometry) GetTypeVariationReference() uint32 {
	if x != nil {
		return x.TypeVariationReference
	}
	return 0
}

type DataType_Geography struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Srid                   int32                  `protobuf:"varint,1,opt,name=srid,proto3" json:"srid,omitempty"`
	TypeVariationReference uint32                 `protobuf:"varint,2,opt,name=type_variation_reference,json=typeVariationReference,proto3" json:"type_variation_reference,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *DataType_Geography) Reset() {
	*x = DataType_Geography{}
	mi := &file_spark_connect_types_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataType_Geography) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataType_Geography) ProtoMessage() {}

func (x *DataType_Geography) ProtoReflect() protoreflect.Message {
	mi := &file_spark_connect_types_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataType_Geography.ProtoReflect.Descriptor instead.
func (*DataType_Geography) Descriptor() ([]byte, []int) {
	return file_spark_connect_types_proto_rawDescGZIP(), []int{0, 25}
}

func (x *DataType_Geography) GetSrid() int32 {
	if x != nil {
		return x.Srid
	}
	return 0
}

func (x *DataType_Geography) GetTypeVariationReference() uint32 {
	if x != nil {
		return x.TypeVariationReference
	}
	return 0
}

type DataType_Variant struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	TypeVariationReference uint32                 `protobuf:"varint,1,opt,name=type_variation_reference,json=typeVariationReference,proto3" json:"type_variation_reference,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *DataType_Variant) Reset() {
	*x = DataType_Variant{}
	mi := &file_spark_connect_types_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataType_Variant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataType_Variant) ProtoMessage() {}

func (x *DataType_Variant) ProtoReflect() protoreflect.Message {
	mi := &file_spark_connect_types_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataType_Variant.ProtoReflect.Descriptor instead.
func (*DataType_Variant) Descriptor() ([]byte, []int) {
	return file_spark_connect_types_proto_rawDescGZIP(), []int{0, 26}
}

func (x *DataType_Variant) GetTypeVariationReference() uint32 {
	if x != nil {
		return x.TypeVariationReference
	}
	return 0
}

type DataType_UDT struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Type  string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// Required for Scala/Java UDT
	JvmClass *string `protobuf:"bytes,2,opt,name=jvm_class,json=jvmClass,proto3,oneof" json:"jvm_class,omitempty"`
	// Required for Python UDT
	PythonClass *string `protobuf:"bytes,3,opt,name=python_class,json=pythonClass,proto3,oneof" json:"python_class,omitempty"`
	// Required for Python UDT
	SerializedPythonClass *string `protobuf:"bytes,4,opt,name=serialized_python_class,json=serializedPythonClass,proto3,oneof" json:"serialized_python_class,omitempty"`
	// Required for Python UDT
	SqlType       *DataType `protobuf:"bytes,5,opt,name=sql_type,json=sqlType,proto3,oneof" json:"sql_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataType_UDT) Reset() {
	*x = DataType_UDT{}
	mi := &file_spark_connect_types_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataType_UDT) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataType_UDT) ProtoMessage() {}

func (x *DataType_UDT) ProtoReflect() protoreflect.Message {
	mi := &file_spark_connect_types_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataType_UDT.ProtoReflect.Descriptor instead.
func (*DataType_UDT) Descriptor() ([]byte, []int) {
	return file_spark_connect_types_proto_rawDescGZIP(), []int{0, 27}
}

func (x *DataType_UDT) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *DataType_UDT) GetJvmClass() string {
	if x != nil && x.JvmClass != nil {
		return *x.JvmClass
	}
	return ""
}

func (x *DataType_UDT) GetPythonClass() string {
	if x != nil && x.PythonClass != nil {
		return *x.PythonClass
	}
	return ""
}

func (x *DataType_UDT) GetSerializedPythonClass() string {
	if x != nil && x.SerializedPythonClass != nil {
		return *x.SerializedPythonClass
	}
	return ""
}

func (x *DataType_UDT) GetSqlType() *DataType {
	if x != nil {
		return x.SqlType
	}
	return nil
}

type DataType_Unparsed struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// (Required) The unparsed data type string
	DataTypeString string `protobuf:"bytes,1,opt,name=data_type_string,json=dataTypeString,proto3" json:"data_type_string,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DataType_Unparsed) Reset() {
	*x = DataType_Unparsed{}
	mi := &file_spark_connect_types_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataType_Unparsed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataType_Unparsed) ProtoMessage() {}

func (x *DataType_Unparsed) ProtoReflect() protoreflect.Message {
	mi := &file_spark_connect_types_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataType_Unparsed.ProtoReflect.Descriptor instead.
func (*DataType_Unparsed) Descriptor() ([]byte, []int) {
	return file_spark_connect_types_proto_rawDescGZIP(), []int{0, 28}
}

func (x *DataType_Unparsed) GetDataTypeString() string {
	if x != nil {
		return x.DataTypeString
	}
	return ""
}

var File_spark_connect_types_proto protoreflect.FileDescriptor

const file_spark_connect_types_proto_rawDesc = "" +
	"\n" +
	"\x19spark/connect/types.proto\x12\rspark.connect\"\xd8%\n" +
	"\bDataType\x122\n" +
	"\x04null\x18\x01 \x01(\v2\x1c.spark.connect.DataType.NULLH\x00R\x04null\x128\n" +
	"\x06binary\x18\x02 \x01(\v2\x1e.spark.connect.DataType.BinaryH\x00R\x06binary\x12;\n" +
	"\aboolean\x18\x03 \x01(\v2\x1f.spark.connect.DataType.BooleanH\x00R\aboolean\x122\n" +
	"\x04byte\x18\x04 \x01(\v2\x1c.spark.connect.DataType.ByteH\x00R\x04byte\x125\n" +
	"\x05short\x18\x05 \x01(\v2\x1d.spark.connect.DataType.ShortH\x00R\x05short\x12;\n" +
	"\ainteger\x18\x06 \x01(\v2\x1f.spark.connect.DataType.IntegerH\x00R\ainteger\x122\n" +
	"\x04long\x18\a \x01(\v2\x1c.spark.connect.DataType.LongH\x00R\x04long\x125\n" +
	"\x05float\x18\b \x01(\v2\x1d.spark.connect.DataType.FloatH\x00R\x05float\x128\n" +
	"\x06double\x18\t \x01(\v2\x1e.spark.connect.DataType.DoubleH\x00R\x06double\x12;\n" +
	"\adecimal\x18\n" +
	" \x01(\v2\x1f.spark.connect.DataType.DecimalH\x00R\adecimal\x128\n" +
	"\x06string\x18\v \x01(\v2\x1e.spark.connect.DataType.StringH\x00R\x06string\x122\n" +
	"\x04char\x18\f \x01(\v2\x1c.spark.connect.DataType.CharH\x00R\x04char\x12<\n" +
	"\bvar_char\x18\r \x01(\v2\x1f.spark.connect.DataType.VarCharH\x00R\avarChar\x122\n" +
	"\x04date\x18\x0e \x01(\v2\x1c.spark.connect.DataType.DateH\x00R\x04date\x12A\n" +
	"\ttimestamp\x18\x0f \x01(\v2!.spark.connect.DataType.TimestampH\x00R\ttimestamp\x12K\n" +
	"\rtimestamp_ntz\x18\x10 \x01(\v2$.spark.connect.DataType.TimestampNTZH\x00R\ftimestampNtz\x12W\n" +
	"\x11calendar_interval\x18\x11 \x01(\v2(.spark.connect.DataType.CalendarIntervalH\x00R\x10calendarInterval\x12[\n" +
	"\x13year_month_interval\x18\x12 \x01(\v2).spark.connect.DataType.YearMonthIntervalH\x00R\x11yearMonthInterval\x12U\n" +
	"\x11day_time_interval\x18\x13 \x01(\v2'.spark.connect.DataType.DayTimeIntervalH\x00R\x0fdayTimeInterval\x125\n" +
	"\x05array\x18\x14 \x01(\v2\x1d.spark.connect.DataType.ArrayH\x00R\x05array\x128\n" +
	"\x06struct\x18\x15 \x01(\v2\x1e.spark.connect.DataType.StructH\x00R\x06struct\x12/\n" +
	"\x03map\x18\x16 \x01(\v2\x1b.spark.connect.DataType.MapH\x00R\x03map\x12;\n" +
	"\avariant\x18\x19 \x01(\v2\x1f.spark.connect.DataType.VariantH\x00R\avariant\x12/\n" +
	"\x03udt\x18\x17 \x01(\v2\x1b.spark.connect.DataType.UDTH\x00R\x03udt\x12>\n" +
	"\bgeometry\x18\x1a \x01(\v2 .spark.connect.DataType.GeometryH\x00R\bgeometry\x12A\n" +
	"\tgeography\x18\x1b \x01(\v2!.spark.connect.DataType.GeographyH\x00R\tgeography\x12>\n" +
	"\bunparsed\x18\x18 \x01(\v2 .spark.connect.DataType.UnparsedH\x00R\bunparsed\x122\n" +
	"\x04time\x18\x1c \x01(\v2\x1c.spark.connect.DataType.TimeH\x00R\x04time\x1aC\n" +
	"\aBoolean\x128\n" +
	"\x18type_variation_reference\x18\x01 \x01(\rR\x16typeVariationReference\x1a@\n" +
	"\x04Byte\x128\n" +
	"\x18type_variation_reference\x18\x01 \x01(\rR\x16typeVariationReference\x1aA\n" +
	"\x05Short\x128\n" +
	"\x18type_variation_reference\x18\x01 \x01(\rR\x16typeVariationReference\x1aC\n" +
	"\aInteger\x128\n" +
	"\x18type_variation_reference\x18\x01 \x01(\rR\x16typeVariationReference\x1a@\n" +
	"\x04Long\x128\n" +
	"\x18type_variation_reference\x18\x01 \x01(\rR\x16typeVariationReference\x1aA\n" +
	"\x05Float\x128\n" +
	"\x18type_variation_reference\x18\x01 \x01(\rR\x16typeVariationReference\x1aB\n" +
	"\x06Double\x128\n" +
	"\x18type_variation_reference\x18\x01 \x01(\rR\x16typeVariationReference\x1a`\n" +
	"\x06String\x128\n" +
	"\x18type_variation_reference\x18\x01 \x01(\rR\x16typeVariationReference\x12\x1c\n" +
	"\tcollation\x18\x02 \x01(\tR\tcollation\x1aB\n" +
	"\x06Binary\x128\n" +
	"\x18type_variation_reference\x18\x01 \x01(\rR\x16typeVariationReference\x1a@\n" +
	"\x04NULL\x128\n" +
	"\x18type_variation_reference\x18\x01 \x01(\rR\x16typeVariationReference\x1aE\n" +
	"\tTimestamp\x128\n" +
	"\x18type_variation_reference\x18\x01 \x01(\rR\x16typeVariationReference\x1a@\n" +
	"\x04Date\x128\n" +
	"\x18type_variation_reference\x18\x01 \x01(\rR\x16typeVariationReference\x1aH\n" +
	"\fTimestampNTZ\x128\n" +
	"\x18type_variation_reference\x18\x01 \x01(\rR\x16typeVariationReference\x1aq\n" +
	"\x04Time\x12!\n" +
	"\tprecision\x18\x01 \x01(\x05H\x00R\tprecision\x88\x01\x01\x128\n" +
	"\x18type_variation_reference\x18\x02 \x01(\rR\x16typeVariationReferenceB\f\n" +
	"\n" +
	"_precision\x1aL\n" +
	"\x10CalendarInterval\x128\n" +
	"\x18type_variation_reference\x18\x01 \x01(\rR\x16typeVariationReference\x1a\xb3\x01\n" +
	"\x11YearMonthInterval\x12$\n" +
	"\vstart_field\x18\x01 \x01(\x05H\x00R\n" +
	"startField\x88\x01\x01\x12 \n" +
	"\tend_field\x18\x02 \x01(\x05H\x01R\bendField\x88\x01\x01\x128\n" +
	"\x18type_variation_reference\x18\x03 \x01(\rR\x16typeVariationReferenceB\x0e\n" +
	"\f_start_fieldB\f\n" +
	"\n" +
	"_end_field\x1a\xb1\x01\n" +
	"\x0fDayTimeInterval\x12$\n" +
	"\vstart_field\x18\x01 \x01(\x05H\x00R\n" +
	"startField\x88\x01\x01\x12 \n" +
	"\tend_field\x18\x02 \x01(\x05H\x01R\bendField\x88\x01\x01\x128\n" +
	"\x18type_variation_reference\x18\x03 \x01(\rR\x16typeVariationReferenceB\x0e\n" +
	"\f_start_fieldB\f\n" +
	"\n" +
	"_end_field\x1aX\n" +
	"\x04Char\x12\x16\n" +
	"\x06length\x18\x01 \x01(\x05R\x06length\x128\n" +
	"\x18type_variation_reference\x18\x02 \x01(\rR\x16typeVariationReference\x1a[\n" +
	"\aVarChar\x12\x16\n" +
	"\x06length\x18\x01 \x01(\x05R\x06length\x128\n" +
	"\x18type_variation_reference\x18\x02 \x01(\rR\x16typeVariationReference\x1a\x99\x01\n" +
	"\aDecimal\x12\x19\n" +
	"\x05scale\x18\x01 \x01(\x05H\x00R\x05scale\x88\x01\x01\x12!\n" +
	"\tprecision\x18\x02 \x01(\x05H\x01R\tprecision\x88\x01\x01\x128\n" +
	"\x18type_variation_reference\x18\x03 \x01(\rR\x16typeVariationReferenceB\b\n" +
	"\x06_scaleB\f\n" +
	"\n" +
	"_precision\x1a\xa1\x01\n" +
	"\vStructField\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x124\n" +
	"\tdata_type\x18\x02 \x01(\v2\x17.spark.connect.DataTypeR\bdataType\x12\x1a\n" +
	"\bnullable\x18\x03 \x01(\bR\bnullable\x12\x1f\n" +
	"\bmetadata\x18\x04 \x01(\tH\x00R\bmetadata\x88\x01\x01B\v\n" +
	"\t_metadata\x1a\x7f\n" +
	"\x06Struct\x12;\n" +
	"\x06fields\x18\x01 \x03(\v2#.spark.connect.DataType.StructFieldR\x06fields\x128\n" +
	"\x18type_variation_reference\x18\x02 \x01(\rR\x16typeVariationReference\x1a\xa2\x01\n" +
	"\x05Array\x12:\n" +
	"\felement_type\x18\x01 \x01(\v2\x17.spark.connect.DataTypeR\velementType\x12#\n" +
	"\rcontains_null\x18\x02 \x01(\bR\fcontainsNull\x128\n" +
	"\x18type_variation_reference\x18\x03 \x01(\rR\x16typeVariationReference\x1a\xdb\x01\n" +
	"\x03Map\x122\n" +
	"\bkey_type\x18\x01 \x01(\v2\x17.spark.connect.DataTypeR\akeyType\x126\n" +
	"\n" +
	"value_type\x18\x02 \x01(\v2\x17.spark.connect.DataTypeR\tvalueType\x12.\n" +
	"\x13value_contains_null\x18\x03 \x01(\bR\x11valueContainsNull\x128\n" +
	"\x18type_variation_reference\x18\x04 \x01(\rR\x16typeVariationReference\x1aX\n" +
	"\bGeometry\x12\x12\n" +
	"\x04srid\x18\x01 \x01(\x05R\x04srid\x128\n" +
	"\x18type_variation_reference\x18\x02 \x01(\rR\x16typeVariationReference\x1aY\n" +
	"\tGeography\x12\x12\n" +
	"\x04srid\x18\x01 \x01(\x05R\x04srid\x128\n" +
	"\x18type_variation_reference\x18\x02 \x01(\rR\x16typeVariationReference\x1aC\n" +
	"\aVariant\x128\n" +
	"\x18type_variation_reference\x18\x01 \x01(\rR\x16typeVariationReference\x1a\xa1\x02\n" +
	"\x03UDT\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12 \n" +
	"\tjvm_class\x18\x02 \x01(\tH\x00R\bjvmClass\x88\x01\x01\x12&\n" +
	"\fpython_class\x18\x03 \x01(\tH\x01R\vpythonClass\x88\x01\x01\x12;\n" +
	"\x17serialized_python_class\x18\x04 \x01(\tH\x02R\x15serializedPythonClass\x88\x01\x01\x127\n" +
	"\bsql_type\x18\x05 \x01(\v2\x17.spark.connect.DataTypeH\x03R\asqlType\x88\x01\x01B\f\n" +
	"\n" +
	"_jvm_classB\x0f\n" +
	"\r_python_classB\x1a\n" +
	"\x18_serialized_python_classB\v\n" +
	"\t_sql_type\x1a4\n" +
	"\bUnparsed\x12(\n" +
	"\x10data_type_string\x18\x01 \x01(\tR\x0edataTypeStringB\x06\n" +
	"\x04kindB6\n" +
	"\x1eorg.apache.spark.connect.protoP\x01Z\x12internal/generatedb\x06proto3"

var (
	file_spark_connect_types_proto_rawDescOnce sync.Once
	file_spark_connect_types_proto_rawDescData []byte
)

func file_spark_connect_types_proto_rawDescGZIP() []byte {
	file_spark_connect_types_proto_rawDescOnce.Do(func() {
		file_spark_connect_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_spark_connect_types_proto_rawDesc), len(file_spark_connect_types_proto_rawDesc)))
	})
	return file_spark_connect_types_proto_rawDescData
}

var file_spark_connect_types_proto_msgTypes = make([]protoimpl.MessageInfo, 30)
var file_spark_connect_types_proto_goTypes = []any{
	(*DataType)(nil),                   // 0: spark.connect.DataType
	(*DataType_Boolean)(nil),           // 1: spark.connect.DataType.Boolean
	(*DataType_Byte)(nil),              // 2: spark.connect.DataType.Byte
	(*DataType_Short)(nil),             // 3: spark.connect.DataType.Short
	(*DataType_Integer)(nil),           // 4: spark.connect.DataType.Integer
	(*DataType_Long)(nil),              // 5: spark.connect.DataType.Long
	(*DataType_Float)(nil),             // 6: spark.connect.DataType.Float
	(*DataType_Double)(nil),            // 7: spark.connect.DataType.Double
	(*DataType_String)(nil),            // 8: spark.connect.DataType.String
	(*DataType_Binary)(nil),            // 9: spark.connect.DataType.Binary
	(*DataType_NULL)(nil),              // 10: spark.connect.DataType.NULL
	(*DataType_Timestamp)(nil),         // 11: spark.connect.DataType.Timestamp
	(*DataType_Date)(nil),              // 12: spark.connect.DataType.Date
	(*DataType_TimestampNTZ)(nil),      // 13: spark.connect.DataType.TimestampNTZ
	(*DataType_Time)(nil),              // 14: spark.connect.DataType.Time
	(*DataType_CalendarInterval)(nil),  // 15: spark.connect.DataType.CalendarInterval
	(*DataType_YearMonthInterval)(nil), // 16: spark.connect.DataType.YearMonthInterval
	(*DataType_DayTimeInterval)(nil),   // 17: spark.connect.DataType.DayTimeInterval
	(*DataType_Char)(nil),              // 18: spark.connect.DataType.Char
	(*DataType_VarChar)(nil),           // 19: spark.connect.DataType.VarChar
	(*DataType_Decimal)(nil),           // 20: spark.connect.DataType.Decimal
	(*DataType_StructField)(nil),       // 21: spark.connect.DataType.StructField
	(*DataType_Struct)(nil),            // 22: spark.connect.DataType.Struct
	(*DataType_Array)(nil),             // 23: spark.connect.DataType.Array
	(*DataType_Map)(nil),               // 24: spark.connect.DataType.Map
	(*DataType_Geometry)(nil),          // 25: spark.connect.DataType.Geometry
	(*DataType_Geography)(nil),         // 26: spark.connect.DataType.Geography
	(*DataType_Variant)(nil),           // 27: spark.connect.DataType.Variant
	(*DataType_UDT)(nil),               // 28: spark.connect.DataType.UDT
	(*DataType_Unparsed)(nil),          // 29: spark.connect.DataType.Unparsed
}
var file_spark_connect_types_proto_depIdxs = []int32{
	10, // 0: spark.connect.DataType.null:type_name -> spark.connect.DataType.NULL
	9,  // 1: spark.connect.DataType.binary:type_name -> spark.connect.DataType.Binary
	1,  // 2: spark.connect.DataType.boolean:type_name -> spark.connect.DataType.Boolean
	2,  // 3: spark.connect.DataType.byte:type_name -> spark.connect.DataType.Byte
	3,  // 4: spark.connect.DataType.short:type_name -> spark.connect.DataType.Short
	4,  // 5: spark.connect.DataType.integer:type_name -> spark.connect.DataType.Integer
	5,  // 6: spark.connect.DataType.long:type_name -> spark.connect.DataType.Long
	6,  // 7: spark.connect.DataType.float:type_name -> spark.connect.DataType.Float
	7,  // 8: spark.connect.DataType.double:type_name -> spark.connect.DataType.Double
	20, // 9: spark.connect.DataType.decimal:type_name -> spark.connect.DataType.Decimal
	8,  // 10: spark.connect.DataType.string:type_name -> spark.connect.DataType.String
	18, // 11: spark.connect.DataType.char:type_name -> spark.connect.DataType.Char
	19, // 12: spark.connect.DataType.var_char:type_name -> spark.connect.DataType.VarChar
	12, // 13: spark.connect.DataType.date:type_name -> spark.connect.DataType.Date
	11, // 14: spark.connect.DataType.timestamp:type_name -> spark.connect.DataType.Timestamp
	13, // 15: spark.connect.DataType.timestamp_ntz:type_name -> spark.connect.DataType.TimestampNTZ
	15, // 16: spark.connect.DataType.calendar_interval:type_name -> spark.connect.DataType.CalendarInterval
	16, // 17: spark.connect.DataType.year_month_interval:type_name -> spark.connect.DataType.YearMonthInterval
	17, // 18: spark.connect.DataType.day_time_interval:type_name -> spark.connect.DataType.DayTimeInterval
	23, // 19: spark.connect.DataType.array:type_name -> spark.connect.DataType.Array
	22, // 20: spark.connect.DataType.struct:type_name -> spark.connect.DataType.Struct
	24, // 21: spark.connect.DataType.map:type_name -> spark.connect.DataType.Map
	27, // 22: spark.connect.DataType.variant:type_name -> spark.connect.DataType.Variant
	28, // 23: spark.connect.DataType.udt:type_name -> spark.connect.DataType.UDT
	25, // 24: spark.connect.DataType.geometry:type_name -> spark.connect.DataType.Geometry
	26, // 25: spark.connect.DataType.geography:type_name -> spark.connect.DataType.Geography
	29, // 26: spark.connect.DataType.unparsed:type_name -> spark.connect.DataType.Unparsed
	14, // 27: spark.connect.DataType.time:type_name -> spark.connect.DataType.Time
	0,  // 28: spark.connect.DataType.StructField.data_type:type_name -> spark.connect.DataType
	21, // 29: spark.connect.DataType.Struct.fields:type_name -> spark.connect.DataType.StructField
	0,  // 30: spark.connect.DataType.Array.element_type:type_name -> spark.connect.DataType
	0,  // 31: spark.connect.DataType.Map.key_type:type_name -> spark.connect.DataType
	0,  // 32: spark.connect.DataType.Map.value_type:type_name -> spark.connect.DataType
	0,  // 33: spark.connect.DataType.UDT.sql_type:type_name -> spark.connect.DataType
	34, // [34:34] is the sub-list for method output_type
	34, // [34:34] is the sub-list for method input_type
	34, // [34:34] is the sub-list for extension type_name
	34, // [34:34] is the sub-list for extension extendee
	0,  // [0:34] is the sub-list for field type_name
}

func init() { file_spark_connect_types_proto_init() }
func file_spark_connect_types_proto_init() {
	if File_spark_connect_types_proto != nil {
		return
	}
	file_spark_connect_types_proto_msgTypes[0].OneofWrappers = []any{
		(*DataType_Null)(nil),
		(*DataType_Binary_)(nil),
		(*DataType_Boolean_)(nil),
		(*DataType_Byte_)(nil),
		(*DataType_Short_)(nil),
		(*DataType_Integer_)(nil),
		(*DataType_Long_)(nil),
		(*DataType_Float_)(nil),
		(*DataType_Double_)(nil),
		(*DataType_Decimal_)(nil),
		(*DataType_String_)(nil),
		(*DataType_Char_)(nil),
		(*DataType_VarChar_)(nil),
		(*DataType_Date_)(nil),
		(*DataType_Timestamp_)(nil),
		(*DataType_TimestampNtz)(nil),
		(*DataType_CalendarInterval_)(nil),
		(*DataType_YearMonthInterval_)(nil),
		(*DataType_DayTimeInterval_)(nil),
		(*DataType_Array_)(nil),
		(*DataType_Struct_)(nil),
		(*DataType_Map_)(nil),
		(*DataType_Variant_)(nil),
		(*DataType_Udt)(nil),
		(*DataType_Geometry_)(nil),
		(*DataType_Geography_)(nil),
		(*DataType_Unparsed_)(nil),
		(*DataType_Time_)(nil),
	}
	file_spark_connect_types_proto_msgTypes[14].OneofWrappers = []any{}
	file_spark_connect_types_proto_msgTypes[16].OneofWrappers = []any{}
	file_spark_connect_types_proto_msgTypes[17].OneofWrappers = []any{}
	file_spark_connect_types_proto_msgTypes[20].OneofWrappers = []any{}
	file_spark_connect_types_proto_msgTypes[21].OneofWrappers = []any{}
	file_spark_connect_types_proto_msgTypes[28].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_spark_connect_types_proto_rawDesc), len(file_spark_connect_types_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   30,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_spark_connect_types_proto_goTypes,
		DependencyIndexes: file_spark_connect_types_proto_depIdxs,
		MessageInfos:      file_spark_connect_types_proto_msgTypes,
	}.Build()
	File_spark_connect_types_proto = out.File
	file_spark_connect_types_proto_goTypes = nil
	file_spark_connect_types_proto_depIdxs = nil
}
