apiVersion: v1
kind: Service
metadata:
  name: spark-connect
  namespace: spark-connect
  labels:
    app: spark-connect
spec:
  selector:
    app: spark-connect
  ports:
    - name: grpc
      port: 15002
      targetPort: 15002
      protocol: TCP
  type: ClusterIP
