[package]
name = "scg-proxy"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[dependencies]
scg-auth = { path = "../auth" }
scg-genproto = { path = "../genproto" }
scg-observability = { path = "../observability" }
scg-routing = { path = "../routing" }
tokio = { workspace = true }
tokio-stream = { workspace = true }
tonic = { workspace = true }
tower = { workspace = true }
prost = { workspace = true }
async-trait = { workspace = true }
futures = { workspace = true }
parking_lot = { workspace = true }
tracing = { workspace = true }
tracing-opentelemetry = { workspace = true }
opentelemetry = { workspace = true }
async-stream = "0.3"
thiserror = { workspace = true }

[dev-dependencies]
scg-store-memory = { path = "../store-memory" }
scg-store-redis = { path = "../store-redis" }
scg-pool-static = { path = "../pool-static" }
scg-auth = { path = "../auth" }
scg-observability = { path = "../observability", features = ["testing"] }
tokio = { workspace = true }
async-stream = "0.3"
parking_lot = { workspace = true }
reqwest = { workspace = true }
opentelemetry = { workspace = true }
opentelemetry_sdk = { workspace = true, features = ["rt-tokio", "testing"] }
opentelemetry-proto = { workspace = true }

